### ISSUE TITLE
[bluetooth] Discovery is unrealiable

### ISSUE THREAD

**Issue by paulianttila** [openhab/openhab-addons#10139]
Discovery at least with BlueGiga adapter, seems to unreliable from user perpective.

Situation after first scan (2021-02-13 at 13:23:58)

![Screenshot 2021-02-13 at 13 23 58](https://user-images.githubusercontent.com/5506533/107848838-5f6d0380-6dff-11eb-9e33-a1a0711fd25d.png)

During next scan, one new device found (2021-02-13 at 13:24:18)

![Screenshot 2021-02-13 at 13 24 18](https://user-images.githubusercontent.com/5506533/107848870-b07cf780-6dff-11eb-99ec-edaa70238d39.png)

After scan complete, inbox shows only new device (2021-02-13 at 13:24:28)

![Screenshot 2021-02-13 at 13 24 28](https://user-images.githubusercontent.com/5506533/107848960-955eb780-6e00-11eb-99da-e94548bb4538.png)

During next scan (2021-02-13 at 13:24:49)
![Screenshot 2021-02-13 at 13 24 49](https://user-images.githubusercontent.com/5506533/107848982-bc1cee00-6e00-11eb-96d9-d4f1e7069295.png)

After next scan, inbox is empty as no new devices discovered (2021-02-13 at 13:24:56)

![Screenshot 2021-02-13 at 13 24 56](https://user-images.githubusercontent.com/5506533/107848984-c17a3880-6e00-11eb-8f2e-5b16e42e1850.png)

Full log:
[log.txt](https://github.com/openhab/openhab-addons/files/5975584/log.txt)

Scan seems to show only new devices, which has been found during scan. Is that intention?

**Comment by paulianttila** [comment]
If I remove the following code, inbox seems to work correctly. New devices are added to inbox and old devices which which hasn't been updated after a while will be removed from inbox.

https://github.com/openhab/openhab-addons/blob/6829ff657ab27a35e5ab54913f64b803624e7e11/bundles/org.openhab.binding.bluetooth/src/main/java/org/openhab/binding/bluetooth/discovery/internal/BluetoothDiscoveryService.java#L218-L222

@cpmeister, you have added this functionality by purpose, so do you think it's working correctly?

**Comment by cpmeister** [comment]
Discovery is pretty finicky at the moment, but that is kinda unavoidable especially if you have a large number of devices you are discovering that each require a connection attempt to discover things from. The bluetooth adapters will easily get overwhelmed with connection requests and would cause some of those discoveries to fail.

There are a lot of changes that would be required to reduce discovery failures. I'm already in the process of making those changes but my progress has been slowed from the lack of merging of my PRs.
I already have a PR that adds an expiring cache for the snapshot so that you can reattempt discoveries if they failed to properly discover the first time.

It was definitely an oversight on my part to not allow devices to be rediscovered during manual scans.

**Comment by paulianttila** [comment]
>Discovery is pretty finicky at the moment, but that is kinda unavoidable especially if you have a large number of devices you are discovering that each require a connection attempt to discover things from. The bluetooth adapters will easily get overwhelmed with connection requests and would cause some of those discoveries to fail.

Yes, I have seen discovery fails very often, even I have only one device which need connection for discovery

**Comment by lsiepel** [comment]
@paulianttila if i look at th ePR history for the bleutooth bindings, i see several that in some way or another affect this. Could you verify if this is still an issue?

**Comment by paulianttila** [comment]
I don't use bluegiga adapter (or any other bluetooth adapters) anymore as it's not reliable enough for daily use , so I will close this issue for now.
