### ISSUE TITLE
[hue] [zigbee] openhab does not change color on a bulb or zone, if the bulb or zone is in white mode

### ISSUE THREAD

**Issue by Marlow925** [openhab/openhab-addons#10159]
OpenHAB 2.5.12

When changing the color on a zone, room or bulb in OpenHAB using the PaperUI or similar, and if the color bulb is in warm white/white mode, the change of color is ignored or in some cases a random white color is selected. 

This behaviour was not the case in early versions of 2.5. It's been a while since I used/tested it.

I'm not sure, if #9741 refers to the same issue or a similar cause, but I feel, that when one sets a color or a warm white tone in OpenHAB, OpenHAB should be able to switch the bulb to the correct mode first, if needed.

If I use the Hue App (or equivalent) and set the bulb, room or zone to a color first, then OpenHAB will correctly set colors.

/M

**Comment by Marlow925** [comment]
Additionally, OpenHAB will also only change some lights to the requested color, if the lights of the zone or room are set to different colors.

**Comment by Marlow925** [comment]
One more observation: this seems mainly to happen with Zigbee bulbs from 3rd party manufacturers (Müller Tint, Ikea, Livarno/Lidl). 

In one room, the genuine Philips Hue Strip will change color as directed, but the Müller Tint bulbs otherwise in that room won't.

The Gledopto LED drivers don't seem to have this issue. They change correctly, ever time.

It is peculiar though, as other 3rd party apps for the Philips Hue system don't have these issues. The "Hue Essentials" app on Android is able to set the correct color every time, so there seems to be something in the approach of the OpenHAB Hue Binding, that causes these issues.

**Comment by Marlow925** [comment]
After a good bit testing, I've found out, that this problem only occurs with Lidl/Livarno/TuyaSmart and Müller tint bulbs.

And it happens as well in the Hue binding as well in the Zigbee binding.

https://live.staticflickr.com/65535/50979200446_30d21605a8_b.jpg

On the Lidl bulb, the "Brightness" and the "Color Temperature" slider are working. The "Color" slider does nothing. The spot is connected using a Bitron Zigbee USB adapter.

The Ikea bulb is also connected via the Zigbee binding. It only presents the color slider and that's all working.

The Hue bulb is on the hue hub and that works flawless, also when the color or color temperature is set.

The Müller tint bulb is connected to the Hue hub. If I change the color in the Hue app or the Hue Essentials app, the color slider will reflect the correct color, but when I set the color in OpenHAB, it will just do nothing.

So it seems, there is something with how certain brands of Zigbee bulbs get controlled and it's not limited to the Hue hub, but also to the Zigbee binding.

/M

**Comment by gkunz** [comment]
Hi all,
continuing the community thread here as well since I have a few questions the maintainers hopefully can answer here.

In general, I have the same issue and the root cause seems to be the following: The when changing the color mode from color temp to color, the hue binding defaults to using HS color mode. The TS0505A bulbs don't seem to work with this, yet they work fine in XY mode.

Question to hue maintainers: is there a specific reason for defaulting to the HS mode instead of the  XY mode? (for instance [here](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.hue/src/main/java/org/openhab/binding/hue/internal/handler/LightStateConverter.java#L71)?

Reading the Hue API, it seems that XY mode is preferred over HS mode [Hue API core concepts](https://developers.meethue.com/develop/get-started-2/core-concepts/):

> xy beats ct beats hue, sat – Simple.

Also, CIE mode does not seem to be hardware dependent whereas HS is according to the [Hue Light API](https://developers.meethue.com/develop/hue-api/lights-api/#get-attr-and-state):

> Note, that hue/sat values are hardware dependent which means that programming two devices with the same value does not garantuee that they will be the same color.

and

> The CIE xy color is absolute, independent from the hardware.

Moroever, the official Hue app works fine with my bulbs AND sets them to XY mode.

I have changed the code to default to XY mode and changing between color temp and color mode works fine with my cheap TS0505A bulbs. Note that I don't have other color bulbs available for testing, so I might miss something with regards to other manufacturers.

Proposals for a solutions:
As of today, I see two potential solutions:

1. change the default to XY instead of HS. This might have negative impacts I cannot judge at the moment - happy to learn more though.
2. add a kind of vendor map to the code to handle bulbs like the TS0505A, i.e., switch those to XY mode by default. My test code is based on this approach. I can also create a PR for discussing this more detail. 

Thanks
Georg
