### ISSUE TITLE
[homekit] Temperature sensors, possibly thermostats not returning correct values

### ISSUE THREAD

**Issue by ecdye** [openhab/openhab-addons#10275]
@yfre 

There seems to be an issue after the milestone 2 build where the temperature sensor only returns the maximum value regardless of the fact that the temperature in openHAB appears correctly. Here is an example log line it says this no matter what temperature it actually is, and then displays 100 ˚F in the home app.

```
2021-03-03 07:44:48.780 [WARN ] [istics.impl.base.FloatCharacteristic] - Detected value out of range 69.0. Returning max value instead. Characteristic io.github.hapjava.characteristics.impl.thermostat.CurrentTemperatureCharacteristic@c3ad04
```

**Comment by yfre** [comment]
is maxValue set at item?  have you made it using mainUi or text configuration? what is the actual temperature and is "use Fahrenheit" set to true in homekit configuration?

**Comment by ecdye** [comment]
> is maxValue set at item? 

No, I did not set it I just left it to default.

> have you made it using mainUi or text configuration?

mainUI

>  what is the actual temperature 

The actual temperature is 69, the log message always says `Detected value out of range [insert actual temperature]....`.

> is "use Fahrenheit" set to true in homekit configuration?

yes

**Comment by yfre** [comment]
i think i know what it is doing. 
100 is the default max temperature in Celsius.  
in the recent version i have added support for Fahrenheit for custom max/min. probably I did something wrong for default values. it takes default 100 as F and converts it to C, which is 37 C. compares it with 69 and decides that 69 is above limit and sends 37 C = > 100 F. 

it is definitely a bug. 

could you please try one thing  - add custom maxValue  at item and check whether it works correctly with custom maxValue, looks like this in mainUI (but do it as currentTemperature)

![image](https://user-images.githubusercontent.com/11726616/109877190-fc8ac180-7c72-11eb-9fe0-2bec900a8af6.png)

**Comment by ecdye** [comment]
If I manually set the min and max values to 0 and 100 respectively yes it works. Which means it will serve as a workaround for the moment until the bug is fixed

**Comment by thales-man** [comment]
I’m also having issues with temperature sensors not reporting correctly. External sensors showing 1.9˚C are being translated to 50˚F. This clearly isn’t right. I’d hazard having monitored this temperature gauge that 50 is some sort of default floor value as it hasn’t changed for hours, even though it’s changed outside. I’m not sure what the purpose of having min / max values is quite frankly. It should just translate correctly the given value from one format to the next. 
 F=(Cx1.8)+32

**Comment by yfre** [comment]
if max/min values not provided, then home app on ios device will use defaults for max/min. to my understanding, min/max are useful to have proper scale for gauge representation in home app, e.g. on thermostats

but the actual issue in your case is C->F conversion. can you double check in main UI the temperature on items? is it 1.9C. 
try to increase max value to 100 or so to see what is the resulted value. maybe we get an idea what is wrong, e.g. if it is 66.2 then it converts 19 C and not 1.9 C

**Comment by thales-man** [comment]
Hi Eugen,  I'm clearly not explaining the problem properly. 

I have a sensor in openHAB reporting a temperature of 1.9˚C => that is 35.4˚F. 
This sensor is exposed using the apple home kit metadata to the home app using the characteristics of 'temperature sensor' and 'temperature sensor current temperature'.
In the Home App this sensor shows a temperature of 50˚F.
Until the temperature from the sensor exceeds 10˚C, the Home App temperature won't change; it remains at 50˚F.
Is that clearer?

**Comment by yfre** [comment]
ok. i think i got it. 
the default value for Min temperature in homekit is 10 C, which maps to 50 F. 
means, if openhan sends value below 10C it will get rounded to 10C and then translated to fahrenheit

10 C as default min temperature is defined by apple. but it can be overwritten. 
add minValue to your configuration as shown above. e.g. set minValue to 0
![image](https://user-images.githubusercontent.com/11726616/140061955-8790918e-4d51-4817-bb01-4c14cab47f9f.png)

**Comment by thales-man** [comment]
BTW, I would dispute this statement:
_10 C as default min temperature is defined by apple._
I have written bridges using HAP protocols and there is no range restriction on temperatures. You update the appropriate characteristic and it shows it... It's a simple as that.
HAP Specification PG 175 9.35 Current Temperature

**Comment by thales-man** [comment]
That's not the temperature sensor, it's the thermostat. They aren't the same. It might be applicable for internal temperatures to drop that low. However, frost levels are usually determined to be around 7.5˚C.

**Comment by yfre** [comment]
you are right, the target temperature is used by thermostats, but the second, current temperature, is used by temperature sensor. and it does have default min and max values defined by apple. it is according to last public HAP spec, 0 and 100 C. which should be fine for you case.

i just checked and the library has correct default values, 0 and 100
https://github.com/yfre/HAP-Java/blob/45d9403dac182aae4e9de6c171b16b97b89f3e1c/src/main/java/io/github/hapjava/characteristics/impl/thermostat/CurrentTemperatureCharacteristic.java#L12

so, im not sure why in your case the different values were used as defaults. maybe newer IOS has different default values. maybe it is related to Fahrenheit conversion. 
can you share your config/homekit metadata for that item so that i can try to reproduce.

**Comment by thales-man** [comment]
I've raised a bug with Apple as it isn't satisfactory for a temperature sensor not to be able to reflect sub-zero temperatures.

**Comment by thales-man** [comment]
> can you share your config/homekit metadata for that item so that i can try to reproduce.

Hi Eugen

I'm not sure what config data you'd want. What I can say is, I hadn't got any config data beyond that which openHAB set's by default. The device in use is an Oregon 433mhz (RFXComm TRX433E bound device) set up in the garden for outside temperature notifications. The problem is obvious now as outside temperatures sink below your 10˚C marker. The issue I've recorded with Apple is the fact that once we get to 32˚ƒ it's not going to go any lower as the range is restricted from 0˚C to 100˚C. It's a bit pitiful that Apple can't think beyond the end of their noses... How many thermometers stop at the freezing point of water? I mean, does an M1 only deal with unsigned bytes?? If it did, it wouldn't be much cop, would it...
