### ISSUE TITLE
[Gardena] Suspected memory leak (especially) when api is down

### ISSUE THREAD

**Issue by bf8392** [openhab/openhab-addons#10516]
The Gardena Binding seems to have a Memory leak when the Gardena developer api is down (it crashes the whole installation). When I deactivate the Gardena Binding I have no issues...
I sadly can't provide any logs for the moment, as the crash happened on a remote location, and I have to go there by the weekend...I'll then provide logs if someone wants to look into...
It happened 4 times now, and stopped when turning Gardena binding off...Also had database issues because of "unclean" shutdowns....

## Your Environment
* Version used: (e.g., openHAB and add-on versions)
* Openhab 3.0.1, latest Docker on latest HypriotOS, RPI 4 B+

**Comment by Bruetti1991** [comment]
Some time ago I had the same issue with my gardena binding. When the binding was running for some time, I got a lot ‘TimeoutException’ and ’ simultaneous.logins’ errors that slowed down my whole Openhab.

The problem is, how the binding handles connection losses. The websocket connection to the Gardena API randomly just closes for no obvious reason. This leads to a complete reinitalization of the whole binding instead of just restarting the closed websocket. Also the binding does not properly synchronize the calls when a websocket closes. So sometimes the binding restarts a single websocket more than once. The longer the binding is running, the more connections/threads are started, which will slow down Openhab and/or lead to a crash.

To resolve this issue, I fixed the handling of websockets. See #11824 
I never had issues after that. Connection losses are now properly detected and the websockets are restarted.

For an updated jar file, see [openHAB Cummunity](https://community.openhab.org/t/cgroup-fork-rejected-by-pids-controller-in-system-slice-openhab-service/123195/6?u=bruetti91)
