### ISSUE TITLE
[openwebnet] shutter position should stay NULL after reboot/reconnect

### ISSUE THREAD

**Issue by weltraumbagger** [openhab/openhab-addons#10662]
since openhabian 3.1.0m4 shutters (who2) on reboot always restores to 0 (open). this might make rules (e.g. sun-protection) work wrong because the state could differ from the real state.

no matter if restored to 0 (mostly always wrong in night-times) or restored to 100 (mostly wrong during day). so for short interrupts (e.g. only a reboot) somebody could use a rule to check offline-time and eventually then use persistence to reload the old states.

but in generally, if the state would stay NULL then this can be recognized from rules and handled.

**Comment by mvalla** [comment]
according to the discussion in the community thread, after a reboot the value of the channel will stay NULL until a full up/down of the shutter will be executed to calculate again the estimated position. 
Similarly after a disconecction from the gateay since the shutter position will not be valida anymore, the value will be set to UNDEF.
