### ISSUE TITLE
[IpCamera] FFmpeg Output Folder overwriting issue

### ISSUE THREAD

**Issue by houshasen** [openhab/openhab-addons#10661]
## Expected Behavior
When multiple IpCamera Binding Things are created, each should have own camera streaming.

## Current Behavior
Currently, the default FFmpeg Output Folder is "/etc/openhab/html/camera1/"; therefore, when I created two generic IpCamera that uses RTSP input and transcoding using FFMPEG, both output ended up going the same folder and therefore, output stream looked identical for both.

## Possible Solution
1. Rename default output folder perhaps based on the server port as that is user selected and should be unique for each camera.
2. Better solution is leave folder but output stream should use proper file. Perhaps, name file using server port information? This part I am uncertain as not exactly sure how internally this is being processed.

## Steps to Reproduce (for Bugs)
1. Create one generic IPCamera entity and fill everything except leave FFmpeg Output Folder as default i.e. "/etc/openhab/html/camera1/"
2. Create a separate generic IPCamera entity and fill everything but again leave FFmpeg Output Folder as default.
3. Create Video Cards for each using HLS outputs for each camera.

## Context
I did not realize why I was seeing Bedroom's streaming on my Doorbell streaming. Sometimes one failed to stream while the other worked (but still always bedroom). After typing in actual URL for each HLS output, I then realize two are identical from the source level. But initially I thought it was due to Video Card issue on UI so I tried to delete recreate. I even tried to stop and restart THINGs.

## Your Environment
* Version used: OpenHabian with OpenHAB version 3.1.MS4 
* Hardware: Debian 10 based Virtual Machine

**Comment by Skinah** [comment]
Thank you for reporting this, will have a think of what makes the most sense.

**Comment by Skinah** [comment]
We have to consider what happens when someone uses MANUAL vs DISCOVERY methods to add a new camera, does it work smoothly for both? Does the change create a breaking change? These are what I am considering whilst looking at possible ways forward.... 

When MANUALLY adding a camera, one option is to leave the field blank and make it a required field they have to fill it in before the thing can be created. I don't like this, as it makes it harder for a linux noob to get working due to folder write permissions needing to be correct. The other way forward would be to make the default be "auto" and if the user does not change it from auto, then the binding changes it to be "/etc/openhab/html/cameras/UniqueIDhere/".

Regarding the use of the serverPort: It is a valid use case to use -1 to turn off the file serving features. We have to think about future features that may need a folder when a user has set the port to -1. In this case multiple cameras would then use the same folder location if based on the serverPort.

DISCOVERY:
I prefer to use the IP with dots removed, which could be a hostname. If the cameras hostname is 'gate.router' then the folder would become "/etc/openhab/html/cameras/gaterouter". If it has a normal IP it would be "/etc/openhab/html/cameras/19216816". Since discovery already uses this logic already to create the UniqueID, it matches up with what is proposed above for manual adding.

When a user opens the auto discovered thing to add the user and pass, the folder is already showing correctly what the binding will use and the user can review and change it to what they prefer, from then on it will not change and is set at what the user originally reviewed the setting to be.

Renaming the stream is not what I prefer, but will stay open to this approach if it ends up solving all issues and does not create breaking changes. I see two issues with renaming the stream: The idea is to have a predictable name that rules and widgets can use, and secondly at some point it may be necessary to purge all the files in that folder. With HLS the files can build up and clearing them out to reduce space is one thing that may happen, so encouraging a separate folder for each camera I think is a better approach. It will probably create cleaner and less code to not use a variable in multiple stream names and recordings that the camera creates.

SUMMARY of what I prefer:
1. Change the default to 'auto' for manually added things. The field description MUST be updated to state it needs to be a unique folder, which it currently does not. The first time the camera comes ONLINE the path is replaced with what the binding will use and the UID, so auto is not seen if a user goes in to review the config settings after the camera is already created.
2. For auto discovered cameras, this can be fixed as discussed above and is worth doing as it causes no breaking changes. In this case the 'auto' value would never get seen at any stage.
