### ISSUE TITLE
Resol binding in version 3.1 M4 not updating values

### ISSUE THREAD

**Issue by EjvindHald** [openhab/openhab-addons#10684]
I am using the OH version 3.1 M4 where the new Resol binding has been included.

I have configured everything using files, and the connection is fine.

Upon startup of OH all the temperatures and pump measures are updated and show correct values. 

However, these values seem to be static - they are not updated as they change in my KM2 device.

If I restart the binding using Karaf console I get an one time update of the values.

I saw similar behaviour in the Resol binding for OH version 2.x, if the binding was activated using the addons folder instead of Market Place.

My installation is Linux Ubunto.

**Comment by ramack** [comment]
This seems to be fixed in the meantime, probably by some change in core with the UnitsOfMeasurement. The resol binding emits l/h which doesn't seem to be a known unit in class `org.openhab.core.library.unit.Units`

Is this an issue in the binding and it should convert the data into l/min, or should the l/h be added in the core?

**Comment by ramack** [comment]
BTW the binding just forwards the unit in a string from the used vbus-java library, so potentially there might come up another unit which is not known in core. While some unit symbols ("%RH", "Ω") are already handled specially in ResolThingHandler.java:packetReceived() other devices (which was not yet tested) might uses new unit strings for which we might need to add a special handling, too.

**Comment by ramack** [comment]
RP for for the bugfix for this issue is ready for review!
