### ISSUE TITLE
[configuration] Make it possible that bridge is flagged as required for a thing

### ISSUE THREAD

**Issue by coeing** [openhab/openhab-addons#10802]
Hi there,

We develop the Bosch Smart Home binding for openHAB. All of our things require the Bosch Smart Home Controller as a bridge. But currently it does not seem to be possible to force the user to choose a bridge for a thing. For other configuration parameters this is possible by setting `required=true`, but the bridge configuration setup is done in `thing-types.xml` instead of `configs.xml`, so there is no such flag.

Maybe I am missing something? I have the feeling that this is a quite basic feature that should be already there, but I could not find any information about it.

Thanks for any further info! :)

PS: We got this requests from one of our testers and he did not see such thing in the other binding he uses: https://github.com/stefan-kaestle/openhab2-addons/issues/63

**Comment by lsiepel** [comment]
@lolodomo isn't this something for the core repo? This would i.m.h.o. opinion be an improvement for user experience. I have noticed this with PlugwiseHA binding too. 
Every Thing from that binding needs a Bridge to function correct. If not selected, the user will eventually get an error, Thing offline due to missing bridge, but it would be better if it can be forced to select one.

**Comment by J-N-K** [comment]
IMO adding `supported-bridge-type-refs` indicates that a bridge is mandatory. I believe there is no thing with an optional bridge or does anyone know of such a thing @openhab/add-ons-maintainers? 

We currently have no validation in core for that, but that would just prevent the thing from trying to initialize. This should be added, but it does not solve your issue. UI should validate that, it already knows that a bridge should be added, because it shows the input-field for a bridge.

**Comment by jlaur** [comment]
I think most bindings perform their own validation in `initialize()`:

https://github.com/openhab/openhab-addons/blob/2c2097d6461efa805cbeb661902fa4611f5c8f10/bundles/org.openhab.binding.hdpowerview/src/main/java/org/openhab/binding/hdpowerview/internal/handler/HDPowerViewRepeaterHandler.java#L70-L75

I'm not aware of any bindings with an optional bridge, it's not something I have thought of tbh. Didn't search though, but haven't seen it.

Conceptually thinking, it might make sense though? I could imagine having a device with a local API, but also having some additional functionality offered through a cloud service. As an example, a video doorbell providing a local video stream, but also providing facial recognition etc. through a service. In this case the cloud account might be the bridge. Multiple things could then have the same bridge to avoid redundancy (like in the Netatmo binding which ended up with two layers of bridges), but it could be possible to opt-out and run it fully local without any account/bridge. Just loudly thinking...

**Comment by kaikreuzer** [comment]
You are all correct, if there's a `supported-bridge-type-refs`, it means that the Thing requires exactly one of the listed bridges.

If I understand the OT correctly, I would agree with @lolodomo that this is rather a UX issue: When manually creating a new Thing in the Main UI, the UI allows the Thing creation without having a bridge selected. While an error marker appears for mandatory configuration parameters, this does not happen for the bridge selection. In practice, this bridge selection is easily missed and the user then wonders, why the Thing does not work.

@coeing If this is indeed your issue, I would suggest to close this issue and rather open one in https://github.com/openhab/openhab-webui. If this is not your issue, please explain what we got wrong. 😉
