### ISSUE TITLE
[pushover] fails to send attachment

### ISSUE THREAD

**Issue by gmccandless** [openhab/openhab-addons#11225]
When trying to send a jpeg attachment I receive the error below.
_Script execution of rule with UID 'Notification-2' failed: Skip sending the message as file 'filename=/etc/openhab/html/Porch.jpg' does not exist. in Notification_

Additionally I have also tried using a URL and receive the same type of error.
_Script execution of rule with UID 'Notification-2' failed: Skip sending the message as file 'http://localhost:8080/static/Porch.jpeg' does not exist. in Notification_

To confirm there is no issue with my account I have tried to send the attachment manually using the command below. No error is returned and the message is delivered as expected.

**curl -s \
--form-string "token=MYTOKEN" \
--form-string "user=MYUSER" \
--form-string "message=System Message: There is someone at the front door." \
-F "attachment=@/etc/openhab/html/Porch.jpeg" \
https://api.pushover.net/1/messages.json**

This is the rule entry I'm using:

`val actions = getActions("pushover", "pushover:pushover-account:ce12ed7b9b")
     actions.sendAttachmentMessage(Push_Notification.state.toString, "openHAB", "/etc/openhab/html/Porch.jpeg", null)`

**Comment by gmccandless** [comment]
@cweitkamp yes I am still facing the issue, although I have a workaround at present, But it would be good to get it working as it should. Below are the permissions that are currently set and I've attached a copy of the file for your reference.

-rw-r--r-- 1 openhab openhab 876552 Oct 16 16:16 Porch.jpeg

![Porch](https://user-images.githubusercontent.com/4215146/137599756-2cbbea78-18c2-46a2-b913-a44eb1fd91c5.jpeg)

**Comment by cweitkamp** [comment]
I downloaded you example image and gave it a try. It was possible for me to send it without an error.

> When trying to send a jpeg attachment I receive the error below.
Script execution of rule with UID 'Notification-2' failed: Skip sending the message as file 'filename=/etc/openhab/html/Porch.jpg' does not exist. in Notification

Please check the spelling of your file extension. The error message revels `jpg` instead of `jpeg`. If that does not help it would be nice to have an TRACE log of the Pushover binding from the moment your rule is executed.

**Comment by wborn** [comment]
Let's close this as it seems to be a user error.
