### ISSUE TITLE
[influxdb] no datapoints found if metadata contains `item`

### ISSUE THREAD

**Issue by maglnet** [openhab/openhab-addons#11288]
## Expected Behavior

Given the following item configuration:
```
Number:Temperature someStupidName (gTempSensors) { influxdb="temperature" [item="tempOutdoor"] }
```

I expect to read and write data to and from influxdb with a tag `item=tempOutdoor`.

## Current Behavior

- data is written to influxdb with tag `item=tempOutdoor`
- data is queried with `WHERE item = 'someStupidName';` for v1 and `filter(fn: (r) => r["item"] == "someStupidName")` for v2

## Possible Solution

Within the `createQuery` methods it may be possible to get the correct item name from metadata if available.
This would be managed the same way, like getting the measurementName from metadata if available here:

I'd create a PR with a possible solution soon.

https://github.com/maglnet/openhab-addons/blob/1f18dda30134066cb62e772b04353dc77f964929/bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx1/Influx1FilterCriteriaQueryCreatorImpl.java#L52
https://github.com/maglnet/openhab-addons/blob/1f18dda30134066cb62e772b04353dc77f964929/bundles/org.openhab.persistence.influxdb/src/main/java/org/openhab/persistence/influxdb/internal/influx2/Influx2FilterCriteriaQueryCreatorImpl.java#L52

## Steps to Reproduce (for Bugs)

see #11290 

## Context

the reason why I set an item name via the metadata is, that my OH-ItemNames are named by the hardware (not sure if that's good practice) but my influxdb data should have some more clear names to be able to create queries via the web interface easily.

## Your Environment

- OpenHAB 3.1.0
- Raspberry PI
- InfluxDB v2

**Comment by lujop** [comment]
Not sure to want to accept that, because the current item and tag logic is quite complex to support migrated data from old versions and other edge cases. And I don't want to complicate it even more if it's not absolutely necessary and benefits common uses cases.

With current options, you can set the measurement name by using metadata, and you can also set arbitrary tag names. I think that with that you can have your data with good structure and meaning, despite not controlling the names of the items.

Why do you don't want to use custom tags instead of hacking with item tagname?

**Comment by maglnet** [comment]
I really don't see that much complexity in the tag and item name logic during the query time, please check the linked PR that fixes the described issue with very low effort.

> Trying to override the item tag name it's not a documented neither expected behavior in my opinion.

Well, you're right, but neither it is documented, that it's not allowed to use the key `item`, so my thought was to try to override the default, that worked fine when _writing_ to influx db but not when _reading_ :-)

**Comment by maglnet** [comment]
Just as an additional thought:

If there are any edge cases or migration cases where there's an metadata tag named `item` in the current configuration then it would have the same problem as I discovered:  
It would write to tag `item=A` but query `item=B` so, I don't really get the case where there may be a working edge case.

**Comment by lujop** [comment]
I've been considering it but I'm sorry to say that for me it's a no.
Your PR is very well done, clean, and tested but  I don't want to introduce that behavior. After all, it introduces more complexity for an edge case that in my opinion isn't necessary because it can be supported with current options.

Indeed, it's not a lot of complexity, but for me, the existing one is more than desirable and if you look at the last addon commits you will see that had been some bugs about edge cases.
And supporting that is a little extra complexity that the addon will have forever and every added contract constraints future changes.

In your last comments, you didn't ask why using another custom tag name is not an option for the use case you exposed.

In case you don't agree with my opinion just add a comment and I will ask some other maintainer to give his opinion.

**Comment by J-N-K** [comment]
I'm no longer maintainer here, but I agree with @lujop.

**Comment by kaikreuzer** [comment]
> my OH-ItemNames are named by the hardware (not sure if that's good practice) 

I can answer this: No, definitely no good practice! The item layer is the functional level of openHAB, which should in theory be completely independent from the underlying hardware and hence the item names should be independent as well.

As per the suggested feature: I agree with @lujop and @J-N-K - this doesn't feel to be a good fit to how openHAB is structured in general and I'd rather vote against such a feature.

**Comment by maglnet** [comment]
Thanks for clarifying this. I'll then start renaming the problematic items, so it should not be a problem anymore.

Nevertheless I think I'll create a new PR later to add a hint to the `README` that overriding the tag `item` is not a good idea :-)
If this is finished, I'll close this issue.

**Comment by lujop** [comment]
Sure, thank you @maglnet
