### ISSUE TITLE
[http] failed calls in logging that are actually successful

### ISSUE THREAD

**Issue by idserda** [openhab/openhab-addons#11369]
## Expected Behavior
HTTP calls that have a 20x response should be considered successful 

## Current Behavior
Only HTTP calls that have a 200 response are considered successful. All other 20x responses (so 201 Created, 204 No Content, etc) are marked as failed by the binding. This results in a lot of incorrect warning lines in the log.  

## Possible Solution

Change [this line](https://github.com/openhab/openhab-addons/blob/main/bundles/org.openhab.binding.http/src/main/java/org/openhab/binding/http/internal/http/HttpResponseListener.java#L67) to use `response.getStatus().isSuccess()`

## Steps to Reproduce (for Bugs)

1. Do a http call that returns a 201, 204 or other non-200 response
2. See this line appear in the OH log: `[WARN ] [p.internal.http.HttpResponseListener] - Requesting '<url>' (method='POST', content='org.eclipse.jetty.client.util.StringContentProvider@704d4f0e') failed: 201 Created`

## Context
I'm calling the [DSMR-reader](https://github.com/dsmrreader/dsmr-reader) REST api  from OH. This endpoint returns 201 created. 

Workaround for now: `log:set ERROR org.openhab.binding.http.internal.http.HttpResponseListener`

## Your Environment
openhab 3.2.0.M3

**Comment by giig1967g** [comment]
Hi,
is my error in openhab.log caused by the same bug?

`2022-01-20 07:34:45.976 [WARN ] [p.internal.http.HttpResponseListener] - Requesting 'http://api.ipify.org/' (method='GET', content='null') failed: HttpConnectionOverHTTP@157cba0::SocketChannelEndPoint@1324eea{l=/192.168.88.5:40772,r=api.ipify.org/54.91.59.199:80,ISHUT,fill=-,flush=-,to=131/0}{io=1/0,kio=1,kro=1}->HttpConnectionOverHTTP@157cba0(l:/192.168.88.5:40772 <-> r:api.ipify.org/54.91.59.199:80,closed=false)=>HttpChannelOverHTTP@1dec3b4(exchange=HttpExchange@4f3030{req=HttpRequest[GET / HTTP/1.1]@182e352[TERMINATED/null] res=HttpResponse[null 0 null]@f4b256[PENDING/null]})[send=HttpSenderOverHTTP@11c1e1f(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@3b697c{s=START}],recv=HttpReceiverOverHTTP@e3969a(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]]`

**Comment by J-N-K** [comment]
The issue reported here is about successful requests (2xx) with a code other than 200 being reported as failed. Your request looks like it really failed.

**Comment by giig1967g** [comment]
thanks
