### ISSUE TITLE
[deconz] Add On/OFF Switch to colortemperaturelight

### ISSUE THREAD

**Issue by batje** [openhab/openhab-addons#11587]
Currently the colortemperaturelight lights do not have an ON/OFF switch. The way to switch these lights off is by setting the Brightness to 0.

However, in the Deconz web application, there *is* an OFF/ON switch:

PUT http://deconz-upstairs/api/489ABDC1EF/lights/2/state
with payload
{"on":false,"transitiontime":9,"bri":0}
And when the brightness is higher than 0:
{"on":true,"transitiontime":9,"bri":14}

Turning that into a Switch would be very helpful.

If you *are* already setting the 'on' value, then I might be suffering from #10585 as well, but then on the lower end. When I send 0 to my bulbs (all 4 of them), they dont switch off.

## Your Environment

* Version used: OpenHab 3.1

**Comment by J-N-K** [comment]
This has been discussed several times. openHAB philosophy is to use a Switch item on the brightness channel. Why do you need an additional on/off channel?

**Comment by kaikreuzer** [comment]
@batje, @J-N-K is right, but this philosophy was never clearly documented, since the hue binding was always considered the "reference as code". To improve the situation, I have created https://github.com/openhab/openhab-docs/pull/1675 and tried to explain there, [why the brightness channel is enough](https://github.com/openhab/openhab-docs/pull/1675/files#diff-4462b48fbbe0a1e2f624f446bf9bf49301d1e9a0813e47fcd5b5fdc12c7b8f1cR56-R62). I hope this helps a bit for understanding the abstraction layer of openHAB.

**Comment by wborn** [comment]
If you know what to look for and where, this info can also be derived from the item types / commands table in:

https://www.openhab.org/docs/configuration/items.html#type

But the extra docs make it more clear. 👍

**Comment by batje** [comment]
Great solution. Thank yiou.
