### ISSUE TITLE
[fsinternetradio] Frontier binding 3.1 connection error

### ISSUE THREAD

**Issue by nocodehummel** [openhab/openhab-addons#11651]
Frontier binding with a Pinell Supersound II has status OFFLINE with COMMUNICATION_ERROR. In general the communication works fine, but it looks like the connection gets lost after the radio is turned off. 

## Expected Behavior
It would be expected for the Pinell radio to stay online, also when the radio is switched off. The network setting on the radio has 'keep connected: true'.

## Current Behavior
After the radio is turned off the thing is reported OFFLINE and the following error is reported.

> java.util.concurrent.ExecutionException: java.io.EOFException: HttpConnectionOverHTTP@184cbbc::SocketChannelEndPoint@19c63e{l=/10.0.x.xyz:39304,r=/10.0.x.zyx:2244,ISHUT,fill=-,flush=-,to=3/0}{io=0/0,kio=0,kro=1}->HttpConnectionOverHTTP@184cbbc(l:/10.0.x.xyz:39304 <-> r:/10.0.x.zyx:2244,closed=false)=>HttpChannelOverHTTP@d5e1a3(exchange=HttpExchange@b49c59{req=HttpRequest[GET /fsapi/GET/netRemote.sys.power HTTP/1.1]@1966518[TERMINATED/null] res=HttpResponse[null 0 null]@1386fa2[PENDING/null]})[send=HttpSenderOverHTTP@274a9f(req=QUEUED,snd=COMPLETED,failure=null)[HttpGenerator@8b5416{s=START}],recv=HttpReceiverOverHTTP@234c7a(rsp=IDLE,failure=null)[HttpParser{s=CLOSED,0 of -1}]] 

## Steps to Reproduce (for Bugs)
1. Install Frontier binding
2. Turn-on Pinell Supersound II
2. Add thing: Pinell Supersound II (with IP and PIN).
3. Turn-off Pinell Supersound II
4. After 24 hours check thing status; OFFLINE
5. Check logs files; [ERROR] [radio.FrontierSiliconRadioConnection]

## Context
The issue occurs while including the radio in the openHAB home automation. 

## Your Environment
* Version used: openHAB 3.1
* Operating System and version: Linux openhab 5.10.17-v7l

**Comment by git-boris** [comment]
Hello nordicgit70,

I don't own a Pinell Supersound II, but stumbled upon your issue looking for other information about the fsinternetradio add-on, so I cannot check the following things by myself. But you could try them and post the results to narrow down the root cause.

You wrote that to reproduce this, you need to wait 24 hours. Does this mean before 24h the radio can be turned on by openhab again? If so, I haven't tried this with my radio yet.

The error means that the polling request to read the power status from the radio failed. To check if the radio responds to API calls, you can enter the following URL with the IP address and pin of your radio in your browser.

http://<radio-ip>/fsapi/CREATE_SESSION?pin=1234

it should return an XML structure like:
<fsapiResponse>
<status>FS_OK</status>
<sessionId>1234567890</sessionId>
</fsapiResponse>

If you don't get a response when your radio is turned off, but only when it is turned on, it means that your radio doesn't respond to API calls when turned off, regardless of the parameter "keep connected: true". My radio does still respond then, so this might be a specialty of the Pinell Supersound II.

You could also check if the UNDOK app by Frontier is able to turn the radio on. If so, this would at least indicate that it is possible to resolve this issue. I haven’t tried the app and don’t know if the radio can handle two connections at the same time, so it might be necessary to turn off openhab while trying this.
