### ISSUE TITLE
[pulseaudio] The PulseAudio binding Has Hardcoded Ports that May not Match all Setups

### ISSUE THREAD

**Issue by Dracrius** [openhab/openhab-addons#11661]
PulseAudio's "official" windows distro has seen no love in years and is many versions behind the rest of the project so another person has started maintain a stable up to date windows version as of 2021 (https://pgaskin.net/pulseaudio-win32/) but his is using port 4713 rather then 4712 if you have `module-cli-protocol-tcp` and  `module-native-protocol-tcp` loaded at the same time. Worst of all it also currently has a bug that cause it not to launch if you try to force the port with `load-module module-native-protocol-tcp port=4712`. While that bug does need to be fixed it brought to my attention the hardcoded values in the binding that do not respect the Bridge's Port settings from the Openhab UI. This means despite setting the right port setting on the bridge to 4713 my Sink thing will not connect while pulseaudio is using 4713. The bridge will connect just fine but all sinks lose connection until you disable `module-native-protocol-tcp` and there by return to using Port=4712

**Comment by Dracrius** [comment]
These are the files with the hardcoded port.
[bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/discovery/PulseaudioDiscoveryParticipant.java](https://github.com/openhab/openhab-addons/blob/bea7197ede7b6876c31a2b8f7d8cf37d50a7c2f5/bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/discovery/PulseaudioDiscoveryParticipant.java)
https://github.com/openhab/openhab-addons/blob/bea7197ede7b6876c31a2b8f7d8cf37d50a7c2f5/bundles/org.openhab.binding.pulseaudio/src/main/java/org/openhab/binding/pulseaudio/internal/handler/PulseaudioBridgeHandler.java

**Comment by Dracrius** [comment]
Solved with this pull request https://github.com/openhab/openhab-addons/pull/11631
Same cause as https://github.com/openhab/openhab-addons/issues/11630

**Comment by dalgwen** [comment]
Hello,

I tried to reproduce your issue but couldn't
What I tried : 
- on the pulseaudio server, load the cli-protocol-tcp module on port 4713, with this command : "pactl load-module module-cli-protocol-tcp port=4713" (command probably totally irrelevant as you use Windows)
- configure a pulseaudio bridge on openHAB with the port 4713
- the bridge is "connected"
- create a sink thing from the mailbox (with the autodiscovery feature, because the bridge is connected, the binding can query the pulseaudio server for sink/source information and pre-initialize some sink thing)
- activate, in the sink thing parameter, the audiosink feature.
- play a sound over the sink by an openHAB rule
---> Got a sound

About the hardcoded port you mentionned : 

- the "PulseaudioDiscoveryParticipant" file is for the autodiscovery of pulseaudio BRIDGE (i.e. to identify servers on the network and pre-initialize them without even the need of writing an IP address). It uses mdns for this (the pulseaudio server must have the zeroconf-publish module loaded to expose itself as a mdns service). As it has indeed a real bug (it should use the port from the ServiceInfo object discovered and not the 4712), it is only for confirming autodiscovery and doesn't impact the bridge, when manually configured. This bug only prevents a pulseaudio bridge with zeroconf-publish module from showing in the mailbox in case the port used for the simple-protocol-tcp module is not the default one (pretty rare case)

- the PulseaudioBridgeHandler has indeed the 4712 port default value on the object initialization. But on the line 135, when initialized, it override this value with the one taken in the parameter.

So it seems OK to me.

I suggest you double check the parameters, as it is a little bit confusing. You could maybe have mixed them ?

There is two parameters, very different : 
- the port parameter on the **BRIDGE** thing must match the parameter of the module-cli-protocol-tcp loaded on the server side (in your case, 4713)
- the port parameter on the **SINK** thing is not mandatory. Even if you load manually the module-simple-protocol-tcp (which you should not have to, except if you have other special need), the binding can found it and connect to it WITHOUT the port configuration. The port configuration serves another purposes : if the module-simple-protocol is not loaded on the pulseaudio server side, the binding ask it to load it on the port you specify. BUT it is only a preference, as the binding will try to laod the module on other ports if it failed.


I will try to make a PR to fix the hardcoded port on the mdns discovery service (but as I said, it won't help you)

**Comment by dalgwen** [comment]
Oops, in fact, I will not make a PR to fix the hardcoded port on the mdns discovery service.
I just saw a comment in the code leading me to think it is intentionnal : 
`// we do not read the port here because the given port is 4713 and we need 4712 to query the server`
It suggests that the mdns query result is misleading and the port returned is not the cli-module-tcp port and therefore is of no interest for the binding.
(I do not use this functionnality and thus could not test it)

**Comment by lsiepel** [comment]
If i understand it right, the 'hardcoded' port is not used and @Dracrius can allready configure the relevant port setting? If so can you confirm, maybe we can then close this issue? 
Or if that is not the case, what can we do to get this fixed?

**Comment by Dracrius** [comment]
> If i understand it right, the 'hardcoded' port is not used and @Dracrius can allready configure the relevant port setting? If so can you confirm, maybe we can then close this issue? Or if that is not the case, what can we do to get this fixed?

The original reply while possibly finding a reason for the inconsistency is wrong that port is used seeing as I had to change it and build my own version just to get it to work.

**Comment by lsiepel** [comment]
Can you share your change? Maybe we can make it configurable and default to the current behaviour ?
