### ISSUE TITLE
[telegram] NumberFormatException (Token/Bot-Id exceeds the range of Integer)

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#11732]
When I'm creating a bot within my Telegram client it generates tokens like "5087153354:...". When I try to send messages to it via a rule, the message is received by the Telegram client (everything looks good), but the rule execution stops and the log shows this error message: "2021-12-08 05:32:17.501 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'telegram-1' failed: java.lang.NumberFormatException: Expected an int but was 5087153354 at line 1 column 61 path $.result.from.id in telegram".

The message is true, 5087153354 exceeds the range of Integer, therefore you should use another data type within the binding.

I have 2 bots within my Telegram client. The first bot has a valid integer (start with "1"), but everytime I'm trying to create a second bot the number starts with "5" (not an valid integer with 10 digits). I hope that does only occur when someone has 2 bots within 1 Telegram client (but I'm not sure... ;-) ).

The problem occurs in OpenHAB 3.1, I don't know if it still exists in OpenHAB 3.2.

**Comment by Novanic** [comment]
The problem also occurs with just 1 bot (new device, with new telegram installation and just 1 bot).

This issue should get a high priority, because it affects all new users.

**Comment by Skinah** [comment]
Thanks for reporting this and I agree it is a high priority, I can take a look if I can reproduce it. I need to know the following ASAP as we only have days before 3.2 Stable is released...

1. How to reproduce? what steps are needed?
2. Does it happen in the latest Milestone build? If you don't want to change the core, you can download the addons in a KAR for the milestone and rename the kar to zip and open it up to get the jar for telegram.
3. Can you enable TRACE logs on this when it happens so we can see each step that happens just before and including the error message?

I have updated the library that this binding uses from 4.9.0 to 5.2.0 so if this NumberFormatException comes from a bug in the library, then there is a good chance it will be fixed in the milestones. I have taken a quick look and everything in the binding appears to not use an INT but a LONG for the chatId and String for the botID/token. My gut is saying this was a library bug that was fixed when the lib was updated months ago.

Need to confirm if it is still happening in the latest Milestone, or it will only waste peoples time.

**Comment by Skinah** [comment]
See here as this was fixed in the lib and others on the forum indicate that after updating and cleaning the cache they have it working.... https://github.com/pengrad/java-telegram-bot-api/issues/230
