### ISSUE TITLE
[transform.JSONPath] sum aggregation isn't updated

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#11756]
I'm trying to sum various values of a json received via MQTT. When the JSON path of the item is "$.intervalDatas[0].channelIntervalDatas[0].averageImportRMSActivePower", everything is working fine and it is updated every 5 minutes (a MQTT message is sent every 5 minutes).

When I try to sum all values of the array with this JSON path expression: "$.sum($.intervalDatas[*].channelIntervalDatas[*].averageImportRMSActivePower)" it seems to work at first, the correct value is set. But it is never updated. The next MQTT messages have no effect / the item is never updated.

OpenHAB 3.1 is used.

**Comment by lsiepel** [comment]
You might search some other transform related issues as the combination of transforms and mqtt are not always straight forward. Sorry not much details :-/

**Comment by lsiepel** [comment]
It's an old issue, not sure if it is still relevant, but i think you will get the best support by the community forums as many more users will look at it. I close htis for now. 
If you think there is a bug that should be fixed in code, please re-open and add more details like the actual message, item configuration etc.
