### ISSUE TITLE
[knx] add dedicated input field for status GA

### ISSUE THREAD

**Issue by svenb1234** [openhab/openhab-addons#11784]
If one wants to add a status GA to a channel one has to use the following syntax:

`1/1/20+<1/2/20`

This is not straight forward for beginners/normal users.

It would be a lot easier if there were dedicated input fields for the several GAs which belong to a channel, e.g. the status GA.

Even if the dedicated lines are not feasible, there should be at least some hint on the Main UI page regarding the syntax.

## Your Environment

* Version used: openhab 3.1
* Main UI

**Comment by udo1toni** [comment]
In fact, the syntax is similar to the syntax in ETS, the first GA is to send messages, all other GA are only to receive messages. In question of <, this is only to pull status information in startup phase, you could omit this piece.

But certainly it would be nice to have a hint about configuration in the UI. "Group address Notation" and "The Group Address(es)" is not sufficient.

**Comment by svenb1234** [comment]
I think that the Main UI also aims at ETS inside users, i.e. assist them to lower the complexity.

"Group address to send:"
"Datapoint type (optional):"
"Group address to listen to (optional):"      "Pull status at start-up" as checkbox
"+" (add GA to listen to)

**Comment by kaikreuzer** [comment]
> But certainly it would be nice to have a hint about configuration in the UI. "Group address Notation" and "The Group Address(es)" is not sufficient.

The "Group Address Notation" in the field description refers to [the KNX binding documentation](https://www.openhab.org/addons/bindings/knx/#group-address-notation).
I agree that it would be better if this was a link to the docs, but unfortunately, this is not supported by the UI afaik.
For a complex system like KNX, I am expecting the user to have a look at the docs in any case, though.

The syntax is there since openHAB 1 and it is kept backward compatible in order to ease migration. We cannot build any specific treatment for KNX in there as the UI configuration is built in a generic fashion.

I'd therefore suggest to close this issue.

**Comment by svenb1234** [comment]
I disagree since a GUI's purpose is to ease complexity. Not to just display the message: RTFM. That is why there is ETS Inside and free@home both of which ease the complexity of KNX via GUI. 

If th GUI does not allow this, then its design should be changed to not restrict assisting the user. It should allow to break down the complexity into several fields and bits of information accompanied by hints and information.

The syntax in the code can still stay the same, even if it's content is assembled from several fields.

**Comment by kaikreuzer** [comment]
In that case I suggest you open an issue for the UI then. But I doubt that any KNX-specific stuff will be implemented there, since otherwise 300 other bindings might ask for the same and the code base will instantly be a mess and not maintainable anymore...
