### ISSUE TITLE
[digitalstrom] Power Consumption and Energy Level NULL after DSS Update to 1.19.2

### ISSUE THREAD

**Issue by alaub81** [openhab/openhab-addons#11847]
Digitalstrom did an Update to dss Version 1.19.2. After I installed the update, all my power and energy values get no updates and if I add a new Item, the value is NULL.

It seems, that digitalstrom changed something here, so we do not get values anymore.

In the [Release notes](https://www.digitalstrom.com/wp-content/uploads/2021/12/SRN-2112_v1.1_EN.pdf) is written, that they improved something with the energy graphics. 

I am using the openhab 3.2.0 docker image. Problem was in 3.1.1, too. I restarted the dss and also openhab was restarted a couple of times.

For me it seems that we have a new bug here.

To reproduce that Bug, you have to update the digitalstrom server to version 1.19.2. After that you will not see any item value updates on your power consumptions or energy levels. So it just keeps at 0. Interesting is, that the totalpowerconsumption, which belongs to the digitalstrom server thing, is still working.

I am using a Debian 10 Installation on a Raspberry Pi 4 with openhab docker image in version 3.2.0. The Digitalstrom Server is a dss20 with distroVersion 1.19.2

**Comment by ardanedh** [comment]
I can confirm the problem. A quick glance at the JSON results for getting meter values does not show any changes in the API.

If time allows, I'll try to dig into the digitalSTROM code. Meter values are not a high priority in my openHAB environment, though ;)

**Comment by ardanedh** [comment]
With digitalSTROM Server version _1.19.2_, the JSON request (`/json/metering/getLatest`) to retrieve the meter values returns a `dSUID` instead of a `dsid`:
```json
{
    "result": {
        "values": [
            {
                "dSUID": "303505d7f8000000000002c00000323c00",
                "value": 124.0,
                "date": "2022-01-04 20:46:02"
            }
        ]
    },
    "ok": true
}
```

The binding fails at this point to handle the meter values due to the missing `dsid`
I don't know if this is a bug in the new digitalSTROM server version or if this is by intent.
The latest [digitalSTROM-Server JSON](https://developer.digitalstrom.org/Architecture/dss-json.pdf) API clearly indicates the returned value should be a `dsid`.

Unfortunately, getting in contact with digitalSTROM is somewhat difficult, they seem to communicate mainly via Facebook (a service I don't use). I'm uncertain at the moment on what is the best solution to this problem ...

**Comment by alaub81** [comment]
last time I had problems with digitalStrom I used the mail address support@digitalstrom.com . I know it took some time, but I had a good contact there with one of the product owner. I have the name, but I do not know if I am allowed to write here.

But he owns a blog [https://ds-tools.net/blog/](https://ds-tools.net/blog/)

Perhaps you could contact him. I think they changed the API and forgot to document it.

**Comment by ardanedh** [comment]
> But he owns a blog https://ds-tools.net/blog/

Unfortunately, the mentioned product owner is no longer working for digitalSTROM ...

**Comment by ardanedh** [comment]
I've now seen the issue mentioned on the digitalSTROM facebook page as well, with no statement from digitalSTROM so far.
Other developers (german forum [symcon](https://community.symcon.de/t/update-19-2-und-metering-verschwunden/127354)) are discussing the problem as well.
I still hope digitalSTROM releases a bugfix for the dSS, before changing any binding code ...

**Comment by alexf2015** [comment]
I can also confirm that the bug occours on my side since I updated digitalstrom server to 1.19.2.
Unfortunately that release is announced as final stabilization release for dss11 series which means there are no plans to provide further updates. Hopefully they will fix the bug introduced with 1.19.2.

**Comment by alexf2015** [comment]
I checked API docs and I believe the change in general is intentional. Maybe it was a mistake that it was applied now or maybe the API documentation was not updated properly. 
But if you have a look at "/json/metering/getAggregatedLatest" you will see that the response should contain both dsuid and dsid while dsid is deprecated. I guess there are plans to remove dsid in general.

**Comment by alexf2015** [comment]
Feedback from digitalstrom support:

> I will discuss this issue with my collegues of our developement and will inform you.
> Best regards,
> Muharrem Kaya

and second reply

> is it possible for you to use "dsuid" (instead of "dsid")?
> Best regards,
> Muharrem Kaya

So it looks like they do not want to revert that change.

**Comment by ardanedh** [comment]
> So it looks like they do not want to revert that change.

The dSS software version 1.19.2 has been announced as the `End of life stabilization release for dSS11-1GB, dSS11-E, dSS IP` ... a bold move breaking such a fundamental part with the _last_ release and not being willing to fix it ...

Thanks for getting in contact with digitalSTROM, though!

**Comment by alexf2015** [comment]
I am also not happy as I own a `dSS11-1GB` device and I do not want to replace it. Unfortunately I could happen that the API will be changed in future releases in a way that makes it hard to keep the binding backwards compatible.

**Comment by ardanedh** [comment]
Interesting development in the digitalSTROM server releases. digitalSTROM removed the release 1.19.2 from their download section and recommends version 1.19.1:

*Since 1.19.2 introduced an issue with setting the dimming in 300 series it is not available for now.* (statement found on faceb@#¼).

I'm genuinely curious if they fix the dSUID/dsid mishap as well.

**Comment by alaub81** [comment]
hopefully not. I installed today openHAB version 3.3.0.M1 with the fix and everything is working fine since a few hours 🙂

Thanks for fixing it!
