### ISSUE TITLE
[homekit] homekitMultiplicator doesn’t seem to work in HumiditySensor

### ISSUE THREAD

**Issue by chayter** [openhab/openhab-addons#11919]
It doesn’t seem that the code is referencing the configuration value and is hard coded to 1.0.

**Comment by lsiepel** [comment]
@chayter this issue was raised two years ago and some PR's have been made. Could you verify this is still hapenning at 4.1? and could you link to the code so it would be easier to see what you mean and what is going on?

**Comment by ccutrer** [comment]
[The code definitely is referencing the config value](https://github.com/openhab/openhab-addons/blob/9362fcccdcd9a2447d5271d1c0f913b9f03c9933/bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHumiditySensorImpl.java#L55). Perhaps you've placed the config on the RelativeHumidity characteristic's item in a complex accessory, rather than on the Group item?

**Comment by lsiepel** [comment]
Closed, no follow up by issue reporter.

**Comment by ronnyandersson** [comment]
> [The code definitely is referencing the config value](https://github.com/openhab/openhab-addons/blob/9362fcccdcd9a2447d5271d1c0f913b9f03c9933/bundles/org.openhab.io.homekit/src/main/java/org/openhab/io/homekit/internal/accessories/HomekitHumiditySensorImpl.java#L55). Perhaps you've placed the config on the RelativeHumidity characteristic's item in a complex accessory, rather than on the Group item?

@ccutrer I cannot find that as an example in the documentation, but I had this exact issue. On a simple item then `homekit="HumiditySensor" [homekitMultiplicator = 100]` works fine, but in a complex accessory group item the homekitMultiplicator must be placed in the group instead. Then it works as expected: `homekit="TemperatureSensor,HumiditySensor,Battery" [homekitMultiplicator = 100]` So this is rather undocumented, but works great.
