### ISSUE TITLE
[meater] New binding for meater probes

### ISSUE THREAD

**Issue by jannegpriv** [openhab/openhab-addons#11998]
[meater] My feature request for creating a binding to support the Meater probes offered by https://meater.com/.

Public API available on:
https://github.com/apption-labs/meater-cloud-public-rest-api

I will start to create a binding for it.

**Comment by Novanic** [comment]
Hi,

I have also developed a binding for it. It's working, but I decided to not continue it, because the usage is just not hugh enough. I requested a few API enhancements at the meater team, which could increase the usage of the binding, but unfortunately it seem not to have a high priority for the meater team:
- [Support for accessing the cook visualization](https://github.com/apption-labs/meater-cloud-public-rest-api/issues/9)
- [Transfer devices even when they aren't active](https://github.com/apption-labs/meater-cloud-public-rest-api/issues/7)
- [Support for connection quality](https://github.com/apption-labs/meater-cloud-public-rest-api/issues/6)
- [Support for battery level](https://github.com/apption-labs/meater-cloud-public-rest-api/issues/5)

But you could use the code and continue it if you want: https://github.com/Novanic/openhab-addons/tree/meater-3

**Comment by jannegpriv** [comment]
Hi!

I'm initially doing this on a request from a collegue at work but then I also grabbed a Meater+ probe and then it was doable for me to implement it.

I will have a look at your code for sure!

Here is my branch atm, I will continue to dev/test today:
https://github.com/jannegpriv/openhab-addons/tree/11998-meater
