### ISSUE TITLE
[hdpowerview] Fix SAT missing null annotation warnings

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#12027]
Unfortunately #11944 and #11980 introduced four unnoticed SAT warnings:

```
[WARNING] Code Analysis Tool has found: 
 0 error(s)!
 4 warning(s)
 0 info(s)
[WARNING] org.openhab.binding.hdpowerview.internal.api.Firmware.java:[20]
Classes/Interfaces/Enums should be annotated with @NonNullByDefault
[WARNING] org.openhab.binding.hdpowerview.internal.api.responses.FirmwareVersion.java:[20]
Classes/Interfaces/Enums should be annotated with @NonNullByDefault
[WARNING] org.openhab.binding.hdpowerview.internal.api.responses.FirmwareVersions.java:[22]
Classes/Interfaces/Enums should be annotated with @NonNullByDefault
[WARNING] org.openhab.binding.hdpowerview.internal.api.responses.Survey.java:[25]
Classes/Interfaces/Enums should be annotated with @NonNullByDefault
```

The reason for omitting `@NonNullByDefault` was to avoid annotating all member variables with `@Nullable` since the classes are only used for JSON deserialization.

Ideally the null annotation could be used to define the contract (instead of working against us), so this class:

```
public class FirmwareVersions {
    public Firmware mainProcessor;
    public Firmware radio;
}
```

could be changed to:
```
@NonNullByDefault
public class FirmwareVersions {
    public Firmware mainProcessor;
    @Nullable
    public Firmware radio;
}
```

to indicate that **mainProcessor** should always be set, and otherwise `JsonParseException` should be thrown. Unfortunately this is not possible, since object is constructed with default constructor, leaving all member variables as null.

See these comments:
- https://github.com/openhab/openhab-addons/pull/12002#issuecomment-1009368319
- https://github.com/openhab/openhab-addons/pull/12002#issuecomment-1009989135

**Comment by andrewfg** [comment]
> object is constructed with default constructor, leaving all member variables as null.

Indeed. So I think the best solution is to declare all (non primitive) fields as @Nullable, and then do a “contract” test at higher level to check if the field is null, and if so raise a JsonParseException at the higher level. Note: that primitive fields like int/Boolean will be initialised as 0/false even if the contract fails; so it is probably better to declare the fields as @Nullable Integer/Boolean, so you can actually do the null check at the higher level.

Note that the class needs to be declared as@NonNullByDefault so that the compiler will be forced to do null checks, and warn of potential NPE’s..
