### ISSUE TITLE
[mqtt] add a correct LWT mechanism

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab-addons#12104]
As stated in https://community.openhab.org/t/openhab-sending-out-its-lwt/132313/5 there is a missing feature when it comes to LWT for openHAB itself.

The addon should provide full LWT functionality, this is:

- If openHAB connection to the broker is lost, send a message -> this part is working as expected
- If openHAB is shut down properly, send a message before closing connection -> seems not to work
- If openHAB is started send another message -> not implemented yet, one has to do it manually via rules.

**Comment by Rossko57** [comment]
To add a little more flesh on the bones -

Binding correctly pre-sets LWT message upon subscribing to broker.  Users may conveniently set `lwtRetain=true` so that late subscribers can discover a previous failure event.
Problem is that setting a LWT message with the broker does not automatically clear any old retained LWT disaster message, i.e. it looks "offline" forever.

Suggestion - binding to auto-publish a **birth** message to an arbitrary topic, after each successful broker connection.  This would be properties on the broker Thing, like `birthMessage="online", birthTopic="openhab/lwt", birthRetain=true`.
This would have general announcement capability, but conveniently allows users to choose to publish to same topic as LWT and override old disaster.

A completely separate issue is that, by design, brokers do not publish LWT in the event of orderly disconnect, only error cases.
Many remote subscribers to MQTT LWT will not care if openHAB has gone offline by accident or intent, but are not notified of orderly shutdown.

Suggestion, add an action to broker Thing closedown process (which already includes voluntary unsubscribes) to publish a shutdown message.  Like the birth message, this can be arbitrary, but users may choose LWT topic for convenience.
`shutdownMessage="offline", shutdownTopic="openhab/lwt", shutdownRetain=true`.

A refinement would be for shutdown topic/retain to default to same as birth.

**Comment by jimtng** [comment]
@Rossko57 I've started implementing it and I was about to submit my PR. However I was thinking, would we need to specify shutdownMessage separately? It is basically the same as lwt so why not just omit that and publish the lwtTopic/lwtMessage?
