### ISSUE TITLE
[jdbc] timescaleDB/postgreSQL not timestamping in UTC?

### ISSUE THREAD

**Issue by Alpoy** [openhab/openhab-addons#12315]
## Expected Behavior
Timestamps should be equally stored in different db's?

## Current Behavior
I'm having some trouble figuring out this one, I'm comparing the same persisted-item in Grafana in 2 different DB sources, influxDB and timescaleDB/postgreSQL, but the latter is always ahead by 1 hour.
I've tried figuring out whats going on in this post on the forums but I don't know what more to do:
https://community.openhab.org/t/jdbc-timescaledb-postgresql-timestamps-not-utc-bug/133394

I might be way off here but could this be a bug where timestamps stored in postgresql are stored "with" the timezone offset, not UTC? Influxdb uses unixtime so it should be UTC.

## Steps to Reproduce (for Bugs)
Here's a visualization of the problem (all data from the timescaleDB/postgreSQL is ahead 1 hour, influxDB source is correct):
![image](https://user-images.githubusercontent.com/11949996/154705136-7a03bf12-ba34-4195-a6f7-62970a894ddf.png)

## Your Environment
Raspbian 11 - postgresSQL 13, TimescaleDB 2.5.2 and InfluxDB 1.8.10-1
Openhab 3.2 (stable)

**Comment by henfiber** [comment]
This should be now fixed with: https://github.com/openhab/openhab-addons/pull/14294. After the PR is accepted the issue could be closed.

At least for:

- newly ingested data in new items (which create new tables with the more appropriate TIMESTAMPTZ type) or 
- newly ingested data in existing items after being converted to TIMESTAMPTZ with `jdbc schema fix` (backup first and make sure time zone is set correctly before running the command).
