### ISSUE TITLE
[tr064] Support for fiber devices

### ISSUE THREAD

**Issue by Novanic** [openhab/openhab-addons#12362]
I switched from a FritzBox 7590 (DSL) to a FritzBox 5530 (fiber) and would like to get the current connection speed (downstream and upstream) again.

I configured the channels "dslDownstreamCurrRate" and "dslUpstreamCurrRate" like before, but this doesn't work. These warnings are logged every second:
2022-02-23 21:00:13.366 [WARN ] [ng.tr064.internal.soap.SOAPConnector] - Failed to get Tr064ChannelConfig{channelType=dslDownstreamCurrRate, getAction=GetInfo, dataType='ui4, parameter='null'}: HTTP-Response-Code 500 (Internal Server Error), SOAP-Fault: 820 (Internal Error)
2022-02-23 21:00:13.465 [WARN ] [ng.tr064.internal.soap.SOAPConnector] - Failed to get Tr064ChannelConfig{channelType=dslUpstreamCurrRate, getAction=GetInfo, dataType='i4, parameter='null'}: HTTP-Response-Code 500 (Internal Server Error), SOAP-Fault: 820 (Internal Error)

So it seems this information is only available for DSL devices but not for fiber (glass fiber / optical fiber) devices and I don't see alternative channels within the binding which could provide the current connection speed. Could you please enhance the binding to support at least this information for fiber devices?

**Comment by Novanic** [comment]
@lolodomo or @wborn There are a few issues regarding the TR-064 binding (with tags [tr064] and [tr-064]) which aren't assigned to a project or maintainer. Therefore nobody seems to work or comment on this issue. Is there still a maintainer for the binding and can you assign these issues?

**Comment by wborn** [comment]
Based on the [Git history](https://github.com/openhab/openhab-addons/commits/main/bundles/org.openhab.binding.tr064) and [CODEOWNERS](https://github.com/openhab/openhab-addons/blob/main/CODEOWNERS) this add-on currently has no maintainer. Maybe @kaikreuzer can add you to the [contributors team](https://github.com/orgs/openhab/teams/contributors) because you are also the livisismarthome add-on maintainer? After that you can self assign yourself to any issue you want to work on and you'll also automatically get review requests for livisismarthome PRs.

**Comment by lsiepel** [comment]
Is this issue related to https://github.com/openhab/openhab-addons/issues/10287 and/or https://github.com/openhab/openhab-addons/issues/10919 
They all look very similar
