### ISSUE TITLE
[iCalendar] Binding does not support IP addresses or 'localhost' in URL

### ISSUE THREAD

**Issue by Sascha-L** [openhab/openhab-addons#12476]
When using an IP address or 'localhost' in Source URL, downloading the ICS file fails:

2022-03-15 04:00:30.730 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar failed with ExecutionException: No subject alternative DNS name matching localhost found.

2022-03-15 09:00:15.842 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar failed with ExecutionException: No subject alternative names matching IP address 127.0.0.1 found

So it is not possible to use e.g.:

https://127.0.0.1/mycalendar.ics

or:

https://localhost/mycalendar.ics

**Comment by clinique** [comment]
I just made the test, and it seems to work fine on my side. Except that I did test on http://127.0.0.1/mycalendar.ics (or localhost).
Are you sur you've got a proper certificate to handle https ?

**Comment by Sascha-L** [comment]
My Let's Encrypt SSL certificate is created for my dyndns domain, so of course while using localhost / 127.0.0.1 it may throw certificate erros, but they should not matter in this case. When I enter the URL https://localhost/mycalendar.ics  or https://127.0.0.1/mycalendar.ics in Chrome or Edge it directly downloads the file without any complaints about the SSL certificate.

So if it is only a SSL issue, it would be nice to have an option to ignore SSL certificate erros or always ignore them e.g. if localhost is used.

Or is it possible to enter an absolute or relative file path (on Windows, e.g.) to the ics file which is stored on the same machine where openHAB is running?

**Comment by andrewfg** [comment]
Are you running a separate file server on 127.0.0.1 / local host? Excuse me if I am stating the obvious, but the OpenHAB web server itself is running on that address, so you might need to configure your file server to not clash with the OH web server…

**Comment by Sascha-L** [comment]
Yes, I'm running XAMPP, so localhost or 127.0.0.1 returns openHAB Web UI,  but e.g. localhost/mycalendar.ics will return the file from htdocs dir.

**Comment by daMihe** [comment]
This is a non-issue of iCalendar. Your problem is in that case you are using a certificate for your calendar source that is not matching the host name of the URL. Either replace the certificate to one that matches the hostname, or change the URL to your dyndns-name, or set up a virtualhost which a different certificate. If security is really not required and you have issues using https, please use http.

I won't implement an "ignore SSL errors" setting, as people tend to ignore problems and are then wondering when other things don't work or they getting "hacked" or whatever. That is a behavior i don't support, sorry.
