### ISSUE TITLE
org.openhab.binding.hue support Sensor API (e.g. for Hue Dimmer)

### ISSUE THREAD

**Issue by regnets** [openhab/openhab-addons#1260]
I purchased a Philips Hue Dimmer (http://www2.meethue.com/de-de/productdetail/philips-hue-dimmer-switch) and this thing is not supported ootb from the hue binding as far as i can tell.

However the Philips API provides an interface for accessing those devices
http://www.developers.meethue.com/documentation/sensors-api

Support for these devices would be great! However we will need a faster polling period for the sensors, as the API is still not providing any form of callback or external events.
##

**Comment by kaikreuzer** [comment]
Yes, I agree it would be nice to add this functionality. I find it pretty weird though that there is still no event subscription possible. Polling the bridge definitely means no satisfying user experience, since it will always mean quite some latency even if the polling frequency is increased.

**Comment by ddudnik** [comment]
Hi @kaikreuzer 

With the appearance of Hue motion detector the support for Sensor API makes even more sense now. Even if implemented with polling. I guess it should work more or less fine from UX perspective for this new Hue motion detector which is in fact a multi-sensor providing: motion sensor, daylight sensor and (unadvertised) temperature sensor.

Since I got myself one of those, I would be up for the task :)

However, first I would like to ask about the library (Jue) used to talk to Hue bridge API. It is no secret that it is unsupported for quite some time and therefore unable to catch up with new features. What do you think about migrating Hue binding to a new library underneath? (or maybe creating a new version of hue binding with a new library leaving the existing binding untouched).  And a follow up question: what is the policy of using libraries which do not have their source open? (thinking official Philips Hue Java SDK which is free for use but does not open its source)

Thank you!

**Comment by kaikreuzer** [comment]
> Since I got myself one of those, I would be up for the task :)

Sounds promising :-)

First of all, I would suggest to open an issue and discussion at https://github.com/eclipse/smarthome/issues, because this is where the hue binding code is located.

> What do you think about migrating Hue binding to a new library underneath?

Well, the question is whether there IS any actively maintained library (besides the SDK from Philips). If not, we could enhance the Jue library on our own for what we need (we already did so in the past). As there is a single author, I could also think of asking him to allow us to take the code and make the sources directly a part of the binding. We would then simply do the HTTP requests on our own, which isn't too hard and leaves us most flexibility.

> And a follow up question: what is the policy of using libraries which do not have their source open? (thinking official Philips Hue Java SDK which is free for use but does not open its source)

It actually appears [here](https://github.com/PhilipsHue/PhilipsHueSDK-Java-MultiPlatform-Android) as if Philips offers it under a new BSD license - but you are right, in this repo, there are only binaries and the source code are merely example apps :-/ Also statements like "the hue SDK and API can only be used for hue and for no other application or product" are pretty incompatible with any OSI license. For Eclipse projects, having sources available is a must. See [here for the general policy](https://www.eclipse.org/legal/eplfaq.php#OSICOMPLIANT). What Philips does is a bit fuzzy and I guess it would require quite some discussions to have the license terms sorted out with them.

**Comment by regnets** [comment]
@ddudnik I am following this issue for quite some time now. If you need a Philips Hue Dimmer i would gladly purchase one for you if this helps you to develop/test the binding.

@kaikreuzer Does it make sense to just add features to the Philips Hue Binding? If I'm not mistaken, there were some effort to create a binding for all zigbee lighting products. However i can't find an issue in the openhab2 repo nor in the esh repo concerning this topic.

**Comment by ddudnik** [comment]
@kaikreuzer 
I opened a new issue in eclispe/smarthome repo regarding the library: https://github.com/eclipse/smarthome/issues/2601. I guess we could create another separate issue for the Sensor API support to keep things clear. Do you know if it's somehow possible to "transfer" this issue to eclipse/smarthome? (or we could just copy-paste)

@regnets Thank you for your offer! I do have the Hue Dimmer myself so I don't need another one.

**Comment by kaikreuzer** [comment]
> Do you know if it's somehow possible to "transfer" this issue to eclipse/smarthome?

No, you have to create a new one.

**Comment by ddudnik** [comment]
@kaikreuzer @regnets I've created a new issue about Sensor API support in eclipse/smarthome: https://github.com/eclipse/smarthome/issues/2603. I guess this one can be closed.
