### ISSUE TITLE
Simplify way of loading libraries in scripting addons

### ISSUE THREAD

**Issue by NCC1701M** [openhab/openhab-addons#12662]
As described in this [article](https://community.openhab.org/t/oh-3-examples-writing-and-using-javascript-libraries-in-mainui-created-rules/108526) the way of loading a library is

```javascript
this.OPENHAB_CONF = (this.OPENHAB_CONF === undefined) ? java.lang.System.getProperty("openhab.conf") : this.OPENHAB_CONF;
load(OPENHAB_CONF + "/automation/lib/javascript/personal/utils.js")
```

The way a library is loaded could be simplified if the `load` function would handle relative paths.

For example:

If the load function is called like this
```javascript
load("automation/lib/javascript/personal/utils.js");
```

the function could detect that a relative path was provided (on linux because of the missing / at the beginning of the string) and automatically prepend the `OPENHAB_CONF` path.

Otherwise if the function is called with an absolute path 
```javascript
load("/somewhere/on/the/filesystem/automation/lib/javascript/personal/utils.js");
```

it would not prepend the `OPENHAB_CONF`. 

This would make loading libraries a little easier and would lead to better code because DRY (Don't Repeat Yourself).

**Comment by J-N-K** [comment]
@rkoshak This requires at least writing a wrapper for the script engine. Since Nashorn was removed in Java 15, it'll not be available in core once we switch to Java 17 there. @wborn has created an add-on for supporting ECMA Script 5.1 (which is currently available from the marketplace). It makes much more sense to integrate it there instead of writing code which will be obsolete in the near future (especially with respect to limited core development capacities).

**Comment by rkoshak** [comment]
I completely agree so it makes more sense to me to open an issue on @wborn's repo which has the Nashorn add-on and close this issue here since it doesn't actually apply to any code hosted in this repo.

Or, were it me, I'd close it as "won't fix" given that Nashorn is on the chopping block and based on the marketplace entry, that add-on is mainly there to provide legacy support. I don't think there is an intention to continue development on Nashorn, or am I wrong?

**Comment by lsiepel** [comment]
See previous post. Raising an issue at wborn’s repo might be best. I would also not expect much development on this due to it being replaced.

**Comment by wborn** [comment]
> Raising an issue at wborn’s repo might be best.

That's this repo because I contributed the code in https://github.com/openhab/openhab-addons/pull/14013.
