### ISSUE TITLE
[Velbus] Button Modules with multiple adressess not fully working

### ISSUE THREAD

**Issue by JornHermans** [openhab/openhab-addons#12702]
Buttonmodules or Glasmodules like an VMBGPOD, VMBELO have issues on higher channel numbers then 8 i think this has to do with the multiple addresses assigned to it.

## Expected Behavior
When we press button ch 1 to 8 we get a trigger event in openhab
When we press button ch 9 to 32 we also get a trigger event in openhab

## Current Behavior
When we press button ch 1 to 8 we get a trigger event in openhab
When we press button ch 9 to 32 we don't get a trigger event in openhab

## Possible Solution
While experimenting with it i did find that when i added multiple oleds manualy so lets say when an oled had adress 14, 15, 16, ...
I added a thing for each address when i did this i did get a trigger on that address and channel 1 till 8.
Buth this is not a solution!

## Steps to Reproduce (for Bugs)
1. add an vmbelo or oled with the binding
2. Monitor in the karaf console with log:tail
3. trigger a button with the channel number above 8 in either velbus link or by physical touch

## Your Environment
* Version used: 3.2.0 Stable
* Environment name and version: Node.js 14.19.2 - Snapd: Velbus-TCP
* Operating System and version : Debian (latest)

Reffering to user i think are creating the binding @Rosen01  , thnx already for the great effort on this binding!

**Comment by Rosen01** [comment]
Hi @JornHermans ,

I'm not the author of the binding, @cedricboon is the author. 
I'm only add some features or fix some bugs when I've time. 

There is a problem when you add manualy a thing (module) with sub addresses. 
I havn't found the cause yet, and unfortunately I don't have time for the moment to find a solution. 

The best way to add a module is to scan the bus (velbus) and add the module you want.

Best regards,

Daniel

**Comment by nagisa** [comment]
Having read the relevant code, it seems that there's roughly a good amount of plumbing in the binding for subaddresses (the addresses other than the primary one) – it is just that the only way to have those subaddresses set seems to be to add the module(s) over autodiscovery. Otherwise the `subaddress{1..}` property is not exposed to either the `.things` configuration or to the UI.

One detail I’m failing to understand, though, is how OpenHAB manages to read out the temperature sensor from the VMBELO module (the sensor is at the CH33, which should be the 5th address of the module…) as I haven’t found the code that would somehow assign sequential subaddresses.
