### ISSUE TITLE
homekit: thermostat modes limiting

### ISSUE THREAD

**Issue by JacekKac** [openhab/openhab-addons#12760]
is there a way to getrid of cooling mode in thermostat? if i put this into metadata the 4th cooling mode still exist in home app

metadata: {homekit: {value : 'Thermostat', config: {HEAT: 'heat', OFF: 'off', AUTO: 'auto'}}
@yfre  :)

**Comment by yfre** [comment]
@JacekKac it should actually delete the "cool" mode. i have the same setup here - cooling is not that common in Germany. 
probably for some reason homekit binding has not detected changes... try to some other changes, e.g. rename it or so. 

and let me know how you did the change (probably REST) so that i can to catch this changes as well

**Comment by JacekKac** [comment]
i move the config tags to TargetHeatingCoolingMode item. 

items.replaceItem({type: 'String', name: 'RadiatorACx_homekit_TargetHeatingCoolingMode', label: 'Termostat x Target Mode', tags: ['Roomx'], category: '', groups: ['gRoomx_termostat'], metadata: {homekit: {value: 'TargetHeatingCoolingMode', config: {HEAT: 'heat', OFF: 'off', AUTO: 'auto'}}}});
no the behaviour is: 
1/ ios shows coolling in the dropdown
2/ openhab is not reporting a item received command "cool*"
3/ auto,off,heat are working as expected

**Comment by JacekKac** [comment]
it's working ok when i move the tags to mode item instead of group. Items are created using openhab-js addon.
