### ISSUE TITLE
[netatmo] Feature area setting inconsistency ?

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#12770]
Here are my binding configuration:
![image](https://user-images.githubusercontent.com/10186704/169536532-cd53f585-1641-4620-896a-3d133e31adf8.png)

As you can see, only "Weather" is selected as feature area and not "Security". This is the default value.

With this current setting, the binding is correctly operating my Welcome camera.

So is this binding setting really of any interest ?

@clinique  : WDYT ?

**Comment by lolodomo** [comment]
This setting is used during authentication. 
@clinique : can you please explain?

**Comment by clinique** [comment]
In earlier versions of the binding, I used to request all available scopes and it worked fine.
I think I introduced it thinking : 
1. this was maybe a bad practice, 
2. to restrict discovery perimeter, 

But since now discovery perimeter heavily relies on getHomeData, that does not require any scope this usage has gone.
Maybe for simplicity sake, we could get back to requesting all available scopes.

**Comment by lolodomo** [comment]
The problem I see is that even if you use only WEATHER as scope (the default), you got access to non weather stuff. So it is not consistency IMHO.

**Comment by clinique** [comment]
Ok, I'm going to submit you a PR without it.

**Comment by lolodomo** [comment]
Did you check if energy stuff is working when only weather scope is selected?

**Comment by clinique** [comment]
Yes it works :-/
