### ISSUE TITLE
[netatmo] Channel type netatmo:temp-measurement is build twice

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#13015]
@clinique : I believe there is a small problem, you are building the channel type "netatmo:temp-measurement" twice, one for MeasureClass.INSIDE_TEMPERATURE and one for MeasureClass.OUTSIDE_TEMPERATURE. The difference between each of them is the min/max in state description.

As a consequence, the channel provider (NetatmoChannelTypeProvider) will provide only one of both for this UID, the first it finds.

I think this is necessary to have both with a different UID.

**Comment by lolodomo** [comment]
To minimize the breaking changes that such a fix will imply, I suggest to change only MeasureClass.OUTSIDE_TEMPERATURE, meaning only the outside module will be potentially impacted.

**Comment by clinique** [comment]
You're correct. Strictly said I just have used the enum name instead of the apiDescriptor to build the channel type ID. It would be the cleaner but it would break Inside Temp, Outside Temp, Rain Quantity and Humidity (preserving Pressure, CO2, Noise). Not the best choice now that 3.3 is out.

The other option would be to switch Inside Temp and Outside Temp, so the first that comes has the wider measurement range.

**Comment by clinique** [comment]
Thinking of it twice, it is built twice but stored only once as it is in a Map. As Outside Temp comes in second, it is the one that is kept. Not very nice, but should work fine and prevent any bug.

**Comment by lolodomo** [comment]
Does it mean @clinique we change nothing and close this issue ?

**Comment by clinique** [comment]
I'm not sure it is worth the pain to change anything here.
