### ISSUE TITLE
[Mail] Problem: SendHtml generates big margins/ padding, especially on mobile

### ISSUE THREAD

**Issue by maxheartrate** [openhab/openhab-addons#13032]
## Expected Behavior
Hi, I am trying to build a nice looking weekly e-mail report from OpenHAB with consumption values etc. for the past week. I used the HTML mail generator from befree.io. When I send a preview mail from beefree.io  or display the final code as an HTML page, everything looks fine. However, when I use the mail action sendhtml I get huge margins, especially when I view the e-mail on my mobile.
When I transfer the HTML file to my OpenHAB rule, I insert escapes before every " and '.

## Current Behavior
I described the issue here, with screnshots and my OpenHAB rule for sending the report:
https://community.openhab.org/t/problem-big-margins-padding-in-html-e-mails-from-sendhtml-action/136943

## Possible Solution
I tried to remove tags and styles which refer to padding or height to change the behaviour. However, this did not change the result.

## Context
I guess this might not be a bug but probably some kind of mistake I do when I transfer my HTML code to the rule. It would be great to find information on how to proceed in order to reach the correct behaviour. Thank you.

## Your Environment
OpenHAB 3.2 on OpenHABian, Raspberry 4

**Comment by lsiepel** [comment]
This does not seem to be an issue that can be fixed with a PR, but something that is discusses within the community forums. I checked the thread and it seems several options are given. Confirmation if those worked seem to be missing. Anyway, closing this issue here. Feel free to open when you can't get a solution within the community forums.
