### ISSUE TITLE
[gardena] Error 429 Limit Exceeded

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#13137]
The gardena account Thing sometimes goes permanently OFFLINE with the message "Error 429 Limit Exceeded".

Disabling/enabling resolves the situation.

_Expected behavior:_

The binding itself should be able to automatically do this by itself without requiring a user intervention.

**Comment by andrewfg** [comment]
I think there are actually two issues..
1. From time to time the server becomes unreachable, and the binding teues and fails to reconnect.
2. And, if the bunding attempts to reconnect yet fails too many times, the error morphs to "limit exceded"

**Comment by jlaur** [comment]
Some context - not to the root cause, but to the behavior of seemingly not recovering after limit has been exceeded:
https://github.com/openhab/openhab-addons/blob/c729b82d59473f1fac871a5b18bda35f697fcc7a/bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/handler/GardenaAccountHandler.java#L102-L108

I don't know if it will, but it seems like it might possibly recover from this after 24 hours.
