### ISSUE TITLE
SetUp will be not restored in jdbc.cfg

### ISSUE THREAD

**Issue by SKLD-OH3** [openhab/openhab-addons#13162]
OH 3.3.0 on RasPi 4

SetUp of JDBC Persistance will be not stored in jdbc.conf. After restart the Raspi all datas on default value.

After modification in jdbc.conf the restart is working.

**Comment by wborn** [comment]
If you configure the add-on using the UI the config will be stored in `userdata/config/org/openhab/jdbc.config`. By design any file based config in `conf/services/jdbc.conf` overrides UI made config upon restarts. So keep everything commented in `conf/services/jdbc.conf` file if you want to configure it using the UI.
