### ISSUE TITLE
[Daikin] new wifi adaptor

### ISSUE THREAD

**Issue by rdsivd** [openhab/openhab-addons#13234]
Hello
The are instaling a heatpump for my  exisiting cv-installation and there will be a wifi adaptor installed type : BRP069A78
this is new type adaptor, is this  useable with the daikin binding ?
i cant find any info in the forum

regards

Ronny

**Comment by lsiepel** [comment]
Did you manage to get it connected with openHAB?

**Comment by rdsivd** [comment]
until now i cant connect to it

**Comment by ripenko** [comment]
I have the same issue. I could connect it to cloud. But I need it in openHAB. 
I have Daikin Altherma 3 EHSX08P50EF

**Comment by jimtng** [comment]
- Find out the ip address of the adapter
- Try entering this in the binding config
- Open your browser window and type `http://IPADDRESS/aircon/get_control_info` - does it show you anything?

If it works, please report back so we can add the adapter model to the list. If it doesn't work, unfortunately that means it isn't supported. 

If the browser window test above gives you some output, report back with the output and we can try to add support to it, otherwise it will never be added without your help.
