### ISSUE TITLE
[deconz] Sensors may appear Offline after been Unreachable and becoming Reachable again. Comes Online after disable/enable

### ISSUE THREAD

**Issue by olemr** [openhab/openhab-addons#13368]
## Expected Behavior

I would expect the sensor Item to appear Online after "reachable": true & "lastupdated": "2022-09-09T18:52:36.769" becomes current.

## Current Behavior
After my Fyrtur battery sensor was unreachable and became reachable again, OH 3.3.0 release still shows it as Offline: (browser refresh does not help.)
Note that everything is working Ok, it's just that the Thing is flagged as Offline in the Things view:
![image](https://user-images.githubusercontent.com/28068256/189479100-a447c6b3-6743-42d9-8ea7-e66172f0bef3.png)

```
{
  "config": {
    "on": true,
    "reachable": true
  },
  "ep": 1,
  "etag": "f9968364c4ecac629519e0b7b1a1ad98",
  "lastannounced": "2022-09-09T18:54:28Z",
  "lastseen": "2022-09-09T18:54Z",
  "manufacturername": "IKEA of Sweden",
  "modelid": "FYRTUR block-out roller blind",
  "name": "FYRTUR block-out roller blind ",
  "state": {
    "battery": 50,
    "lastupdated": "2022-09-09T18:52:36.769"
  },
  "swversion": "2.3.088",
  "type": "ZHABattery",
  "uniqueid": "08:6b:d7:ff:fe:57:c4:64-01-0001"
}

```
![image](https://user-images.githubusercontent.com/28068256/189424839-9b166ab3-b4ed-40c4-ba6b-bb5a5477fbd5.png)

Just pressing 
![image](https://user-images.githubusercontent.com/28068256/189424922-efbb8b7b-d633-4e10-b4e6-4dcf9bd1e3a8.png)
then 
![image](https://user-images.githubusercontent.com/28068256/189424991-f6bc4b4f-faa2-44a1-8cc5-86b504bb9675.png)
makes the item become Online:
![image](https://user-images.githubusercontent.com/28068256/189425092-f3875ac7-f374-4971-8649-0ed2f48240d4.png)

This behaviour is also seen on Switches and other Aqara/Lumi sensors so it is probably a common cause.

## Steps to Reproduce (for Bugs)
I am not sure how to reproduce, but it seems to happen more often when restarting deconz while OH is still running.
The above example happened sometimes during a 32 day uptime of the whole system.

## Your Environment

* Version used: (e.g., openHAB and add-on versions)
* OH 3.3.0 Release, deconz 2.16.1
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...):
```
omr@shs2:~$ java --version
openjdk 11.0.16 2022-07-19
OpenJDK Runtime Environment (build 11.0.16+8-post-Ubuntu-0ubuntu118.04)
OpenJDK 64-Bit Server VM (build 11.0.16+8-post-Ubuntu-0ubuntu118.04, mixed mode, sharing)
omr@shs2:~$

```
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...):
```
omr@shs2:~$ uname -a
Linux shs2 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
omr@shs2:~$

```

**Comment by jlaur** [comment]
See also #12281.

**Comment by jlaur** [comment]
@olemr - is the bridge also OFFLINE when this happens, or only the sensor thing? Can you provide TRACE logs?

**Comment by olemr** [comment]
Only the sensor/switch thing is listed as Offline, but the device/channels works just fine, so this is just cosmetic ...

**Comment by lhurt** [comment]
> @olemr - is the bridge also OFFLINE when this happens, or only the sensor thing? Can you provide TRACE logs?

In my case the bridge is mostly also offline.

**Comment by Redsandro** [comment]
This appears similar to issue #13740 but not identical because of these differences:

1. #13740 doesn't show anything as offline
2. #13740 happens in the opposite case of what you describe.

To elaborate on that second point, you describe this happens often when deconz is restarting. Could you double-check to see if it's not the other way around as described in #13740? E.g.: restart OpenHAB _while_ deconz is offline, and then start deconz?

**Comment by lhurt** [comment]
Hi,

sorry to reply late. I double checked and you’re right. The deconz binding gets back online after restart of deconz docker container on remote server, but not the other way around.

 

One thing I noticed is that some temperature sensors did not come online unless I disabled and reenabled them. This only applies to sensors. When checking in Phoscon Web App or VNC conbee Monitor, it’s clearly visible that the sensor provides new values.

The openHAB thing stays offline. So there may be more than one issues.

 

Hope it gets fixed soon.

 

Thanks a lot

Von: Redsandro ***@***.***> 
Gesendet: Freitag, 18. November 2022 01:39
An: openhab/openhab-addons ***@***.***>
Cc: dolittle ***@***.***>; Comment ***@***.***>
Betreff: Re: [openhab/openhab-addons] [deconz] Sensors may appear Offline after been Unreachable and becoming Reachable again. Comes Online after disable/enable (Issue #13368)

 

This appears similar to issue  <https://github.com/openhab/openhab-addons/issues/13740> #13740 but not identical because of these differences:

1.	#13740 <https://github.com/openhab/openhab-addons/issues/13740>  doesn't show anything as offline
2.	 <https://github.com/openhab/openhab-addons/issues/13740> #13740 happens in the opposite case of what you describe.

To elaborate on that second point, you describe this happens often when deconz is restarting. Could you double-check to see if it's not the other way around as described in  <https://github.com/openhab/openhab-addons/issues/13740> #13740? E.g.: restart OpenHAB while deconz is offline, and then start deconz?

**Comment by Redsandro** [comment]
@jlaur it seems like multiple issues boil down to the same problem: The bridge loses the connection and OpenHAB never reconnects properly. If DeCONZ goes down temporarily, the bridge will not work until OpenHAB is restarted.

These issues can be fixed with a `docker-compose restart` in the OpenHAB directory, but until you manage to login and do that, all the OH+DeConz dependent domotics in the house will be unavailable.

**Comment by jlaur** [comment]
> @jlaur it seems like multiple issues boil down to the same problem: The bridge loses the connection and OpenHAB never reconnects properly. If DeCONZ goes down temporarily, the bridge will not work until OpenHAB is restarted.

I still have a hope that @MHerbst will backport fixes provided in the smarthomej repository since this would probably fix multiple issues - and we have many. See https://github.com/openhab/openhab-addons/pull/12223#issuecomment-1328074472
