### ISSUE TITLE
[HomeWizard] Add Energy Socket and Watermeter

### ISSUE THREAD

**Issue by Daniel-42** [openhab/openhab-addons#13434]
The HomeWizard binding currently only supports their P1 meter.

Since I now own their Watermeter and a couple of Energy Sockets, I would like to see support for these devices in  the binding.

**Comment by lsiepel** [comment]
I think this request was fullfilled a couple of weeks ago. Somehow  this issue was not linked to that PR.
For reference: https://github.com/openhab/openhab-addons/pull/13495

Also see the release notes here: https://github.com/openhab/openhab-distro/releases/tag/4.3.0.M1
When available in a milestone it will also become available in the next stable release (somewhere december 2024)
