### ISSUE TITLE
[avmfritz] pollingInterval and HAN_FUN_CONTACT

### ISSUE THREAD

**Issue by ReArtu** [openhab/openhab-addons#13655]
In my opinion, pollingInterval minimum has to be lower than 5. It's to high for door/window contact. In addition, it would be nice to have a channel linked to "lastalertchgtimestamp" (when the timestamp change, it could mean that someone opened the door/window and be detected even with a long pollingInterval).

https://github.com/openhab/openhab-addons/blob/1e07d1af03fff4410b84d950479b1474595fa1e9/bundles/org.openhab.binding.avmfritz/src/main/java/org/openhab/binding/avmfritz/internal/handler/AVMFritzBaseBridgeHandler.java#L135

**Comment by lsiepel** [comment]
Maybe @cweitkamp knows why this polling interval must be 5+ seconds? I assume this is set because the box gets unresponsive/overloads or something like that?

**Comment by kojid0** [comment]
Maybe @cweitkamp knows why this polling interval must be 5+ seconds? I assume this is set because the box gets unresponsive/overloads or something like that?

It would be nice to set the polling interval below 5 seconds. I have a DECT 440 device and whenever I press a button, the TRIGGERED event is very delayed. I use the buttons to control shelly devices in order to turn light on/off.

**Comment by kojid0** [comment]
It would be nice to set the polling interval below 5 seconds. I have a DECT 440 device and whenever I press a button, the TRIGGERED event is very delayed. I use the buttons to control shelly devices in order to turn light on/off.

**Comment by cweitkamp** [comment]
In general there is no argument against decreasing the minimum polling interval to 1s. I will prepare a PR for that.

**Comment by kojid0** [comment]
> In general there is no argument against decreasing the minimum polling interval to 1s. I will prepare a PR for that.

Thank you so much!
