### ISSUE TITLE
[systeminfo] broken when thing defined in text file

### ISSUE THREAD

**Issue by UrsusS** [openhab/openhab-addons#13708]
The version in 3.4.0.M4 does not work with a textual thing definition as discussed [here]
(https://community.openhab.org/t/openhab-3-4-milestone-discussion/138093/105):

At least I would like to have a warning in startup that the dynamic channels can't get created and that the startup proceeds with the static channels as before.

**Comment by lolodomo** [comment]
PR #13562 broke something. In worst case, we should revert that change.

**Comment by andrewfg** [comment]
With the thing defined via a .things file, when the system initially starts up, I get the following error, and the thing is shown as offline.


```
2022-11-13 22:09:52.696 [WARN ] [mon.registry.AbstractManagedProvider] - Could not update element with key systeminfo:computer:g24 in ManagedThingProvider, because it does not exists.
```
However if, after the system has started, I then disable and re-enable the thing, then it goes online normally.

So @mherwege this makes me suspect that there is possibly some kind of timing issue…

**Comment by Hilbrand** [comment]
This seems to be a bug in core. The systeminfo calls the method `migrateThingType`, which directly calls the managed thing provider (managed things are things created via the UI, unmanaged things are created via text files). The `migrateThingType` method should have called an update thing in a similar way as the `thingUpdated` method (in core). I guess the method `migrateThingType` was never used before.

The reason it works when disable and re-enable the thing, is because the `migrateThingType` fails in the last statement in that method. So all code steps needed before are done. When one disables and re-enables a thing openHAB will re-initialize the thing. This will again call the `thingUpdated` method because the binding will always update the thing (via `updateProperties()`) and that triggers a `thingUpdated` (The method that should have been called in `migrateThingType`) and because the thing changes in the binding are still there it will update with the correct thing data, and because the binding internally still has the modified thing it won't call `migrateThingType` again.

I've created a pr with a fix for core: https://github.com/openhab/openhab-core/pull/3162

**Comment by lolodomo** [comment]
Should be fixed. 
@UrsusS : please reopen in case you have still the issue.
