### ISSUE TITLE
[siemensrds] Unit test failing

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab-addons#13906]
On Windows 10:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.openhab.binding.siemensrds.test.TestRdsData
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.7 s <<< FAILURE! - in org.openhab.binding.siemensrds.test.TestRdsData
[ERROR] org.openhab.binding.siemensrds.test.TestRdsData.testAccessToken  Time elapsed: 0.402 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
        at org.openhab.binding.siemensrds.test.TestRdsData.testAccessToken(TestRdsData.java:208)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   TestRdsData.testAccessToken:208 expected: <true> but was: <false>
[INFO]
[ERROR] Tests run: 6, Failures: 1, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by lolodomo** [comment]
If I replace the current line by `expDate = new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss z", Locale.ENGLISH).parse(expires);`, the test is then OK.

**Comment by andrewfg** [comment]
@lolodomo good catch!

The ClimatixIC cloud server speaks English; AFAIK it is an (American) AWS server. So the `isExpired()` method must indeed parse the date using English day / month names ('Sun' vs 'dim.' / 'Dec' vs 'déc.', etc.).  And therefore currently `isExpired()` will, as you say, fail on computers in regions where the language is not English.

Obviously my Windows PC, my Linux OH system, and the GitHub CI build system, have English locales, which explains why the problem was not broadly identified before now.

> not sure if the problem is only the unit test .. or more generally the binding

Luckily it is NOT a problem in the binding -- because the binding code actually never calls `isExpired()` (!!) -- instead, when the current token expires, the cloud server rejects the next API request with a 'not authorised' response, that forces the binding to request a new token. In other words the expiry check is done by the cloud server and not by the binding.

Nevertheless I will fix the issue in a forthcoming PR. I have a ReadMe update in the pipeline, so I will combine it with that.
