### ISSUE TITLE
[neohub] After adding repeater Heatmiser Boost, thermostat floor temperature channel returns incorrect value

### ISSUE THREAD

**Issue by my5bits** [openhab/openhab-addons#14042]
## Expected Behavior

There are several thermostats Heatmiser neoStat V2 in my setup, they are bound to NeoHub. All items are connected to OpenHab instance and worked flawlessly. After adding repeater Heatmiser Boost and binding couple of remote thermostats to it, remote thermostats report incorrect floor temperature in OpenHab.

## Current Behavior
- remote thermostat (with repeater) reports 127.5 C floor temperature 

## Steps to Reproduce (for Bugs)

1. Bind thermostat to repeater
2. Check floor temperature channel on thermostat's OpenHab thing

## Your Environment

* Version used: (e.g., openHAB and add-on versions) 3.0
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): any
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Linux Mint
![2022-12-22 19_46_52-Window](https://user-images.githubusercontent.com/121252650/209195682-64a32374-4731-4c28-ae6b-9b6913a229c8.png)
![2022-12-22 19_48_15-Window](https://user-images.githubusercontent.com/121252650/209195688-f88a2c18-0f42-49bf-9626-8298f1c7c50d.png)

**Comment by andrewfg** [comment]
Two questions:
1. What value do you see in the Heatmiser App?
2. Can you please post a log trace?

**Comment by my5bits** [comment]
Answers:
1. Heatmiser Neo app reports only room temperature. It does not show floor temperature in it's UI. Refer to attached screenshots of Heatmiser Neo app and Openhab app.
2. Added trace for org.openhab.binding.neohub. Removed non relevant devices - device "Svetaine" refers to directly connected thermostat. Devices "Namelis 1" and "Namelis 2" are thermostats paired with repeater. Device "repeaternode31251" represents repeater.
![1673358906844](https://user-images.githubusercontent.com/121252650/211572141-82cdb9fb-e6e7-4892-84e0-5b91e4bedfcb.jpg)
![1673358906833](https://user-images.githubusercontent.com/121252650/211572150-8e43c2e4-e6f4-4136-a9e4-08d4e5d6d233.jpg)
[trace_neohub.txt](https://github.com/openhab/openhab-addons/files/10383398/trace_neohub.txt)

**Comment by andrewfg** [comment]
@my5bits many thanks for the logs etc.

I am afraid that your problem is NOT due to the OH binding but is rather something wrong in your HeatMiser setup. The log shows that the NeoHub is reporting `"CURRENT_FLOOR_TEMPERATURE":127` for the respective thermostat. (So OH is simply reporting that value). The value 127 is an error value which means either that the sensor is physically not connected to the thermostat, or that under floor temperature is disabled in the thermostat settings. => The thermostat feature settings should probably be: _"Feature 06 / Setting 03"_ (see below)..

![image](https://user-images.githubusercontent.com/893994/211579921-78633ff5-1d04-4dcf-bc07-ebfbbd3f3250.png)

**Comment by my5bits** [comment]
Yes! You are right! All custom settings were reset to factory settings. I suppose that this happened during the pairing process with repeater. With correct settings floor temperature is reported properly.
![2023-01-10 17_39_01](https://user-images.githubusercontent.com/121252650/211596227-c2519202-0bde-42f8-9dad-a208fac66d8d.png)
Thank you for your help!
