### ISSUE TITLE
[bosesoundtouch] possible preset issue

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-addons#14167]
Hi everybody,

I would like to thank you for your great work. I started with installing a new openHAB server in version 3.4.0 and I have 2 Soundtouch devices - Soundtouch 10 and Soundtouch 130 which in reality is a Cinemate 130 with a SoundTouch Wireless link adapter. I had issues with state updates and I did a lot of debugging to understand what is happening. I even put my openhab log settings in Debug mode and I saw that the requests were often send twice or not correctly parsed. This has all been fixed since I downloaded your last JAR file from your onedrive account to use it to bind my soundtouch devices.

I still have 2 problems and I do not find any solution to this. As I'm quite new to openHAB, I'm not sure if it is a configuration issue on my side or still problems in the binding.
- PRESETS are not shown and I cannot select any other configured PRESETS on both devices.
- operationMode changes are not working. You cannot switch to TUNEIN from SPOTIFY or any other mode

I could take some traces to send it to you for debugging if this would help?

Kind regards,
Gilles

_Originally posted by @grassel82 in https://github.com/openhab/openhab-addons/issues/13842#issuecomment-1372723811_

**Comment by lsiepel** [comment]
@grassel82 Can you share your trace logs?

**Comment by grassel82** [comment]
Thank you for the update on issue1.

Issue 2 with presets: all tests were done on Soundtouch10. You are correct
with device has been turned on and preset 1 "tunein / rtl radio ..." was
running. On preset 2 I have another radio station on tunein configured. The
problem is when I click on the PRESET button, I get to the second
screenshot. So not really a choice between PRESETS, but this diagram.

There may be an issue in my configuration of the point PRESET in my
Soundtouch10 thing, but I do not see how to change this or if the point
PRESET has a bug in parsing the answer from the Soundtouch10 device.

I will do another trace this afternoon and upload here.

King regards,

Gilles

**Comment by grassel82** [comment]
Hi,

I did some additional debugging. I opened log:tail in openhab session and I do not see any entry in the log when I click on the PRESET link. I suppose that I normally should get a list with all the presets, but I get this diagram. After searching and trying multiple settings, I found that the diagram view has to do with the "SEMANTIC CLASS" of the PRESET item. I have set it to "Point" and this seems to be the wrong class. I tried a few ones, but the only one that let me choose was "Control".
Does it exist a documentation per binding which Semantic class should be used per item?

Only if I click on the NEXT or PREVIOUS button on the "PlayerControl" Link, I see log entries. I have attached the log trace when clicking on the PlayerControl NEXT/PREVIOUS.

Click "NEXT" done at 21:22.
Click "PREVIOUS" done at 21:23.
[bosesoundtouch10_PRESET.log](https://github.com/openhab/openhab-addons/files/10362853/bosesoundtouch10_PRESET.log)

These buttons are not working to jump to the next PRESET for example? Is this by design?

Kind regards,

Gilles

**Comment by grassel82** [comment]
Hi,
I found now the correct configuration to get a list with your PRESET definitions. I added them manually, but at least they are now correctly shown. Here my METADATA State description for the PRESET item. Semantic class is "Point". 

**"Metadata State Description" configuration:**
`value: " "
config:
  options: 1=RTL Radio Lëtzebuerg,2=Eldoradio,3=RPR1,4=SWR3
  step: "1"
  min: "1"
  max: "6"
`

So you need to configure these "State description" with an "options" list to get the correct behaviour. So this is fixed for me now.

Sorry that I thought it could be a bug. Here is a trace where I selected 2 PRESETs.
22:58: Switch to Preset 1 - RTL Radio Lëtzebuerg
22:59: Switch to Preset 3 - RPR1
[bosesoundtouch.log](https://github.com/openhab/openhab-addons/files/10363389/bosesoundtouch.log)

I hope this will help in the future other beginners in openHAB. I'm quite new, it is my first integration that I tried in openHAB.

Thank you a lot for your help, I really appreciated.

Kind regards,

Gilles

**Comment by lsiepel** [comment]
No problem, glad it turned out to be configuration instead of a bug.
Welcome aboard, the learning curve might be a bit steep in the beginning, but you're gonna love it :-)
