### ISSUE TITLE
[evcc] - writes to loadpoint ID 0 while evcc expects loadpoint ID 1

### ISSUE THREAD

**Issue by prior-philip** [openhab/openhab-addons#14275]
## Problem statement

Starting with evcc 0.111.1, no evcc parameters get updated.
eg:
- charging mode: off,pv,minpv,now
or
- target soc:0-100

Checking log trace in openhab-console showed that binding reaches out to loadpoint0 rather than loadpoint1, which is the first loadpoint per documentation at evcc -> https://docs.evcc.io/docs/reference/api/#rest-api
`19:22:49.454 [TRACE] [hab.binding.evcc.internal.api.EvccAPI] - POST http://localhost:7071/api/loadpoints/0/mode/pv - 404 page not found
`

Correct command would be for first loadpoint:
`POST http://localhost:7071/api/loadpoints/1/mode/pv`

## Possible Solution

- Adjust starting loadpoint ID 

## Context

- No loadpoint related data gets written to evcc. POST command receives 404 (see above)

## Your Environment

* Version used: 3.4.0M4
* Operating System and version ( RaspberryPi4B, Ubuntu 22.10 server):

**Comment by prior-philip** [comment]
Related to API change discussed here https://github.com/evcc-io/evcc/discussions/5522

**Comment by florian-h05** [comment]
Already fixed with https://github.com/openhab/openhab-addons/pull/14245.

You can get the fixed version from the community marketplace (I don’t recommend to use the SNAPSHOT version in production), you need to enable displaying of unpublished addons.

See https://community.openhab.org/t/evcc-binding-electric-vehicle-charging-control-beta/135209.
