### ISSUE TITLE
[Keba] allow faster update rates than 6 seconds

### ISSUE THREAD

**Issue by wolfijenne** [openhab/openhab-addons#14361]
The Keba add-on only initializes if the update rate is set to be slower than 5 seconds.
To allow Solar charging algorithms, a faster update rate would be great.

**Comment by lsiepel** [comment]
Removing (or lowering) this treshold is an easy fix from code perspective, but this is probably set on purpose. @kgoderis as you are mentioned as codewoner, do you know if this can be lowered? Just want to be sure it is not some API limitation.

Looking at the code and i thinkit is because of thise line:
`cache = new ExpiringCacheMap<>(Math.max(refreshIntervl - 5, 0) * 1000);` 

refreshInterval defaults to 15 seconds. So the cache expires at 2/3 of the interval. To me this looks like a good cache strategy, except that the 5 second is hardcoded/ not relative to the refreshInterval.

This could be changed to:
`cache = new ExpiringCacheMap<>(Math.max((refreshIntervl*1000) - (refreshIntervl*333)));`

**Comment by MikeTheTux** [comment]
I guess the min interval comes from the following requirement:
[kecontactp30udp_pgen.pdf](https://www.keba.com/download/x/4a925c4c61/kecontactp30udp_pgen.pdf):
> The minimum waiting time between the scheduled repetitions of any UPD
> command is defined as follows:
> ● t_COM_pause = 5 s

**Comment by lsiepel** [comment]
So can we conclude that this feature can't be added as it conflicts with the official documentation?

**Comment by lsiepel** [comment]
See previous post regarding official documentation. The 6 seconds are by design.
