### ISSUE TITLE
[openwebnet] Make initialization value of Auxiliary to NONE

### ISSUE THREAD

**Issue by fabgio** [openhab/openhab-addons#14744]
Currently an Auxiliary item's initialization value is set to Null which seems an erratic status  to the user. So it  would be better to initialize the item  to NONE as AlarmHandler class  does. 

Minor fix: correct the Auxiliary class' Javadoc to cut the sentence "NOTICE: Support for handling messages from the bus regarding alarm control has to be implemented" as  the feature  has been implemented

**Comment by fabgio** [comment]
I will handle this!

**Comment by mvalla** [comment]
I think this PR is invalid as possible WHAT values defined for AUX, as documented in the Specs (Who=5, page 7) are: ON, OFF, TOGGLE, STOP, UP, DOWN, ENABLED, DISABLED, RESET_GEN, RESET_BI, RESET_TRI and there is no NONE value defined. So at initialization is perfectly fine that the channel value is Null as it happens for every other channel in OH which has not been updated yet.

Regarding the fix to Javadoc: since support for handling AUX messages from the BUS is in fact not supported yet, I think the comment should stay there.

So for me this issue should be closed as invalid.

**Comment by lolodomo** [comment]
@mvalla arguments look good to me. 
Let's close the issue.
