### ISSUE TITLE
[nest] Remove WWN support

### ISSUE THREAD

**Issue by wborn** [openhab/openhab-addons#14761]
See: https://support.google.com/googlenest/answer/9293712?hl=en

> Starting September 29, 2023, all Works with Nest connections will stop working.

**Comment by jlaur** [comment]
@wborn - I'm wondering if there is another API ("native Nest API") we could implement to continue Nest support - see https://github.com/chrisjshull/homebridge-nest.

Based on this project, I was able to authenticate at https://home.nest.com/session, but didn't dig further yet. I also had a brief look at the Nest binding code, but so far only identified it to use a different endpoint, so don't even know if it's the same API. However, I suspect not, since it seems Nest Protect is supported by this API with Google authentication.

**Comment by wborn** [comment]
It's probably the APIs used by the App. The App will probably also be killed when everything is integrated in Google Home.  They could also opt for declaring some products EOL and not support them in Google Home and then kill those unofficial APIs.

**Comment by jlaur** [comment]
> It's probably the APIs used by the App. The App will probably also be killed when everything is integrated in Google Home.

If they kill the app now, wouldn't that render Nest Protect completely uncontrollable, or do you know if it can be configured and controlled from the Google Home app after being migrated? One thing is losing API access, but it would be much worse if they remove all access. In that case I'd go looking for a lawsuit I could join. 🙂
