### ISSUE TITLE
[easee] DNS failure is flagged as configuration error

### ISSUE THREAD

**Issue by alexf2015** [openhab/openhab-addons#14876]
If Cloud API endpoint cannot be reached due to `Request failed: java.net.UnknownHostException: api.easee.cloud: Temporary failure in name resolution` the bridge goes offline with reason ERROR:CONFIG instead ERROR:COMM

**Comment by lsiepel** [comment]
Don't think this is an actual bug. CONFIG and COMM are both used for this same exception.

From binding perspective it is hard to say if it is configuration error like wrong DNS name, typo or whatever or a communication error because the DNS server went down or DNS-misonfiguration.

The status detail does give some indication of the problem, and then you can decide what to do. Or do you mis something?

**Comment by alexf2015** [comment]
You are right if the the name resolution failure is caused by a wrong hostname this is a configuration error. Thus it is hard to decide.
