### ISSUE TITLE
[mapdb] Persistence service blocks item notifications

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-addons#14899]
MapDB block item thread pool when a lot of states are stored.

Discovered in https://github.com/openhab/openhab-core/issues/3578

**Comment by J-N-K** [comment]
@openhab/add-ons-maintainers It could be that this also affects other persistence add-ons. Someone might want to check that.

**Comment by jlaur** [comment]
@J-N-K - thanks for sharing, I have checked jdbc, and it also suffers from this problem. It even makes synchronous network calls during `store`.

**Comment by J-N-K** [comment]
That's similar to what influxdb does.

**Comment by lolodomo** [comment]
I just have a quick look to rrd4j persistence and the store of data is synchronous too. So I guess it should be also fixed.

PS: you made an incredible discovery @J-N-K , strange that it was not detected before.

**Comment by florian-h05** [comment]
> PS: you made an incredible discovery @J-N-K , strange that it was not detected before.

I had serious performance issues where groups nearly completely missed state updates from their members, so thanks again for finding the root cause @J-N-K!

**Comment by J-N-K** [comment]
Similar issues were already reported earlier, but the reports did not contain enough information to find it. I believe that at least some of the issues like https://github.com/openhab/openhab-core/issues/3531 have similar reasons.

**Comment by florian-h05** [comment]
> Similar issues were already reported earlier, but the reports did not contain enough information to find it.

Then I'm glad I was able to provide enough information!

> It happened when you had a massive number of state updates, is that correct ?

Correct. e.g when I turned my light `Florian_Licht` on/off, the `F2_Florian_Licht`, `F2_Florian`, `gLicht` groups were informed, which are nested in other groups, and for each Item the `PersistenceManager` as well. This lead to peaks of over 30 listeners to get informed in one second, which were scheduled but never executed because the thread was too busy with persistence. Seehttps://github.com/openhab/openhab-core/issues/3578 for more information.

> The problem is that all persistence services have probably to be updated. Priority should be RRD4J which is the default persistence service

As Jan said in the core issue, the problem is that the persistence services did not implement `PersistenceService.store` well, see https://github.com/openhab/openhab-core/issues/3578#issuecomment-1525381161.

And I agree that RRD4J should be the top priority.
