### ISSUE TITLE
[Shelly] thing-type: shellyplus1 - shows only 3 instead of 5 external temp sensors

### ISSUE THREAD

**Issue by K-Stefan** [openhab/openhab-addons#14969]
I just configured my shellyplus1 with 5 temperature sensors. But I can only configure 3 external sensors. The text-based-config is for sensors 4 and 5 is ignored. According to the documentation it is supported: https://www.openhab.org/addons/bindings/shelly/#shelly-plus-1-thing-type-shellyplus1

```
Number Shelly_HeizungTemp_1 "Heizung Temperatur 1" <temperature> (HeizungTemp) {channel="shelly:shellyplus1:heizungtemp:sensors#temperature1"}
Number Shelly_HeizungTemp_2 "Heizung Temperatur 2" <temperature> (HeizungTemp) {channel="shelly:shellyplus1:heizungtemp:sensors#temperature2"}
Number Shelly_HeizungTemp_3 "Heizung Temperatur 3" <temperature> (HeizungTemp) {channel="shelly:shellyplus1:heizungtemp:sensors#temperature3"}
Number Shelly_HeizungTemp_4 "Heizung Temperatur 4" <temperature> (HeizungTemp) {channel="shelly:shellyplus1:heizungtemp:sensors#temperature4"}
Number Shelly_HeizungTemp_5 "Heizung Temperatur 5" <temperature> (HeizungTemp) {channel="shelly:shellyplus1:heizungtemp:sensors#temperature5"}
```
The GUI (http://hostname:8080/settings/things/shelly:shellyplus1:heizungtemp) also shows only 3 temperature sensors:
![image](https://github.com/openhab/openhab-addons/assets/10091275/da53e9ca-8439-40ce-9d42-cbebad7f6230)

Screenshot of my 5 temperature sensors on the Shelly 1 Plus: 

![image](https://github.com/openhab/openhab-addons/assets/10091275/e63f6b05-f367-49eb-96e3-cd48d98a07f3)

I restarted / rebooted Openhab and Shelly multiple times without any improvement.

## Expected Behavior
5 Temperature Sensors

## Current Behavior
Only 3 Temperature Sensors are usable. 

## Possible Solution

I`m not a java developer, but I browsed through the source code a little bit. I found a potential failure. 

Here are just 3 extTemperature.sensors within the if statement:

https://github.com/openhab/openhab-addons/blob/6784d22ab9976cb1355b975d889acfeaa9bcce70/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/provider/ShellyChannelDefinitions.java#L351

On this place are 5 external sensors defined: 

https://github.com/openhab/openhab-addons/blob/6784d22ab9976cb1355b975d889acfeaa9bcce70/bundles/org.openhab.binding.shelly/src/main/java/org/openhab/binding/shelly/internal/ShellyBindingConstants.java#L184

## Your Environment

* Version used: openHAB and add-on versions: 3.4.4
Operating System and version:
```
uname -a
Linux openhabian 6.1.21-v7+ #1642 SMP Mon Apr  3 17:20:52 BST 2023 armv7l GNU/Linux
```

**Comment by markus7017** [comment]
I found the bug and will provide an update today

**Comment by habmartin** [comment]
Hi Markus, has this issue been fixed?

**Comment by markus7017** [comment]
yes, check latest DEV build
https://community.openhab.org/t/shelly-binding/56862/3311

**Comment by GRG49** [comment]
I am evaluating openHab to see if it fulfills me need. I 've installed openHAB under windows 10.
With version 3.?.? I had the same problem as K.Stefan: only temp sensor 1 to 3 were detected. This week I installed version 4.0.0 and now none of the external sensors are detected. I installed again version 3 (this time 3.4.4) and none of the external sensors are detected.

**Comment by botrfly** [comment]
I've experienced the similar problem for version 4.0.4 of OpenHAB/Shelly binding in combination with ShellyPlus1, the addon and 5 external DS18B20 temperature sensors. 

In a first run, I've attached 3 external sensors to the Shelly and when adding the device as a 'thing' in OH, these 3 temperature sensors were correctly presented as channels. 

After removing the 'thing' from OH, I've attached two additional sensors, thus resulting in 5 external DS18B20 temperature sensors. After them being added in the web interface of the Shelly device, all 5 sensor worked well and showed temperature values there. Afterwards, adding the device to OH again, however, resulted in a 'thing' without any external temperature sensors being shown (not the 2 additional ones, but even not the 3 that were previously found).

Did I maybe overlook that this issue is currently being addressed and going to be fixed? If so, I'll just  patiently wait for the 4.1 release and many thank's to the developer(s) 
;-)

**Comment by GRG49** [comment]
With version 4.0.4 I have still the problem, that the channels of the external sensors of the Shelly addon were not automaticly detetected. The only work around I found was to add theese channels via the API explorer: "PUT /things/{thingUID}"
`	{
	  "linkedItems": [],
	  "uid": "shelly:shellyplus1pm:ShellyPlus_1PM_WPTemp:sensors#temperature1",
	  "id": "sensors#temperature1",
	  "channelTypeUID": "shelly:sensorExtTemp",
	  "itemType": "Number:Temperature",
	  "kind": "STATE",
	  "label": "Temperatur 1",
	  "description": "Die vom Sensor gelesene Temperatur",
	  "defaultTags": [],
	  "properties": {},
	  "configuration": {}
	},
`
(for the others sensors accordently.)

The config request to the Shelly (/rpc/Shelly.GetConfig) returns the correct answer:
`"sys": {
        "device": {
              "name": "ShellyPlus1PM-WPtemp",
              "mac": "441793AC90EC",
              "fw_id": "20231106-160250/1.0.8-gdba0ee3",
              "discoverable": true,
              "eco_mode": false,
              "addon_type": "sensor"
        },
        "location": {
              "tz": "Europe/Berlin",
              "lat": 49.865710,
              "lon": 8.626040
        },
        "debug": {
              "level": 2,
              "file_level": null,
              "mqtt": {
                    "enable": false
              },
              "websocket": {
                    "enable": true
              },
              "udp": {
                    "addr": null
              }
        },
        "ui_data": { },
        "rpc_udp": {
              "dst_addr": null,
              "listen_port": null
        },
        "sntp": {
              "server": "time.google.com"
        },
        "cfg_rev": 26
  },
  "temperature:100": {
        "id": 100,
        "name": "Brunnen ein Temp ",
        "report_thr_C": 0.1,
        "offset_C": 0.0
  },
  "temperature:101": {
        "id": 101,
        "name": "Brunnen aus Temp",
        "report_thr_C": 0.1,
        "offset_C": 0.0
  },
  "temperature:102": {
        "id": 102,
        "name": "Sole ein Temp",
        "report_thr_C": 0.1,
        "offset_C": 0.0
  },
  "temperature:103": {
        "id": 103,
        "name": "Sole aus Temp",
        "report_thr_C": 0.1,
        "offset_C": 0.0
  },
  "temperature:104": {
        "id": 104,
        "name": null,
        "report_thr_C": 0.1,
        "offset_C": 0.0
  },
  `
But somehow this reponse is not correctly recognized by the binding.

**Comment by markus7017** [comment]
Please provide a DEBUG log of the initialization
and make sure to use latest DEV build


[4.1-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.1.0-SNAPSHOT.jar?raw=true) | [4.0.-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.0.5-SNAPSHOT.jar?raw=true) | [3.4.5-DEV](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.4.5-SNAPSHOT.jar?raw=true) | [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) | **[READMEbeta](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md)** 
[Avdanced Users](https://github.com/markus7017/myfiles/blob/master/shelly/doc/AdvancedUsers.md) - [Shelly Manager](https://github.com/markus7017/myfiles/blob/master/shelly/doc/ShellyManager.md) - [Bugs/Features](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+%5Bshelly%5D) -  [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server) | [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de)

---

Note: The DEV build is always newer than the version in the official Distro or Milestone builds. Current development is based on 4.1-SNAPSHOT, **4.0.x and 3.4.x might be outdated**.

**Comment by stuetzomat** [comment]
hello markus.

i took a closer look at this problem yesterday. 
i am using (4.1.0) and i generate the items via an item file.

please also have a look at my answer here...
https://github.com/openhab/openhab-addons/issues/15615#issuecomment-1846264424

the problem still exists. maybe a little more detail....

after restarting openhab i usually lost the channels for the shelly plus. so yesterday i tried everything to get the channels working again. everything works fine in the shelly app - no chance in openhab.

only when i reset the shellyplus to factory settings and then added the first temp channels again did it work. but only 3/5 channels. on the contrary, the shelly binding lags a little when i activate the 4th channel on the shelly. 

additional info: i then imported the item file with the three sensors and realised that the order was not correct for me. So i changed the file and saved it again. in the end there were two items on one channel and i couldn't delete it on the openhab UI because i was using the text files. again i could only solve this problem by doing a factory reset.

now it looks like the shellyplus with the 3 temperature addons are running without any problems. i hope that this will still be the case after restarting openhab.

but of course it would be great if all 5 temperature add-ons worked. Perhaps you could have a look at this.

thank you, best regards

christoph

**Comment by markus7017** [comment]
this has been fixed in between
try with latest DEV build 
https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-4.2.0-SNAPSHOT.jar?raw=true
