### ISSUE TITLE
[shelly] Low signal strength device blocks OH thread pool (thus blocking other bindings)

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-addons#15164]
This issue was originally reported on the forum [HERE](https://community.openhab.org/t/hue-binding-for-api-v2-3-4-0-0-4-0-0-0/146799/32?u=andrewfg).

If there are Shelly devices added as thing/item, which are located on the edge of the WiFi (with low signal strength), then the updating of those devices can cause threads in the OH core thread pool to block. And since there are only 5 threads in the OH core thread pool, this can cause the updating of other bindings to block as well.

Notes:
- Such Shelly devices are also slow if one tries to connect them directly via the web browser.
- Workaround is to install a WiFi range extender.

**Comment by HolgerHees** [comment]
about the threadpool, I found this

https://community.openhab.org/t/oh3-ruleengine-parameter-in-threadpool/117317/5

**Comment by andrewfg** [comment]
^
That is not relevant. This case refers to the scheduler thread pool. Of which there are indeed 5. Also in OH v3 and OH v4.

**Comment by markus7017** [comment]
The binding does synchronous calls tp the http client, so esp. when connecting to an device running into a timeout this could happen and I suppose the thread is blocked. Do you have a Shelly Plus/Pro nearby. Those could act as a range extender themself, maybe that's a feasible approach.

**Comment by Struppie** [comment]
> The binding does synchronous calls tp the http client .... I don't consider this as a bug. What do you expect with insatiable WiFi connections? This makes all channel data and commands unreliable and results in a OH status out of sync.

Hi @markus7017  - personally I solved the issue with a WiFi repeater and now it is running fine (thanks for the hint regarding the range extender functionality).
What I recognised as a problem is that it seems, that other bindings are negatively influenced by this situation. Of course I don't expect that the status of the Shelly device which is at the edge of the WiFi area is always correct. No problem if this one would be slow or even doesn't work at all. But my finding was that other bindings got stuck in this situation. Means my impression is, that something in OpenHAB itself got stuck (thread pool?) and has a negative influence to other bindings, because of that one Shelly device not answering right away. Is that possible?
(I recognised slow behaviour of the Hue binding in this situation and if I disabled the Shelly binding, everything was working well again with the Hue binding)

**Comment by hmerk** [comment]
@Struppie 
I have some shellys myself with bad WiFi connection, sometimes react very slow when opening their web page. But this has zero impact to my openHAB installation at all.
So what you discovered might be a coincidence, but is not directly related.

**Comment by Struppie** [comment]
@hmerk 
That can be the case. We tracked this down on the Hue binding side and recognised, that an event was received, but to working on it did needed a huge amount of time when the Hue binding was using a thread pool thread of OpenHAB for this. If I disabled the Shelly binding, it worked right away. Also changing the Hue binding to use a separate thread helped in this situation.

I think typically you don't recognise if the work on an event starts e.g. some seconds later. But I'm using Hue motion events to switch on lights and walking into a dark room will be recognised quickly ;)

I'm not saying, that it is 100% the Shelly binding cousing this, but I had the indications above - if there is a possibility to analyse or prove the above theory it may be worth to track this down :)

**Comment by andrewfg** [comment]
IMHO any binding that makes TCP calls on a remote server should implement 1) a socket connect timeout, and 2) a request timeout. I did not check the Shelly binding code, so I don't know if such are implemented in it.

**Comment by hmerk** [comment]
As far as I know, Shelly binding is using openHABs httpclient implementation, which from my knowledge has a default timeout set.

**Comment by markus7017** [comment]
yes, I'm using the default timeouts

**Comment by markus7017** [comment]
PR #15284 includes a reduced request timeout and setting connect timeout, both 10sec
