### ISSUE TITLE
[network] Pingdevice on Docker-Install results in massive threads

### ISSUE THREAD

**Issue by scriptwriter13** [openhab/openhab-addons#15437]
if you are using network-binding with a pingdevice under docker, which normally is used to run not only the container openhab but other containers too you have also a lot of bridge networks which links container. This can result in massive open threads through multiplication. So 30 networks and 10 pingprofiles could impact 300 parallel threads.
On my system load is about 20 if the 10 profiles started to a system-load about 1 if all profiles are disabled.

## Expected Behavior
on docker it should should only start 1 thread from 1 network per ping-profile

## Current Behavior
it opens for 1 ping-profile 1 thread per network instead of 1 thread
- you will get output of all threads loke that:
```
nobody      4261  0.0  0.0   9140  4836 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-e77d9bdcb692 192.168.2.254
nobody      4264  0.5  0.0   9140  4772 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-3a8bcb7e1a20 192.168.2.254
nobody      4270  0.5  0.0   9140  4804 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-5dbd2b0f47cf 192.168.2.254
nobody      4274  0.5  0.0   9140  4876 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-4c02ad546123 192.168.2.254
nobody      4277  0.5  0.0   9140  4884 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-c8c8be0340ae 192.168.2.254
nobody      4283  1.0  0.0   9140  4872 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-d125af02b9b4 192.168.2.254
nobody      4285  0.5  0.0   9140  4828 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-72ac99832aa5 192.168.2.254
nobody      4288  1.0  0.0   9140  4916 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-b3d1fee00881 192.168.2.254
nobody      4290  0.5  0.0   9140  4848 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-77b0d455dbc2 192.168.2.254
nobody      4292  0.5  0.0   9140  4796 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-37b7e1374480 192.168.2.254
nobody      4294  0.5  0.0   9140  4800 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-c6afe6811015 192.168.2.254
nobody      4296  0.5  0.0   9140  4956 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-ad8705eb98cb 192.168.2.254
nobody      4298  1.0  0.0   9140  4892 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-8a8f9f51418c 192.168.2.254
nobody      4309  0.5  0.0   9140  4836 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-eb09dae5f21e 192.168.2.254
nobody      4322  0.5  0.0   9140  4888 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-32b28ae41ba6 192.168.2.254
nobody      4331  0.5  0.0   9140  4880 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-bf53bf1036dd 192.168.2.254
nobody      4334  0.5  0.0   9140  4884 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-f89f1a0e504d 192.168.2.254
nobody      4346  1.0  0.0   9140  4872 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-2db6488b5fc1 192.168.2.254
nobody      4347  1.0  0.0   9140  4936 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-b6dd5302b3c3 192.168.2.254
nobody      4355  1.0  0.0   9140  4884 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-225545b56f9e 192.168.2.254
nobody      4357  1.0  0.0   9140  4880 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-c1e8628f5e78 192.168.2.254
nobody      4360  1.0  0.0   9140  4768 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-ba49e533177b 192.168.2.254
nobody      4373  1.0  0.0   9140  4824 ?        S    08:29   0:00 arping -w 5 -C 1 -i docker0 192.168.2.254
nobody      4374  1.0  0.0   9140  4888 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-0ced1bc112c8 192.168.2.254
nobody      4377  0.0  0.0   9140  4884 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-09b6e1630d76 192.168.2.254
nobody      4380  1.0  0.0   9140  4932 ?        S    08:29   0:00 arping -w 5 -C 1 -i br-46ec93053821 192.168.2.254

```

## Possible Solution
use only the selected network from system-settings-network in openhab, 
OR 
make network-port selectable
OR
let routing of system decide where the package has to go to

## Steps to Reproduce (for Bugs)
- install openhab 4.0.1 (possibly other versions has this too) on docker, network mode host
- select under system settings network your main ethernet of the docker host
- create multiple app-Containers and bridge networks which connecting them, maybe an app-container linking to a database. If you dont know which containers link apache{1,2,3} to mysql{1,2,3} to get 3 apps with their database and their own bridge between)
- verify that you have multiple bridges created with `docker network ls`
- create a network-binding profile like that:
```
UID: network:pingdevice:4b7f079f3f
label: InternetRouter
thingTypeUID: network:pingdevice
configuration:
  hostname: 192.168.2.254
  refreshInterval: 60000
  retry: 1
  timeout: 5000
```
- enable this profile and directly then directly watch next command
- `docker exec  [containername] ps aux|grep arping`
(repeat if you want until next refreshinterval if you want)

## Context
for 1 ping on my side 26 arping-threads are opened which resulting on pinging multiple devices in a high thread. I would expect 1 thread per ping-profile
Also created Community-Discussions: [https://community.openhab.org/t/openhab-4-0-1-and-network-pingdevice-on-docker-install-results-in-massive-threads/148658](https://community.openhab.org/t/openhab-4-0-1-and-network-pingdevice-on-docker-install-results-in-massive-threads/148658)

## Your Environment

* Version used: openhab/openhab:4.0.1 on docker
* Operating System and version : Debian GNU/Linux 11 (bullseye), Docker-CE

**Comment by jamesmelville** [comment]
As codeowners @davidgraeff @mettke, what would you think of a PR which did the following?:
- added a config param called `arpingInterface` ("arping Network Interface") to each `pingdevice` thing
- if this param was populated, arpings would only be issued to that interface
- if this param was blank, current behaviour (arping executable call to every interface) would continue.

**Comment by SHU-red** [comment]
Hello,
this topic is very important for me and i opened already an issue at
https://github.com/openhab/openhab-distro/issues/1619#issuecomment-1865070624

Due to the fact that both topics could be the same i closed the other one in aggreement of @wborn

With my `CoreOS[ Docker[ openHAB-Milestone ] ]` setup im experiencing a unresponsive openHAB and 100% CPU load

As already mentioned in the other issue i opened i recently had to increase my number of docker-networks to increase the range of ip-adresses available to docker as mentioned here:
https://stackoverflow.com/questions/41609998/how-to-increase-maximum-docker-network-on-one-server

So i added a `daemon.json` to my `/etc/docker` directory and added to the normally 30 docker networks 255 more!
I need this because im running many docker-containers on my system

I could not 100% eliminate the high CPU load by uninstalling the network binding but everything makes sense and i had many many network binding entries in my frontail log

This topic is very important for me and for sure i will try to check out any debugging or testing

**Comment by SHU-red** [comment]
I re-tested this with the newest milestone, pushed yesterday --> Same problem --> Extremely high load caused by openhab

Frontail is also flooded with errors like these:
```
2023-12-22 10:44:20.133 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'counters-3' failed: An error occurred during the script execution: Cannot invoke "org.openhab.core.model.rule.scoping.RulesClassCache.get(Object)" because "cache" is null in counters
```

I absolutely do not know what im talking about but i guess that these errors are only a result of the lack of ressources due to the high system load?

Right now im really not able to use a newer openhab than `4.0.4 Release Build`

**Comment by SHU-red** [comment]
Also following this guide does not resolve my problem:
https://straz.to/2021-09-08-docker-address-pools/

**Comment by SHU-red** [comment]
And now i did a test using `openHAB 4.1.0 Release Build`
with the configuration for docker-networks considered to be the default one:
```
{
   "default-address-pools": [
        {
            "base":"172.17.0.0/12",
            "size":16
        },
        {
            "base":"192.168.0.0/16",
            "size":20
        }
    ]
}
```

***Result:***
- Still 100% CPU load (`$ top` still says `java` using 155% of the cpu)
- At this point im not sure anymore if the change in docker `default-address-pools` is the root cause of this problem

My frontail shows me frequently some of those errors:

```
2023-12-27 13:32:54.643 [WARN ] [service.internal.HttpServiceDisabled] - Http service has already been stopped

2023-12-27 13:32:54.696 [WARN ] [service.internal.HttpServiceDisabled] - Http service has already been stopped
```

```
2023-12-27 13:32:49.043 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'dewpoint-7' failed: The name 'NULL' cannot be resolved to an item or type; line 183, column 35, length 4 in dewpoint

2023-12-27 13:32:49.244 [ERROR] [internal.handler.ScriptActionHandler] - Script execution of rule with UID 'dewpoint-6' failed: The name 'dEspGarag_T_Deg' cannot be resolved to an item or type; line 160, column 7, length 15 in dewpoint
```

Is there anything i can do to trace this problem down?
I would like to keep up with the latest version of openHAB but this way it is a showstopper for me

**Comment by wborn** [comment]
As a test I added a config parameter in which you can configure the network interfaces to use.

Try this [org.openhab.binding.network-4.2.0-SNAPSHOT.jar](https://github.com/wborn/openhab-addons/releases/download/network-20231229/org.openhab.binding.network-4.2.0-SNAPSHOT.jar).

You have to enable "Show advanced" to see it. Add each interface on a new line.

We could also implement a ConfigOptionProvider which would make it possible to pick the interface names in the UI similar to choosing USB devices or selecting items.

I also changed the binding to always use the last known reachable interface with arping until the device goes offline.

**Comment by SHU-red** [comment]
Thank you very much
I will be able to check it tomorrow

Can you give me a quick hint how you want me to run this jar file?

I am running a container-only-os

**Comment by wborn** [comment]
You can update it using the [Console](https://www.openhab.org/docs/administration/console.html) with:

`bundle:update org.openhab.binding.network https://github.com/wborn/openhab-addons/releases/download/network-20231229/org.openhab.binding.network-4.2.0-SNAPSHOT.jar`

To revert this use:

`bundle:update org.openhab.binding.network https://openhab.jfrog.io/artifactory/libs-release-local/org/openhab/addons/bundles/org.openhab.binding.network/4.1.0/org.openhab.binding.network-4.1.0.jar`

**Comment by SHU-red** [comment]
***What i did:***
- ssh into the  running openhab container
- entered openhab cli via `/openhab/runtime/bin/client`
- inserted `bundle:update org.openhab.binding.network https://github.com/wborn/openhab-addons/releases/download/network-20231229/org.openhab.binding.network-4.2.0-SNAPSHOT.jar` and pressed Return
- No Message or Error
- Could not find anything about "Show Advanced"  --> Restarted container
- Recognized that all of my pingdevices are now in state `UNINITIALIZED - HANDLER_MISSING_ERROR` since `bundle:update` was executed

***To sum up:***
- Already existing Things do not work anymore
- I can not add manually new things after the bundle-update
- De- and Re-Installing Network binding resolves the problem

Am i doing anything wrong?

***Additionally:***
- I de-installed the network binding
- Stopped openhab
- Re-Deployed it with the :latest-tag --> `openHAB 4.1.0 Release Build`
- High CPU load Main UI does come up after long long boot time and is very unresponsive
--> There is no way to trace the cpu load down to some sort of process right? Problem is, that all of this runs in a .jar file and has nothing to do with linux processes right?
___--> If this problem persists without a installed network-binding, it could be a completely different root cause right?___

Thank you very much for your support

**Comment by wborn** [comment]
> Could not find anything about "Show Advanced"

It's in your pingdevice config:

![image](https://github.com/openhab/openhab-addons/assets/12213581/270476ed-4799-4b79-962f-79d2e8c7bb45)

> Recognized that all of my pingdevices are now in state

Maybe it takes a while to work because your load is high so everything takes long.

> High CPU load Main UI does come up after long long boot time and is very unresponsive

If your load is high even without having the Network Binding installed you are having other issues as well. There is also https://github.com/openhab/openhab-core/issues/3976 which causes issues for Docker users with many interfaces.

**Comment by SHU-red** [comment]
> It's in your pingdevice config:
> Maybe it takes a while to work because your load is high so everything takes long.

Thats what i was guessing but as mentioned no network-thing comes up and there is only an error message on each thing-site
Pretty sure that this would not change even if i wait very long (because it is the case when using 4.0.4 where my cpu load is not unusual high)

> you are having other issues as well

Thats what i am also guessing
So first of all i will take a look into other directions than network-binding

Thank you again

**Comment by wborn** [comment]
> because it is the case when using 4.0.4 where my cpu load is not unusual high

Try it on 4.1.0 instead. There have been many dependency changes since 4.0 so add-ons created for 4.1 will probably not work with 4.0.
