### ISSUE TITLE
[boschindego] Not all http request have explicit timeout

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-addons#15507]
While refactoring some bindings to explicilty have a timeout set for http calls, boschindego was left out.

This was due to some longpoll requests that needed more investigation. Details:
_Originally posted by @jlaur in https://github.com/openhab/openhab-addons/pull/15505#discussion_r1306568446_

**Comment by jlaur** [comment]
See also #13182.

**Comment by lsiepel** [comment]
When reading issue https://github.com/openhab/openhab-addons/issues/17176 i remembered this one about the long polling. Did you ever get this fixed or some detailed logging?

**Comment by jlaur** [comment]
@lsiepel - the latest status can be found in this thread: https://community.openhab.org/t/bosch-indego-how-to-use-bosch-single-id/146299/34

Although it would be interesting to get back to the longpoll topic, in the current situation I'm not willing to invest the time, since Bosch can block us anytime, and already did so in the past. If the API would be made public and officially supported, I would be happy to pick this up.

**Comment by lsiepel** [comment]
Closing this for now as time is limited and it does not seem to be a big enough issue to invest now. Can always be reopened when needed
