### ISSUE TITLE
[googletts] Missing service configuration

### ISSUE THREAD

**Issue by Artur-Fedjukevits** [openhab/openhab-addons#15746]
## Expected Behavior

Some CommunicationException should not reset the oAuthService variable.

## Current Behavior

After some WARN like

`2023-10-13 06:15:16.652 [WARN ] [ce.googletts.internal.GoogleCloudAPI] - Error initializing Google Cloud TTS service: An unexpected IOException occurred: java.util.concurrent.TimeoutException: Total timeout 5000 ms elapsed
`

or 

`2023-10-05 09:08:16.316 [WARN ] [ce.googletts.internal.GoogleCloudAPI] - Error initializing Google Cloud TTS service: An unexpected IOException occurred: java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Buffering capacity 2097152 exceeded`

the oAuthService variable is reset to null and Google TTS returns the Missing service configuration until openHAB is restarted.

## Possible Solution
```
public byte[] synthesizeSpeech(String text, GoogleTTSVoice voice, String codec) {
        String format = getFormatForCodec(codec);
        try {
            return synthesizeSpeechByGoogle(text, voice, format);
        } catch (AuthenticationException e  ̶|̶ ̶C̶o̶m̶m̶u̶n̶i̶c̶a̶t̶i̶o̶n̶E̶x̶c̶e̶p̶t̶i̶o̶n̶ ̶e̶) {
            logger.warn("Error initializing Google Cloud TTS service: {}", e.getMessage());
            if (oAuthService != null) {
                oAuthFactory.ungetOAuthService(GoogleTTSService.SERVICE_PID);
                oAuthService = null;
            }
            voices.clear();
        } catch (CommunicationException e) {
            logger.warn("Error initializing Google Cloud TTS service: {}", e.getMessage());
            voices.clear();
        }
        return null;
    }
```

Probably like this, but I'm not sure.

## Your Environment
Version used: openHAB 4.0.3 
Environment name and version: OpenJDK Runtime Environment Zulu17
Operating System: Ubuntu 20.04.3

**Comment by jlaur** [comment]
I checked #14937, but actually this seems to be a long-standing bug:
https://github.com/openhab/openhab-addons/blob/2d92fda0f25790905b74bb3f764ee50a1607b748/bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleCloudAPI.java#L331-L338

I would suspect that `CommunicationException` should be handled differently, i.e. only `AuthenticationException` should reset OAuth2. @lolodomo, do you agree?

**Comment by jlaur** [comment]
@Artur-Fedjukevits - is anything else logged after that? E.g. "Could not synthesize text via Google Cloud TTS Service"?

**Comment by jlaur** [comment]
@Artur-Fedjukevits - can you test the fix?
- [org.openhab.voice.googletts-4.0.4-SNAPSHOT.jar](https://drive.google.com/file/d/1s_g1XnpMKN81Fr5CiY4Lkn356RHJmxP6/view?usp=sharing)
- [org.openhab.voice.googletts-4.1.0-SNAPSHOT.jar](https://drive.google.com/file/d/1E-GSiHmtNlV3q_I_YK4wT4nGJ1NPCBCe/view?usp=sharing)

**Comment by jlaur** [comment]
Some notes for future refactoring improvements:
https://github.com/openhab/openhab-addons/blob/2d92fda0f25790905b74bb3f764ee50a1607b748/bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleCloudAPI.java#L327-L340

This method is basically a wrapper for:
https://github.com/openhab/openhab-addons/blob/2d92fda0f25790905b74bb3f764ee50a1607b748/bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleCloudAPI.java#L353-L384

Outcomes:
- Line 365: `AuthenticationException`
- Line 375: Return null
- Line 381: Return null
- Line 383: `CommunicationException`

The error handling is inconsistent. The wrapper handles OAuth2 and logging, and converts exceptions into returning `null`. If already `null` because of JSON deserialization or missing response, nothing will be logged. In all cases we end throwing here:
https://github.com/openhab/openhab-addons/blob/2d92fda0f25790905b74bb3f764ee50a1607b748/bundles/org.openhab.voice.googletts/src/main/java/org/openhab/voice/googletts/internal/GoogleTTSService.java#L329-L332

Suggestions:
- `synthesizeSpeechByGoogle` should check response before calling `fromJson`. If null or empty, don't call. In this case `fromJson` will never return `null`.
- `synthesizeSpeechByGoogle` should never return null. If response is missing or cannot be deserialized, throw `CommunicationException` (or custom exception). Chain `JsonSyntaxException`.
- The wrapper `synthesizeSpeech` should only handle OAuth2 and in this case rethrow `AuthenticationException`. Don't log.
- In `GoogleTTSService` catch exceptions and rethrow as `TTSException`. Log if needed, I don't know if throwing this exception will already be logged by the framework.
