### ISSUE TITLE
[airquality] Station id can contain letters

### ISSUE THREAD

**Issue by tata-** [openhab/openhab-addons#15806]
There can be stations which contains letter in their id. On the ui it is not possible to enter such name.

Example station url:

https://api.waqi.info/feed/A355255/?token=<TOKEN>

**Comment by jlaur** [comment]
@tata- I'm not using this binding, but did a quick documentation check:
https://www.openhab.org/addons/bindings/airquality/#thing-configuration

Can you try this URL: `https://api.waqi.info/search/?token=TOKEN&keyword=NAME`, replacing TOKEN by your apiKey and NAME by the station you are looking for.

and paste the response payload here?

**Comment by clinique** [comment]
Tested, I confirm some station Id can be string instead of number, but even as a string it can be queried as number: 
In @tata- 's exemple we want to query station "A355255" : 
https://api.waqi.info/feed/A355255/?token=xxx

Current behaviour of the binding won't let you put "A355255" as stationId, instead you can put "-355255" and it will work.

As long as this workaround is possible, I would consider keeping it unchanged to avoid a breaking change.
