### ISSUE TITLE
[doorbird] Upcoming API Changes

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab-addons#15827]
@mhilbush ,  we received this email from Doorbird .   Thanks!

Hi Openhab,

Affective November 2023 there is a new “v.2” handling for encrypting/decrypting events.  Version 1 has been deprecated and will be removed in the future.  It can also be disabled by the user in the administration area of the app.

Integrations which are using Version 1 should update as soon as possible.

Please see the [updated API](https://www.doorbird.com/downloads/api_lan.pdf?rev=0.34) for additional details.

EVENT MONITORING (UDP BROADCASTS) Pages 28 – 31

**Comment by mhilbush** [comment]
Thanks @digitaldan. I'll look into it.

**Comment by mhilbush** [comment]
At first glance, this looks a positive change. The Doorbird v2 API only requires ChaCha20-Poly1305 for decrypting the event payload. And it looks like ChaCha20-Poly1305 has been part of Java since Java 11. If that ends up being true, then I should be able to get rid of the crypto library that I include with the binding.
