### ISSUE TITLE
Samsung Tv 

### ISSUE THREAD

**Issue by kylelliott** [openhab/openhab-addons#15851]
im running openhab 4.0.4 cant seem to find the jar file for the samsung tv plugin that works with my verison of openhab i can only find verison 4.1.0

**Comment by jlaur** [comment]
@kylelliott - please provide some more details so we can understand what the issue is. It doesn't look like a bug in openHAB, but more like a support request better suited for the [community forum](https://community.openhab.org/) though.

In 4.0.4 under "openHAB Distribution", I see the "Samsung TV Binding" in the list, and it works too.
