### ISSUE TITLE
[myq] Removal of binding

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#15910]
Following the ban on third party integrations, the myQ binding should be removed since it's no longer working. See:
https://chamberlaingroup.com/press/a-message-about-our-decision-to-prevent-unauthorized-usage-of-myq

See also the Home Assistant blog entry on this matter:
https://www.home-assistant.io/blog/2023/11/06/removal-of-myq-integration/

**Comment by digitaldan** [comment]
You beat me too it.  I was going to open a PR to remove MyQ since i don't think this is a game we want to continue playing (at least i don't want to) .   I'm not sure if we need to document this somewhere, or if its pretty clear at this point MyQ is done.  In any case i'll get a PR open to remove here.  

I guess we could keep the MyQ docs, but just mention the binding is no longer available for some amount of time ?
