### ISSUE TITLE
[hue] Scene channel missing

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#16014]
When reading the scene footnote here:
https://www.openhab.org/addons/bindings/hue/doc/readme_v2.html#channels-for-rooms-and-zones

I got a suspicion that I now verified: When creating a Thing for a zone or room having no scenes configured, the `scene` channel will be deleted. When a scene is then added, the channel will not reappear.

## Expected Behavior
Either the scene channel should be present always (for zone and room). Or it should be re-added when scenes are available.

## Current Behavior
The `scene` channel will be missing forever, or at least until the Thing is deleted and created again.

## Possible Solution
None yet.

## Steps to Reproduce
- Create a new zone in the Hue app (without any scenes).
- Create the corresponding Thing in openHAB.
- Observe that the `scene` channel is removed when initializing for the first time.
- Create a scene for the zone in the Hue app.
- Observe that the `scene` channel is still missing after reinitializing the Thing and even after restarting the binding.

## Your Environment
* Version used: 4.1-SNAPSHOT build 3757

**Comment by andrewfg** [comment]
I can confirm that this case is true. Currently we start a thing with all possible channels and then remove those where no data resource was provided. And it the data does arrive later the now missing channel is not restored. This certainly does apply to the case where the user may add scenes later.

Note: I can hypothetically imagine that it might also apply to other channels e.g. when a device has a firmware update that adds new capabilities .. to make a blunt example if a light would be upgraded from dimmable only to have color temperature as well. However I think in such a case it would be Ok that the user has to recreate the thing. So I would not address that issue here.
