### ISSUE TITLE
Restore on Startup not working for RRD4J with OH4.1M4

### ISSUE THREAD

**Issue by apella12** [openhab/openhab-addons#16057]
## Expected Behavior
States restored

## Current Behavior
This is mentioned in the [community under 4.1 Milestones](https://community.openhab.org/t/openhab-4-1-milestone-discussion/149502/116).  Appears to be about three confirmations. Unrestored items are NULL and (for me) about a half a dozen rules bomb.
Also as noted in the forum, the items that are NULL are items created to count reports and lights (not connected to any binding).  All my MQTT items were "restored", but I think that just happens when Mqtt is connected.

## Possible Solution
Wild guess is that some checking protocol was introduced between M3 and M4 and because not all items (Dates & Images) are managed and the new check fails and the whole restore on startup process stops?.

# Steps to Reproduce (for Bugs)
1. First encounter with upgrade from M3 to M4
2. Did setup Mapdb to restore on S/U
3. Accidently did restart before all Mapdb states were persisted
4. Several more items were not restored- So I think a simple restart on M4 should trigger it.

# Context
Rules bomb on startup

# Your Environment
  Release = Raspbian GNU/Linux 11 (bullseye)
  Kernel = Linux 6.1.21-v8+
  Platform = Raspberry Pi 4 Model B Rev 1.1
   Uptime = 61 day(s). 3:4:28
 CPU Usage = 0.75% avg over 4 cpu(s) (4 core(s) x 1 socket(s))
  CPU Load = 1m: 0.01, 5m: 0.03, 15m: 0.05
    Memory = Free: 0.30GB (17%), Used: 1.54GB (83%), Total: 1.85GB
     Swap = Free: 1.92GB (96%), Used: 0.07GB (4%), Total: 1.99GB
      Root = Free: 41.24GB (74%), Used: 14.14GB (26%), Total: 58.38GB
   Updates = 0 apt updates available.
 Processes = 154 running processes of 32768 maximum processes

**Comment by J-N-K** [comment]
I can explain the behavior, but I don't have a solution ATM. The case is indeed https://github.com/openhab/openhab-core/pull/3889, but it's not a bug there.

Before that PR no end time was set in the filter criteria when querying the most recent state. This changed because we need to get the first state before now, not the state with the biggest timestamp.

Unfortunately "begin=null" and "end=null" and "pagesize=1" has a special handling in rrd4j:

```
                    if (filterEndDate == null) {
                        // we are asked only for the most recent value!
                        double lastValue = db.getLastDatasourceValue(DATASOURCE_STATE);
                        if (!Double.isNaN(lastValue)) {
                            HistoricItem rrd4jItem = new RRD4jItem(itemName, mapToState(lastValue, item, unit),
                                    ZonedDateTime.ofInstant(Instant.ofEpochMilli(db.getLastArchiveUpdateTime() * 1000),
                                            ZoneId.systemDefault()));
                            return List.of(rrd4jItem);
                        } else {
                            return List.of();
                        }
                    } else {
                        start = end;
                    }
```

because we now have an end-timestamp, the "get last value" part is no longer executed and we don't get a valid value.

**Comment by J-N-K** [comment]
Maybe the `filterEndDate == null` check should be changed to `filterEndDate == null || Duration.between(filterEndDate, ZonedDateTime.now()).getSeconds() < 10` or something similar. `10` could be replaced by some dynamic value, like `db.getRrdDef().getStep()` or half of that.

**Comment by kaikreuzer** [comment]
Thanks for the analysis @J-N-K, I am now also back at my keyboard.
So if I get it right, the troublesome line is `start = end`, which we are now hitting - and this will simply have rrd4j return nothing. Do you actually see any situations where this setting makes any sense? If not, we might want to change this part of the code to somehow retrieve the best value at the moment of the given `end` time.

**Comment by J-N-K** [comment]
start == end is a valid selection, it selects exactly one bin, so as long as we know exactly what we want (historicState) it's correct.  

The issue only occurs if we don't know what the last valid bin is (restoreOnStartup requires "last valid value", not "value from last bin"). This special case was handled by start=null,end=null,pageSize=1. That's why I suggested to handle start=null,end=now,pageSize=1 the same way.

**Comment by kaikreuzer** [comment]
Ok, got it. So we have to identify if `end` actually means `now` and should therefore check for a small duration as per your suggestion above.

**Comment by kaikreuzer** [comment]
https://github.com/openhab/openhab-addons/pull/16059 seems to nicely address the issue.
