### ISSUE TITLE
[NETATMO] The device is not a ThermRelay (13)

### ISSUE THREAD

**Issue by GuidoTraversari** [openhab/openhab-addons#16061]
I have been using Netatmo integration to check netatmo valves and btcino netsmather thermostat. Through the thermostat card, I can control the temperature of the thermostat entity(which refers precisely to the thermostat). but if I act on the entities that control the valves the error is as follows: Invocazione del servizio climate/set_temperature non riuscita. 403 - Forbidden - The device is not a ThermRelay (13) when accessing 'https://api.netatmo.com/api/setroomthermpoint'

how can i fix it? 
![image](https://github.com/openhab/openhab-addons/assets/127422335/ff634f6a-a797-4d24-a8e4-453eb7621f4d)
![image](https://github.com/openhab/openhab-addons/assets/127422335/8d1c8d8a-7166-402e-8348-d0c191ee48ae)

**Comment by clinique** [comment]
Can you please show your configuration ?

**Comment by GuidoTraversari** [comment]
What configuration are you talking about? Consider that both the thermostat and the valves were added via integration. there is nothing textual to show you. this is a screen of one of the valves
![image](https://github.com/openhab/openhab-addons/assets/127422335/f47ccda7-7646-4c83-bf71-d4d9fca653dd)
and clicking on controls I have the image you see above. With the thermostat I have no problem (thermostat is bticino) netatmo valves are not editable! with this integration I can only read their status but not control them
![image](https://github.com/openhab/openhab-addons/assets/127422335/eb81bf9e-956b-41cf-9f77-0d9275bdc13d)
![image](https://github.com/openhab/openhab-addons/assets/127422335/b34a91c3-09a1-433c-8cee-bcfbff3a22ae)

**Comment by lacchinig** [comment]
I have the same issue, without any solution til now
I have supposed that the integration is working only with HA Cloud, because I have not that subscription
and tring to remove and reinstall the integration the only way to reinsert them is to connect the Cloud
service... but honestly I'm not sure.

2 days ago I have received the email from Natatmo:

Authentication update (second notice)
--
This is a reminder regarding our authentication update following the release initially planned for last fall which we decided to postpone in order to give our users more time. Dear Netatmo developer,
Today, when you refresh an Access Token using the associated endpoint https://api.netatmo.com/oauth2/token, the Netatmo servers respond with a pair of tokens: an Access Token and a Refresh Token.If the previous Access Token is still valid, the newly returned access token is identical but has an expiration time extended by 3 hours.The Refresh Token is not renewed.
Starting May 29, 2024, this behavior will change to comply with the OAuth2 Authorization Framework RFC recommendations (section 10.4) and improve the security of our users' data.When refreshing the tokens, the Access Token and Refresh Token will be different from the previous ones and the old tokens will be invalidated.
What does this mean for you?If you already store the tokens returned by the API when refreshing your tokens, this change will not affect you.If you do not update the tokens when refreshing them, your users will be logged out because the old tokens will be invalidated.If for a given user, you have stored the same token in different places (for example: an application and its widget), you must have a way to synchronize them because the new token will be applied for the entire application.
Sincerely,Legrand - Netatmo - Bticino

Authentication update (second notice)

 

This is a reminder regarding our authentication update following the release initially planned for last fall which we decided to postpone in order to give our users more time.

 

Dear Netatmo developer,
Today, when you refresh an Access Token using the associated endpoint https://api.netatmo.com/oauth2/token, the Netatmo servers respond with a pair of tokens: an Access Token and a Refresh Token.

If the previous Access Token is still valid, the newly returned access token is identical but has an expiration time extended by 3 hours.

The Refresh Token is not renewed.

Starting May 29, 2024, this behavior will change to comply with the [OAuth2 Authorization Framework RFC recommendations (section 10.4)](https://mailer.netatmo.com/lnk/AXEAADqA5ToAAcuzSRYAALLuE7sAAAAACjcAnClgAA8COwBl4aq5dSo2FwnzRza8_alrNZGJ6QAOzw4/1/BBjc6E7DbqNsM-8f6Q3kIg/aHR0cHM6Ly9ldXIwMS5zYWZlbGlua3MucHJvdGVjdGlvbi5vdXRsb29rLmNvbS8_dXJsPWh0dHBzJTNBJTJGJTJGbWFpbGVyLm5ldGF0bW8uY29tJTJGbG5rJTJGQkFBQUE5WjZ2Q3dBQUFBQUFBQUFBTExqNHBnQUFBQUFDamNBQUFBQUFBOENPd0JqX2NwbFZjUU4wYUE5Ulo2cVNTUm16bmozU2dBT3p3NCUyRjElMkZBSnlRT2Nra1YtdGFVQzNjTDROZUJRJTJGYUhSMGNITTZMeTkzZDNjdWNtWmpMV1ZrYVhSdmNpNXZjbWN2Y21aakwzSm1ZelkzTkRrJmRhdGE9MDUlN0MwMSU3Q3JvbWFpbi5sZS1zY291YXJuZWMlNDBsZWdyYW5kLmNvbSU3Q2NkZjllYTNkN2U5MTRlMTI1NDcxMDhkYjE5NmVkN2VlJTdDMTk5Njg2YjViZWY0NDk2MDg3ODY3YTZiMTg4OGZlZTMlN0MxJTdDMCU3QzYzODEzMTczNjA3Njc0NDc5MyU3Q1Vua25vd24lN0NUV0ZwYkdac2IzZDhleUpXSWpvaU1DNHdMakF3TURBaUxDSlFJam9pVjJsdU16SWlMQ0pCVGlJNklrMWhhV3dpTENKWFZDSTZNbjAlM0QlN0MzMDAwJTdDJTdDJTdDJnNkYXRhPXlGTjdwUUR4d3glMkYwZWlzaU9MSDByN3djMlY3MUs0RG1jeGxudGx0WkhLUSUzRCZyZXNlcnZlZD0w) and improve the security of our users' data.

When refreshing the tokens, the Access Token and Refresh Token will be different from the previous ones and the old tokens will be invalidated.

 

What does this mean for you?

If you already store the tokens returned by the API when refreshing your tokens, this change will not affect you.

If you do not update the tokens when refreshing them, your users will be logged out because the old tokens will be invalidated.

If for a given user, you have stored the same token in different places (for example: an application and its widget), you must have a way to synchronize them because the new token will be applied for the entire application.

 

Sincerely,

Legrand - Netatmo - Bticino
