### ISSUE TITLE
[knx] OH 4.1.0 KNX binding fails to send updates to contact-control items

### ISSUE THREAD

**Issue by tkuehne71** [openhab/openhab-addons#16115]
See discussion and more detailed description over here: [https://community.openhab.org/t/contact-knx-items-dont-seem-to-be-sent-with-oh-4-1-0/152298](https://community.openhab.org/t/contact-knx-items-dont-seem-to-be-sent-with-oh-4-1-0/152298)

It seems that beginning with 4.1.0 the KNX binding fails to send updates to contact-control items.

That is the case regardless if the items get updated using the postUpdate method or if the updates are supposed to happen via channel-linking through items that get updated via another binding's channel.

**Comment by J-N-K** [comment]
@holgerfriedrich Can you have a look?

**Comment by holgerfriedrich** [comment]
I will have a look.

Btw: the link above does not work for me unless I copy the link text.... Could you pls check?

**Comment by tkuehne71** [comment]
The issue with the link seems to be fixed. Thanks, jlaur.

At least one other person has reported a similar issue with their setup in the thread.

Best,

Tom

**Comment by holgerfriedrich** [comment]
Lets first look at ```switch``` for comparison:
Things of type ```switch``` and ```switch-control``` send to KNX when ```sendCommand()``` is called, and switch-control also on ```postUpdate()```. If I set profile=follow on the item for switch, it responds to ```postUpdate()``` as well.
For me this looks like expected behavior.

For things of type ```contact``` and ```contact-control```, the framework forbids ```sendCommand()``` with values OPEN or CLOSED, only REFRESH is allowed. ```postUpdate()``` does not send to the bus for ```contact```.
This is also what I would expect.

=> What seems to be missing, is sending to KNX on ```postUpdate()``` for ```contact-control```.

@J-N-K I think I need you help on this. I just do not see the missing piece, can you point me the the place where the binding registers for to data from ```postUpdate```? Or is core at them moment preventing this data to be sent to the binding for ```contact```?
