### ISSUE TITLE
[ipcamera] camera not working after upgrade to 4.1

### ISSUE THREAD

**Issue by TimmiORG** [openhab/openhab-addons#16154]
I upgraded my openhab installation from 3.4.0 to 4.1.0.
This caused my IP cameras to work.
They are kind of hikvision clone.

## Expected Behavior
IP camera is working

## Current Behavior
IP Camera is not leaving "initialization" state

```
2023-12-30 22:01:50.025 [DEBUG] [era.internal.handler.IpCameraHandler] - About to connect to the IP Camera using the ONVIF PORT at IP: 192.168.0.34:8000
2023-12-30 22:01:50.027 [DEBUG] [amera.internal.onvif.OnvifConnection] - Connecting 192.168.0.34 to ONVIF
2023-12-30 22:01:50.028 [TRACE] [amera.internal.onvif.OnvifConnection] - Sending ONVIF request: GetSystemDateAndTime
2023-12-30 22:01:50.030 [TRACE] [amera.internal.onvif.OnvifConnection] - Sending ONVIF request: GetCapabilities
2023-12-30 22:01:50.046 [DEBUG] [g.ipcamera.internal.onvif.OnvifCodec] - Exception on ONVIF connection: Connection reset
2023-12-30 22:01:50.047 [TRACE] [g.ipcamera.internal.onvif.OnvifCodec] - Other ONVIF netty channel event occurred: io.netty.channel.socket.ChannelInputShutdownReadComplete@ce82d6
2023-12-30 22:01:50.054 [DEBUG] [g.ipcamera.internal.onvif.OnvifCodec] - Exception on ONVIF connection: Connection reset
2023-12-30 22:01:50.056 [TRACE] [g.ipcamera.internal.onvif.OnvifCodec] - Other ONVIF netty channel event occurred: io.netty.channel.socket.ChannelInputShutdownReadComplete@ce82d6

```
Happy to share more information if needed

## Context
IP Cams are not working any more

## Your Environment

* Version used: 4.1.0 release
* Operating System and version: Raspbian 11

**Comment by Skinah** [comment]
As a work around set the onvif port to 0. This will stop onvif connecting which is where the issue seems to be. You should only loose PTZ features. I am not able to look at this for a week, so after that I may need to add some code in to give more logging for you to run to narrow it down.

**Comment by Skinah** [comment]
The other thing that would help is to try older versions to see around what time it broke. Install the telstick binding to take care of the dependacies and uninstall the merged binding, then you can just swap the jar files into the addons folder.

https://pcmus.com/openhab/IpCameraBinding/OldVersions/

I suspect it is going to be the binding now sends two onvif messages at the same time instead of only one at a time. I do not believe the messages are any different.

**Comment by TimmiORG** [comment]
Hi @Skinah 
the onvif port to 0 is getting the cam online. Need to check if it is still working as expected.

I can see that there are two messages send to the cam before. Both to /onvif/device_service
1.  GetSystemDateAndTime
2. GetCapabilities

**Comment by Skinah** [comment]
I have looked into this some more and the onvif messages did not change and before 4.1 there were at times three messages sent in parallel by the binding so having two fail is unlikely due to being done at same time. The connection reset error means the camera or your network has shut the connection down. Could this be due to using it inside a container or another reason the network traffic is blocked? No one else has reported it so far with the exact same error.

**Comment by TimmiORG** [comment]
No I'm not using any container. There should not be anything blocking this as well. I don't need onvif on the cams. But it was working in openhab 3.6. That is why I reported it.

**Comment by Skinah** [comment]
In 3.6 if the onvif failed to connect it would not have stopped the camera coming online. Now the binding is working differently at detecting the online and offline states using onvif. It is possible the camera never worked as nothing at the onvif messages changed. As stated the only reason to have the onvif is so you can move a camera, the rest can still work if you manually supply the urls or if the thing type is a brand with an api, the binding knows the urls already. I think the work around is all that is needed unless you try the camera with a 3rd party app like Onvif device manager and it works in that app but not with the binding. Can you do that test to see if it works in ODM?

**Comment by TimmiORG** [comment]
hm...
OK than we can close the ticket as invalid as it sounds like a configuration mistake in the past. So there should not be a onvif configuration in first place. 

Sorry for bothering you.
