### ISSUE TITLE
[systeminfo] Wrong CPU Temperature

### ISSUE THREAD

**Issue by alaub81** [openhab/openhab-addons#16334]
## Expected Behavior
Item should show the same CPU Temperature as the official command:
```bash
vcgencmd measure_temp 
```
And also to
```bash
cat /sys/class/thermal/thermal_zone0/temp
```

## Current Behavior
Item's CPU Temperature is different to the one I get with `vcgencmd measure_temp`.
for example:
command Temp: 47.2'C
Item Temp: 54.9'C

## Possible Solution
Perhaps the way to get the temperature is different to `vcgencmd measure_temp` or `cat /sys/class/thermal/thermal_zone0/temp`

**Would like to know how the binding is reading the cpu temperature.**

## Steps to Reproduce (for Bugs)
Create a Systeminfo CPU Temperature  Item. Checking the temperature there and compare it with `vcgencmd measure_temp`

## Context
Wrong data is showing.

## Your Environment
openHAB 4.1.1 docker setup on a Raspberry Pi 5. Perhaps the problem is Pi5 related.

**Comment by mherwege** [comment]
The systeminfo binding uses the OSHI library. It should use the `vcgencmd` on an RPi, see https://github.com/oshi/oshi/blob/fd6b88ab778feaf3c6a1d40aca598028a199ece0/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java#L155. What is the full output ofcthe `vcgencmd`? I am wondering if it doesn’t start with `temp=` on an RPi 5.

**Comment by alaub81** [comment]
The Output is with `temp=`

I am using the docker image of openhab. There is no `vcgencmd` installed, so I am not able to execute it within the container.

Or am I wrong, that it is executed directly in the container?

**Comment by mherwege** [comment]
Looking at that code, it may indeed be that your device is not recognized as a PI as you are running this in docker.
I saw somewhere they created the special code for PI’s because there was an issue when other external sensors were attached through e.g. onewire. You don’t have other temperature sensors attached to the PI?

**Comment by alaub81** [comment]
No, there are no one-wire sensors connected. 
I do not know, where the wrong input is comming from. Which other methods are used to get the cpu temperature? Only the two?
If the binding uses the output of `/sys/class/hwmon/hwmon0/temp1_input` everything should be fine, but it seems like it doesn't.

**Comment by alaub81** [comment]
I think I found the problem. It is using the temperature of `/sys/class/hwmon/hwmon1/temp1_input`

I do not know which temperature this is, but it is not the one of `vcgencmd`

**Comment by mherwege** [comment]
See https://github.com/oshi/oshi/issues/1023 (and other linked issue). It very much like the workaround created for the PI does not work from docker.

**Comment by mherwege** [comment]
> /sys/class/hwmon/hwmon1/temp1_input

It should use the output of `/sys/class/therma:/thermal_zone0/temp`, see here: https://github.com/oshi/oshi/blob/fd6b88ab778feaf3c6a1d40aca598028a199ece0/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java#L57

I am running OH on an RPi 4, but without docker. Both `vcgencmd measure_temp` and `/sys/class/therma:/thermal_zone0/temp` give me the same temperature as the binding does.  `/sys/class/hwmon/hwmon1/temp1_input` does not exist.
This confirms the issue is very specific to the dockers setup.

As the `vcgencmd` does not exist inside your docker container, I would think `/sys/class/therma:/thermal_zone0/temp` is used. Can you run `cat /sys/class/therma:/thermal_zone0/temp` inside the docker container? From the code, it is doing a normal file operation on the file.

**Comment by mherwege** [comment]
It should be using `hwmon0`, see https://github.com/oshi/oshi/blob/fd6b88ab778feaf3c6a1d40aca598028a199ece0/oshi-core/src/main/java/oshi/hardware/platform/linux/LinuxSensors.java#L96. Reading the code, if `vcgencmd` is available, the value from it should be use, if not, it will use `cat /sys/class/hwmon/hwmon0/temp1_input`, and if that is not available `cat /sys/class/thermal/thermal_zone0/temp`.
All of that works on my RPi 4.

Why do you think it uses the output of `hwmon1`? According to the code, that would happen if `/sys/class/hwmon/hwmon0` is not a directory, if it does not find a file with name starting with `temp` and ending with `_input` or the first value in that file is not an integer. You can check any of these to verify.

Note that the code for OSHI is outside of the binding. The OSHI library is used and no further manipulation of the output is done in the binding. If the wrong result is returned, the issue should be created with the OSHI library (and link this issue).

**Comment by alaub81** [comment]
> Why do you think it uses the output of hwmon1? 
Just because of the same temperatures.

I never tested it on my Pi 4, but I think it worked there also. 

Thank you for your help. We should close this issue. I will have a look at the issues of OSHI Library.
