### ISSUE TITLE
[boschshc] Possible security issue

### ISSUE THREAD

**Issue by jlaur** [openhab/openhab-addons#16459]
See https://github.com/openhab/openhab-addons/security/dependabot/49

**Comment by jlaur** [comment]
@GerdZanker, @david-pace - can you assess if this vulnerability affects the binding?

**Comment by GerdZanker** [comment]
The Bosch SHC code uses ``org.bouncycastle bcpkix-jdk15on 1.70`` which contains https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-33201.

> The vulnerability only affects applications that use an LDAP CertStore from Bouncy Castle to validate X.509 certificates.

The bouncycastle code in boschshc is used to create a JavaKeyStore, a key pair and self signs a certificate with the keypair. Additionally it provide public certs from SmartHomeController for the store.

Therefore the boschshc code is not affected from my point of view, because
* it doesn't use the class ``X509LDAPCertStoreSpi``, mentioned in https://github.com/openhab/openhab-addons/security/dependabot/49
* it doesn't use an LDAP CertStore
* it doesn't validate other X.509 certificates

**Comment by david-pace** [comment]
I also think the binding is not affected since we don't use any LDAP cert store.

But probably it would still be a good idea to upgrade the `org.bouncycastle` dependencies. In our case we should evaluate whether we can upgrade

* `bcpkix-jdk15on:1.70`
* `bcutil-jdk15on:1.70`
* `bcprov-jdk15on:1.70`

to

* `bcpkix-jdk18on:1.77`
* `bcutil-jdk18on:1.77`
* `bcprov-jdk18on:1.77`

**Comment by jlaur** [comment]
@GerdZanker - many thanks for the analysis!
