### ISSUE TITLE
[solarforecast] Binding polls remote api every minute when it receives a http error

### ISSUE THREAD

**Issue by pre-martin** [openhab/openhab-addons#16811]
## Expected Behavior

Tested only with ForecastSolar!

When the "Refresh Interval" for a plane is set to 30 minutes, I expect the binding to not poll faster than in a 30 minutes interval.

## Current Behavior

The binding receives `HTTP/1.1 429 Too Many Requests` from the ForecastSolar api (not yet sure, why. IMHO there is another problem in the binding). After that, the binding polls the api every minute (!) instead of waiting some time (the configured 30 minutes?).

## Possible Solution

In the constructor of the PlaneHandler, the binding creates a [forecast object with expiration in the past](https://github.com/openhab/openhab-addons/blob/4.2.0.M3/bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/forecastsolar/handler/ForecastSolarBridgeHandler.java#L75). The BridgeHandler then calls `fetchData()` every minute. As the forecast is expired, the binding is forced to call the remote api, which responds with an error. But only for a response code of 200, [the expiration is set to a new value](https://github.com/openhab/openhab-addons/blob/4.2.0.M3/bundles/org.openhab.binding.solarforecast/src/main/java/org/openhab/binding/solarforecast/internal/forecastsolar/handler/ForecastSolarPlaneHandler.java#L151). For every other response (429 in this case), the expiration stays in the past and the handler will execute the same code just one minute later.

## Steps to Reproduce (for Bugs)

1.
2.

## Your Environment

* Version used: 4.2.0.M3
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): Java 17 - unimportant
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Windows 11 - unimportant

**Comment by pre-martin** [comment]
@weymann I think that the binding has to distinguish between "some error" (in this case it should be okay to try again after 1 minute) and "429 - too many requests" (in this case the binding must wait much longer).

**Comment by weymann** [comment]
> When the "Refresh Interval" for a plane is set to 30 minutes, I expect the binding to not poll faster than in a 30 minutes interval.

Forecasts are expiring after given `refreshInterval`. In _normal operation_ when everything is fine this will fit 100%
In error cases the  binding is trying to provide a new forecast as early as possible. This shall fit to cases like

- forecast.solar server is down e.g. for maintenance
- Network connection lost
- Internal server errors

> "429 - too many requests" (in this case the binding must wait much longer).

True, I see this is a special problem.
In the past the service was _more tolerant_ and getting ONLINE even if there were additional requests answered with 429. Now as documented in [forecast API](https://doc.forecast.solar/facing429) binding needs to wait at least 1 hour regadless of given `refreshInterval`.

As you suggest I would handle http status 429 in a special way and reject all updates for the complete site in order to obey the API description.

**Comment by pre-martin** [comment]
The linked API spec says "should". So I assume that this is a safe value for which you can be sure, that the next request will be successful (related to the request limit).

As the binding does not keep a history about the number of calls made in the past hour, I guess that you should really wait one hour. Otherwise you would have to implement the history and calculate by yourself, when the request limit *could* be over - IMHO too complicated for this use case.

**Comment by weymann** [comment]
> you should really wait one hour.

As it's done in the PR #16819
