### ISSUE TITLE
[systeminfo] Handler factory not found

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#16965]
Updated to newest snapshot (4148) and now I'm getting "Handler factory not found" on my systeminfo thing.  Had no issues with the snapshot I was on (about a month old).  No errors are being thrown.  I've cleared cache and no effect.  All other bindings are working as expected.

**Comment by mherwege** [comment]
Probably caused by https://github.com/openhab/openhab-addons/pull/16838

@falkena Could you have a look at this?

Do you have binding startup logs? What if you remove and recreate the thing?

My hunch is that the change in name of the dynamically created thing type is the cause of this. The previously created thing type retrieved from storage at startup does not match the thing type that gets created after the change PR.

**Comment by mherwege** [comment]
Confirmed in the forum.

This is a widely used binding, so I don’t think asking users to relink all items to a newly created thing is acceptable. I don’t know much about upgrade instructions, but I doubt they can be used here (the original dynamic thing typename depends on the hostname).
So unless some logic is build to automatically convert the old dynamic name to the new one inside the handler, I think the PR should be reverted.

**Comment by mherwege** [comment]
Reverting https://github.com/falkena/openhab-addons/blob/3edea3c45ca81c08cb8f400e93e33b59c91beb02/bundles/org.openhab.binding.systeminfo/src/main/java/org/openhab/binding/systeminfo/internal/SystemInfoHandlerFactory.java#L51 may be enough to make it work again. I can’t test at the moment.

**Comment by morph166955** [comment]
I attempted to rebuild the thing and it didn't help (same error on the new thing).  There were no regular messages when I started up, the debug log of the binding starting is too long to post.

**Comment by morph166955** [comment]
Just to note, updated to S4166 and this is confirmed as resolved.
