### ISSUE TITLE
[energidataservice] Suggest to provide actions as core base class

### ISSUE THREAD

**Issue by weymann** [openhab/openhab-addons#17434]
**Proposal**
The binding provides _Thing Actions_ in order to calculate best prices for a dynamic tariff. In principle every binding providing such data shall have the same calculations too. E.g. Tibber, aWATTar, Entso-E, ... 
In order not every binding developer is doing his own calculations a base class would be helpful.

**Idea**
Just my first thoughts:
Provide `BaseTariffActions` with the implemented Actions. This base class shall be updated with the latest `TimeSeries` of spot prices as basis for the calculations.
Honestly I don't like the two seperate lists of `duration` and `power phases` so maybe it's possible to combine it in a `TreeMap` with `startingMinute` and `power`. As an additional option a well defined JSON may also fit.

**Thinking further**
Imagine Things like _Shelly Plug_ which are attached to e.g.. laundry or dishwasher can provide such power curves in actions too. So I can get a common power curve for my device and directly feed it to my dynamic tariff provider.

Feel free to place your comments and thoughts. If you're too busy I'm really interested to design and implement a first version and we can do it together as joint work.

**Comment by jlaur** [comment]
@weymann - thanks for starting this discussion, for your suggestion and for you willingness to join such an effort. Since this should be solved in core, I'm closing the issue for Energi Data Service here in the addons repository. A few references for you:
- openhab/openhab-core#3478 - this is where the discussion should be continued. Please read through the whole discussion where Kai already drafted an architecture.
- https://github.com/openhab/openhab-addons/pull/17169#issuecomment-2264887486 - a recent discussion (also to be continued in the core issue)
- Just say to say: I agree with the approach even before finally contributing the Energi Data Service binding: https://github.com/openhab/openhab-addons/blob/6c77b16193e3e0df1efbeeff46e241ed27590ca2/bundles/org.openhab.binding.energidataservice/src/main/java/org/openhab/binding/energidataservice/internal/PriceCalculator.java#L37-L48

**Comment by weymann** [comment]
I agree to close this topic in addons repo.
But ahh no!!! Just reading a glimpse of [this thread](https://github.com/openhab/openhab-core/issues/3478) makes me sick!
Everybody is seeking for the _holy grail of HEMS_ but I just want to know the best price. No more, no less!

And this should be the [seperation of concerns](https://en.wikipedia.org/wiki/Separation_of_concerns). I don't want to implement an HEMS, just give me the price!
