### ISSUE TITLE
[wiz] Support suggested addons

### ISSUE THREAD

**Issue by ccutrer** [openhab/openhab-addons#17847]
The WiZ discovery packet requires IP address and MAC address, but the latter needs to be added to IpAddonFinder in core first.

**Comment by andrewfg** [comment]
@ccutrer can you please provide info about the wiz discovery mechanism and syntax?

**Comment by andrewfg** [comment]
> WiZ discovery packet requires IP address and MAC address

I am not sure what you mean. What IP address and what Mac address? You obviously don't know such details of a yet-to-be-discovered device until you have actually discovered it. From what I can tell from your thing discovery code, you find those things by sending a multicast ping on a specific multicast address and port. And if either a) the multicast ip and port, and/or b) the multicast ping payload, are unique to wiz then ANY response is an indication that the addon shall be suggested. In other words, in order to simply suggest the addon you do do not need to parse any ip or mac addresses from anything. After the binding has been installed, the normal thing discovery process (which you have coded already) will dig in further to find the respective details of all those things.  

If the above is the case, then the govee example might help you; note the Regex `.*` indicates that ANY response is enough to suggest the binding..

https://github.com/openhab/openhab-addons/blob/2e7f0e061c096abc3acbaadc4ea7afc0e7503ca9/bundles/org.openhab.binding.govee/src/main/resources/OH-INF/addon/addon.xml#L11

**Comment by andrewfg** [comment]
Or are you referring to the OH IP and Mac addresses? If so, then I can easily add the latter.

**Comment by ccutrer** [comment]
> What IP address and what Mac address?

The IP Address and MAC address of _openHAB_. Cause yes, all that the add-on finder needs to know is that _any_ packet returned, so the `*` regex is perfect for the response. But the question is WHICH IP address to use on a multi-homed machine. Right now the WiZ binding uses [NetworkAddressService.getPrimaryIpv4HostAddress](https://github.com/openhab/openhab-core/blob/4.3.0.M4/bundles/org.openhab.core/src/main/java/org/openhab/core/net/NetworkAddressService.java#L33), and then iterates through `java.net.NetworkInterface.getNetworkInterfaces` to find the one one that matches that, and gets its MAC address. But _why_ does a WiZ device need to know the MAC address of a controlling device?? And doesn't it just use the IP address of the socket it received the packet on?? I highly suspect the IP address and MAC address in the discovery packet don't actually matter, but I need to do more testing. My own WiZ devices lives on an IoT VLAN, which is not the one openHAB considers my primary network interfaces, so discovery doesn't even work for me. I need to get discovery sorted in that scenario first before I can understand the process further, and get it working with add-on finder.
