### ISSUE TITLE
[wiz] No Brightness or Power On/Off for Full Color/White bulbs

### ISSUE THREAD

**Issue by kamakazie2** [openhab/openhab-addons#17912]
With the new Wiz Binding in 4.3 the Full Color/Tunable White bulb does not have a way to control the brightness for the white modes.

The prior 3rd party add in had power/brightness channels.

Im expecting to use the power state channel to turn on and off the bulb in the last state it was on

I am expecting the brightness channel to control both color and white. Using just the color channel does not allow me to activate the white leds. The only way to activate White currently is to use the Light Mode Warm or Cool white, any attempt to dim the light with the color channel puts it in color mode.

I use this function to dim my lights when they are in warm white mode.

The current work around it to use the Night Light scene for now but that is only warm white.

**Comment by jlaur** [comment]
@ccutrer - FYI. In general I think you should be able to link `Dimmer` and `Switch` to the `color` channel, and for example use a `Dimmer` item to control brightness. But it seems like things might be a bit more complicated if the bulbs can have different modes?

**Comment by ccutrer** [comment]
This is expected behavior. You absolutely CAN send an ON or OFF command to a brightness and/or color channel and it will turn on to the last brightness and color (or color temperature), or a brightness (percent) only command to a color channel. I do this every day with my RGB+CCT bulbs. This is in accordance with openHAB guidelines: https://www.openhab.org/docs/developer/addons/faq.html#modelling-channels, and was mentioned both in the [PR](https://github.com/openhab/openhab-addons/pull/17681), and less directly [in a community post referencing that WiZ is now part of main distribution](https://community.openhab.org/t/wizlighting-binding-4-0-0-0-4-3-0-0/148164/23).

**Comment by kamakazie2** [comment]
Outstanding! Ill try when i get home thanks for the fast support!

**Comment by ccutrer** [comment]
So note that there's two (and a half) ways to do this. The closest to how you likely had things set up before is to just link additional Switch and Dimmer items to the color channel (or Switch to the brightness channel). The second (which is what I use) is to only have a Color item, and just have any rules send ON/OFF and percent commands even though it's a Color item. The "half" is because in BasicUI you can also link switch and slider controls to Color items, which is basically the same thing. Depending on how you use BasicUI there can also be ways to send an ON command to a slider (at least on Android). Just play around and see what works for how you have UIs set up. Just know that under the hood, the binding processes an ON/OFF command the same regardless of if it's addressed to a color, brightness, or state channel.

**Comment by kamakazie2** [comment]
Works perfectly! Thank you for the clarification.
