### ISSUE TITLE
[vitotronic] Thing oilburner is not discovered in Discovery Service

### ISSUE THREAD

**Issue by armintan** [openhab/openhab-addons#3205]
## Expected Behavior
All Things are discovered in the discovery service, but the thing with type oilburner

## Current Behavior
Things with type oilburner not discovered

## Possible Solution
enhance method addThing() in VitotronicDiscoveryService

## Context
I can't use the binding, since I have a Viessman Vitotronic with an oilburner 

## Your Environment

* Version used: openhab2
* Environment name and version: Java 8):
* Operating System and version (openhabian):

**Comment by Hotte37** [comment]
My Oilburner is also not discovered.

I see the oilburner is still missing in VitotronicDiscoveryService.java. @steand can you fix this? Unfortunately i don't know how to build it for OH2.

```
    private void addThing(ThingUID bridgeUID, String thingType, String thingID) {
        logger.trace("Adding new Vitotronic thing: {}", thingID);
        ThingUID thingUID = null;
        switch (thingType) {
            case VitotronicBindingConstants.THING_ID_HEATING:
                thingUID = new ThingUID(VitotronicBindingConstants.THING_TYPE_UID_HEATING, bridgeUID, thingID);
                break;
            case VitotronicBindingConstants.THING_ID_PELLETBURNER:
                thingUID = new ThingUID(VitotronicBindingConstants.THING_TYPE_UID_PELLETBURNER, bridgeUID, thingID);
                break;
            case VitotronicBindingConstants.THING_ID_STORAGETANK:
                thingUID = new ThingUID(VitotronicBindingConstants.THING_TYPE_UID_STORAGETANK, bridgeUID, thingID);
                break;
            case VitotronicBindingConstants.THING_ID_CIRCUIT:
                thingUID = new ThingUID(VitotronicBindingConstants.THING_TYPE_UID_CIRCUIT, bridgeUID, thingID);
                break;
            case VitotronicBindingConstants.THING_ID_SOLAR:
                thingUID = new ThingUID(VitotronicBindingConstants.THING_TYPE_UID_SOLAR, bridgeUID, thingID);
                break;
        }
```

**Comment by Hotte37** [comment]
@Sbried i saw that you included a gasburner thing. As far as i can see, your commit was not merged in. Did you manage to build this addon and include it in openhab?

**Comment by Sbried** [comment]
@Hotte37 yes, I have the vitotronic addon built and running since August last year. As I added some things/channels and corrected some typos it will only run together with my [optolink adapter](https://github.com/Sbried/optolink/tree/feature/Add_URL_communication_capabilities_to_the_optolink). there were some discussions about the not given backwards compatibility. Finally they seemed to clarified but it was not merged into the vitotronic addon.
If you want the jar please let me know.

**Comment by steand** [comment]
I need also the channels for the burners. Otherwise it will not work. 
Can your give me Information about?
1. What your changes are in: https://github.com/Sbried/optolink/blob/feature/Add_URL_communication_capabilities_to_the_optolink/src/main/resources/optolink.xml
For this is the best way you make a pull request with a new optolink.xml (like: optolink_gasburner.xml) at https://github.com/steand/optolink
2. Maybe what you need in: https://github.com/openhab/openhab2-addons/blob/master/addons/binding/org.openhab.binding.vitotronic/ESH-INF/thing/thing-types.xml
Normal this 1:1 from optolink.xml

Thanks.

**Comment by Hotte37** [comment]
I am quite happy with the channels of the oilburner. I only need the thing "oilburner".

My wish is to extend the thing "storagetank" with the channel "charging pump". "charging pump" and "circuitpump" should belong to storage tank.

I have a optolink.xml for a Vitotronic V200KW2 burner. I will make a pull request for optolink_V200KW2.xml.
At the moment i use the pelletburner and mapped the channels (e.g. ontimelevel1 -> ontime). This means i put the oildburner adresses into the pelletburner channels. Before i pull my file, i want to delete the pelletburner and test the oilburner.

**Comment by matze025** [comment]
The oilbruner ist still not regognized.

@Hotte37  It would be cool if you could share your config so I can compare.

**Comment by hmerk** [comment]
closed due to inactivity
