### ISSUE TITLE
[zway] Remove use of `linkRegistry` OSGi Service Tracker (ItemChannelLinkRegistry)

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-addons#3402]
We don't want bindings to access these services directly (see eclipse/smarthome#5182). Therefore PR eclipse/smarthome#5244 has started with encapsulating the `ItemChannelLinkRegistry` to the `ThingHandlerCallback`.

It has to be removed in the Z-Way Binding to fulfill the new ESH API.

https://github.com/openhab/openhab2-addons/blob/48d87768b3c49e28e3b4f12596e52227fd1ec515/addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/handler/ZWayDeviceHandler.java#L117
https://github.com/openhab/openhab2-addons/blob/48d87768b3c49e28e3b4f12596e52227fd1ec515/addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/handler/ZWayDeviceHandler.java#L166
https://github.com/openhab/openhab2-addons/blob/48d87768b3c49e28e3b4f12596e52227fd1ec515/addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/handler/ZWayDeviceHandler.java#L384
https://github.com/openhab/openhab2-addons/blob/48d87768b3c49e28e3b4f12596e52227fd1ec515/addons/binding/org.openhab.binding.zway/src/main/java/org/openhab/binding/zway/handler/ZWayDeviceHandler.java#L413

@pathec, @Wire82 May I ask for your help?

**Comment by kaikreuzer** [comment]
Oops, I was a bit too quick with releasing the ESH changes to openHAB - this issue now breaks the build, see https://openhab.ci.cloudbees.com/job/openHAB2-Bundles/321/console.

@cweitkamp As long as we do not have any feedback from @pathec, do you see any simply, not too intrusive way of removing this dependency?
It seems that the handler illegally gets hold of linked item names in order to manage remote subscriptions on the Z-Way server... Not sure what will break if we simply remove that...

**Comment by cweitkamp** [comment]
Without any knowledge about what the ZWay API does with the linked item name I cannot say what will happen if we remove those lines of code completely.

I currently can think of one very easy way to fix the build without introducing a regression into the ZWay Binding. But this way is not the way we want to go. The idea is to subscribe the binding to the `ItemChannelLinkRegistry` OSGi Service and pass it to the handler through the constructor.

A second solution could be to pass something else instead of the item name e.g. the label of the channel.

**Comment by Wire82** [comment]
If I understand it correct, the zWay binding needs the OpenHab name to update the OpenHab item via the REST API if the state within zWay changes. 
It registers the names within zWay via the OpenHab connector. See below:

![grafik](https://user-images.githubusercontent.com/17042631/38197946-e73011c2-368a-11e8-9405-a257611b395a.png)

@pathec Correct me if I'm wrong. I'm not familiar with the OpenHab Connector.

So for the binding we need to know the OpenHAb item name which is linked to the zWay Channel within the binding. 

![grafik](https://user-images.githubusercontent.com/17042631/38197909-c27a5158-368a-11e8-962a-5d1a85d6fe17.png)

Any idea how to solve this?

**Comment by pathec** [comment]
@Wire82 you're right. The openHAB connector needs the item name and updates the state of the items with the REST interface: `PUT /rest/items/{itemname}/state`.

**Comment by kaikreuzer** [comment]
> As we have currently a broken build, I would suggest to simply comment out Zway from the build for the time being.

FTR: https://github.com/openhab/openhab2-addons/pull/3442

**Comment by Wire82** [comment]
@kaikreuzer Do you see any other solution for this issue? I don't know if currently anyone is able to do this change. For me this looks like a major change of the binding.
As I will not have time and also the knowledge to do this, it completely relies on @pathec to do this.
To be honest I also think it is not a good solution for the community to simply kill the binding. Many people use this binding to get their smart home running. 
As my own experience has shown the integrated Z-Wave binding of OpenHab is not an option for a lot of people.
We should maybe think of something like "grand father rights" for bindings there experience has shown that they are working well and don´t cause any issues.
For a product which bases on the community and the power of people spending days or weeks of developing bindings at home it could be a feasible solution.
So what you and the rest of the developer think?

**Comment by pathec** [comment]
@kaikreuzer Can you explain the approach with the servlet? Is it possible to subscribe to events from openHAB, for example when new items are created? New items related to Z-Way binding could be sent to Z-Way. That's what the binding is doing now.

Alternatively, **WebSockets** could be used. Z-Way offers possibilities for this. The binding would then only update the channels of its things when corresponding events occur via WebSockets. A significant disadvantage at the moment would be that there is no authentication for WebSocket. For the internal network e.g. on a RaspberryPi with openHAB and Z-Way this is certainly no problem. However, the WebSocket port of Z-Way should not be shared. I am unsure whether this is a use case for binding across network boundaries to link Z-Way and openHAB.

As a **very short-term solution**, I can offer to remove the critical code and use periodic polling at the moment.

A somewhat complicated solution would be the use of **MQTT**. There is a corresponding extension for Z-Way. This sends an update via MQTT, but the items must then be named according to a certain pattern. This in turn requires the manual creation of items and the corresponding naming.

**Comment by kaikreuzer** [comment]
@Wire82 We are definitely not killing the binding - it is part of the 2.2 release and it will be part of the 2.3 release; we are only talking about a (agreed, very unfortunate) temporary measure as the current code simply broke the build (due to more strictly checked APIs in ESH).

>  Is it possible to subscribe to events from openHAB, for example when new items are created?

As mentioned: Binding must not know about specific items. All they should need to know is which of their channels are used (by having linked items). This information is provided to the handler through calls to the `ThingHandler.channelLinked`and `ThingHandler.channelUnlinked` methods, so this is what you want to react upon.

> Alternatively, WebSockets could be used

Websockets would indeed be the preferred way (much better than MQTT) as there wouldn't be a need for an additional servlet and it is much easier to get events from Z-Way. I would tend to say that no authentication is acceptible here (does Z-Way plan to add that feature for websockets in future?).

> As a very short-term solution, I can offer to remove the critical code and use periodic polling at the moment.

That would be great to have as a quick solution for the time being!

**Comment by cweitkamp** [comment]
This issue was closed with PR #3474. Wasn't it?
Or shall we keep it for the following PR with an updated implementation by WebSockets.

**Comment by davidgraeff** [comment]
Can this be closed?

**Comment by hmerk** [comment]
closed due to inactivity
