### ISSUE TITLE
[samsungtv] err_connection_refused

### ISSUE THREAD

**Issue by Saraphie** [openhab/openhab-addons#4289]
## Expected Behavior
I should be able to switch power or source on my Samsung UE55JU6850U 

## Current Behavior
OpenHAB2 found my TV and is correctly showing if it is "online" or "offline". I'm able to change volume or mute it via simple items. But as I try to switch it power off or change the source it's not shown as "online" but as "err_connection_refused"

## Context
I'm not sure if this is due the mentioned lack of support for models after 2013.
I was optimistic as it was discovered and some features are working.

## Your Environment
* Version used: latest as of 27.11.2018
* Operating System: OpenHABian 1.4.1

## Notes
I had no time yesterday to do it and I'm currently not at home, but I can add logs or reports later today. Some help how I get them would be nice, as I'm pretty new to the OpenHABian and OpenHAB2 thing ;)

**Comment by Cossey** [comment]
The volume and mute will work on most Samsung TVs since they operate via UPnP but all other functionality works over the Remote Control API. 

Give the most recent add-on linked in Pull Request 4169 a go to see if it works for you. If it does then post in the thread your model no and release year. 

Just note that if you have a TV like mine from 2017/2018 with the latest firmware update this may not work for you due to recent changes made to the Remote Control API.

**Comment by arjanmels** [comment]
@Saraphie A PR has just been merged which may address your issues. You can try the latest snapshot built (tomorrow) or  try the jar I uploaded to: [org.openhab.binding.samsungtv-2.5.0-SNAPSHOT.jar](https://drive.google.com/open?id=1BAg5Xs1UtuZi61p5FpXjVJGWV31-HLK8)

**Comment by hmerk** [comment]
closed due to inactivity
