### ISSUE TITLE
[mqtt] Manage the things offline/online with availability_topic for HomeAssistant MQTT Thing

### ISSUE THREAD

**Issue by lucacalcaterra** [openhab/openhab-addons#4863]
## Expected Behavior

Reflect the online/offline things with a an online/offline MQTT message to availability_topic of HomeAssistant MQTT Bridge

## Current Behavior

Current version of binding not take care about availability of things create with this binding, even the payloads are defined 
## Possible Solution

Fix the code managing the MQTT messages on the availability_topic (online/offline)
## Your Environment

Openhab 2.4 running on Windows, Linux and Raspberry (various instance); same issue.

**Comment by jochen314** [comment]
@lucacalcaterra: Can you please report back, if this is fixed for you now?

**Comment by lucacalcaterra** [comment]
> @lucacalcaterra: Can you please report back, if this is fixed for you now?

ASAP i'll take time to test it

**Comment by SBKila** [comment]
Hi, I have install the Openhab 2.4 stable release, I suppose the fix is not in it. I'm working on a ESP8266 with autodiscover Homeassistant protocol. what should i use to try your fix ?

**Comment by davidgraeff** [comment]
oh 2.5m2

**Comment by J-N-K** [comment]
@lucacalcaterra, @SBKila can you report if this is fixed?

**Comment by lucacalcaterra** [comment]
I must rewrite my project due to API changes of server (alarm project)... So now i cannot test it, very very busy :-( I'll inform you when i'll have time

**Comment by SBKila** [comment]
Hi luca,


I have install 2.5.0 M3 release and perform some test

Test 1 with autodiscovery without definition of payload_available => default value is « online »

homeassistant/binary_sensor/portal/bell : 
{
	"~": "homeassistant/binary_sensor/portal/bell",
	"name": "Portal Bell Btn",
	"avty_t": "~/available",
	"stat_t": "~/state",
	"uniq_id": "be2a4e743fee",
	"dev": {
		"ids": "dc4f22184f81",
		"name": "PortalControler",
		"mf": "KilaProduction",
		"mdl": "DIY",
		"sw": "0.1"
	}
}





When sending 
homeassistant/binary_sensor/portal/bell/available : online



In logs get Following
2019-10-19 11:03:32.650 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler HomeAssistantThingHandler tried updating the thing status although the handler was already disposed.

>>>>>>>>>>>>>>> i disconnect my module and power it again
>>>>>>>>>>>>>>> it reconnect  to mosquitto
>>>>>>>>>>>>>>> it resend the Discovery message

When sending 
homeassistant/binary_sensor/portal/bell/available : online




==> /opt/openhab250m3/userdata/logs/openhab.log <==
2019-10-19 11:09:37.712 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler HomeAssistantThingHandler tried updating the thing status although the handler was already disposed.

==> /opt/openhab250m3/userdata/logs/events.log <==
2019-10-19 11:09:37.726 [hingStatusInfoChangedEvent] - 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee' changed from OFFLINE (GONE): At least one component not active to ONLINE

When sending 
homeassistant/binary_sensor/portal/bell/available : offline



==> /opt/openhab250m3/userdata/logs/openhab.log <==
2019-10-19 11:09:40.720 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler HomeAssistantThingHandler tried updating the thing status although the handler was already disposed.

==> /opt/openhab250m3/userdata/logs/events.log <==
2019-10-19 11:09:40.736 [hingStatusInfoChangedEvent] - 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee' changed from ONLINE to OFFLINE (GONE): At least one component not active



Provenance : Courrier pour Windows 10

De : Luca Calcaterra
Envoyé le :jeudi 17 octobre 2019 15:37
À : openhab/openhab2-addons
Cc : SBKILA; Mention
Objet :Re: [openhab/openhab2-addons] [mqtt] Manage the things offline/onlinewith availability_topic for HomeAssistant MQTT Thing (#4863)

I must rewrite my project due to API changes of server (alarm project)... So now i cannot test it, very very busy :-( I'll inform you when i'll have time
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by SBKila** [comment]
Test 2 with autodiscovery with definition of payload_available


homeassistant/binary_sensor/portal/bell :
{
	"~": "homeassistant/binary_sensor/portal/bell",
	"name": "Portal Bell Btn",
	"avty_t": "~/available",
	"stat_t": "~/state",
	"uniq_id": "be2a4e743fee",
	"pl_avail": "1",
	"pl_not_avail": "0",
	"dev": {
		"ids": "dc4f22184f81",
		"name": "PortalControler",
		"mf": "KilaProduction",
		"mdl": "DIY",
		"sw": "0.1"
	}
} 


2019-10-19 11:29:27.168 [home.event.InboxAddedEvent] - Discovery Result with UID 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee' has been added.

==> /opt/openhab250m3/userdata/logs/openhab.log <==
2019-10-19 11:29:27.166 [INFO ] [g.discovery.internal.PersistentInbox] - Added new thing 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee' to inbox.




==> /opt/openhab250m3/userdata/logs/openhab.log <==
2019-10-19 11:30:25.532 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channel 'be2a4e743fee#sensor' for thing type 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee', because channel type 'mqtt:be2a4e743fee_sensor' could not be found.
2019-10-19 11:30:25.542 [WARN ] [re.thing.internal.ThingFactoryHelper] - Could not create channels for channel group 'be2a4e743fee' for thing type 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee', because channel group type 'mqtt:be2a4e743fee' could not be found.

==> /opt/openhab250m3/userdata/logs/events.log <==
2019-10-19 11:30:25.565 [me.event.InboxRemovedEvent] - Discovery Result with UID 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee' has been removed.
2019-10-19 11:30:25.587 [hingStatusInfoChangedEvent] - 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee' changed from UNINITIALIZED to INITIALIZING
2019-10-19 11:30:25.632 [hingStatusInfoChangedEvent] - 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee' changed from INITIALIZING to OFFLINE (GONE): No response from the device yet



When sending 
homeassistant/binary_sensor/portal/bell/available : 1



==> /opt/openhab250m3/userdata/logs/openhab.log <==
2019-10-19 11:31:24.235 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command '1' not supported by type 'OnOffValue': No enum constant org.eclipse.smarthome.core.library.types.OnOffType.1
2019-10-19 11:31:24.244 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command '1' not supported by type 'OnOffValue': No enum constant org.eclipse.smarthome.core.library.types.OnOffType.1


>>>>>>>>>>>>>>> i disconnect my module and power it again
>>>>>>>>>>>>>>> it reconnect  to mosquitto
>>>>>>>>>>>>>>> it resend the Discovery message


==> /opt/openhab250m3/userdata/logs/events.log <==
2019-10-19 11:33:24.479 [me.event.ThingUpdatedEvent] - Thing 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee' has been updated.
2019-10-19 11:33:24.484 [hingStatusInfoChangedEvent] - 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee' changed from OFFLINE (GONE): No response from the device yet to OFFLINE (GONE): At least one component not active




When sending 
homeassistant/binary_sensor/portal/bell/available : 1




==> /opt/openhab250m3/userdata/logs/openhab.log <==
2019-10-19 11:35:36.466 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command '1' not supported by type 'OnOffValue': No enum constant org.eclipse.smarthome.core.library.types.OnOffType.1
2019-10-19 11:35:36.471 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command '1' not supported by type 'OnOffValue': No enum constant org.eclipse.smarthome.core.library.types.OnOffType.1

==> /opt/openhab250m3/userdata/logs/events.log <==
2019-10-19 11:35:36.483 [hingStatusInfoChangedEvent] - 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee' changed from OFFLINE (GONE): At least one component not active to ONLINE


When sending 
homeassistant/binary_sensor/portal/bell/available : 0



==> /opt/openhab250m3/userdata/logs/openhab.log <==
2019-10-19 11:35:45.235 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command '0' not supported by type 'OnOffValue': No enum constant org.eclipse.smarthome.core.library.types.OnOffType.0
2019-10-19 11:35:45.240 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command '0' not supported by type 'OnOffValue': No enum constant org.eclipse.smarthome.core.library.types.OnOffType.0

==> /opt/openhab250m3/userdata/logs/events.log <==
2019-10-19 11:35:45.248 [hingStatusInfoChangedEvent] - 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee' changed from ONLINE to OFFLINE (GONE): At least one component not active


Provenance : Courrier pour Windows 10

De : Stephane Blanc
Envoyé le :samedi 19 octobre 2019 11:12
À : openhab/openhab2-addons; openhab/openhab2-addons
Cc : Mention
Objet :RE : [openhab/openhab2-addons] [mqtt] Manage the things offline/onlinewith availability_topic for HomeAssistant MQTT Thing (#4863)

Hi luca,


I have install 2.5.0 M3 release and perform some test

Test 1 with autodiscovery without definition of payload_available => default value is « online »

homeassistant/binary_sensor/portal/bell : 
{
                "~": "homeassistant/binary_sensor/portal/bell",
                "name": "Portal Bell Btn",
                "avty_t": "~/available",
                "stat_t": "~/state",
                "uniq_id": "be2a4e743fee",
                "dev": {
                                "ids": "dc4f22184f81",
                                "name": "PortalControler",
                                "mf": "KilaProduction",
                                "mdl": "DIY",
                                "sw": "0.1"
                }
}





When sending 
homeassistant/binary_sensor/portal/bell/available : online



In logs get Following
2019-10-19 11:03:32.650 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler HomeAssistantThingHandler tried updating the thing status although the handler was already disposed.

>>>>>>>>>>>>>>> i disconnect my module and power it again
>>>>>>>>>>>>>>> it reconnect  to mosquitto
>>>>>>>>>>>>>>> it resend the Discovery message

When sending 
homeassistant/binary_sensor/portal/bell/available : online




==> /opt/openhab250m3/userdata/logs/openhab.log <==
2019-10-19 11:09:37.712 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler HomeAssistantThingHandler tried updating the thing status although the handler was already disposed.

==> /opt/openhab250m3/userdata/logs/events.log <==
2019-10-19 11:09:37.726 [hingStatusInfoChangedEvent] - 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee' changed from OFFLINE (GONE): At least one component not active to ONLINE

When sending 
homeassistant/binary_sensor/portal/bell/available : offline



==> /opt/openhab250m3/userdata/logs/openhab.log <==
2019-10-19 11:09:40.720 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler HomeAssistantThingHandler tried updating the thing status although the handler was already disposed.

==> /opt/openhab250m3/userdata/logs/events.log <==
2019-10-19 11:09:40.736 [hingStatusInfoChangedEvent] - 'mqtt:homeassistant_be2a4e743fee:accce134:be2a4e743fee' changed from ONLINE to OFFLINE (GONE): At least one component not active



Provenance : Courrier pour Windows 10

De : Luca Calcaterra
Envoyé le :jeudi 17 octobre 2019 15:37
À : openhab/openhab2-addons
Cc : SBKILA; Mention
Objet :Re: [openhab/openhab2-addons] [mqtt] Manage the things offline/onlinewith availability_topic for HomeAssistant MQTT Thing (#4863)

I must rewrite my project due to API changes of server (alarm project)... So now i cannot test it, very very busy :-( I'll inform you when i'll have time
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



Garanti sans virus. www.avast.com 



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by jochen314** [comment]
I tried your sample config on the current master branch.

Please note, that the topic for the configuration needs to end in <code>/config</code> for autodiscovery to work (see https://www.home-assistant.io/docs/mqtt/discovery/).

So putting the sample configs under <code>homeassistant/binary_sensor/portal/bell/config</code>, I did not encounter any problems.
The thing went online/offline when the correponding messages where sent.

**Comment by SBKila** [comment]
Hi, totally agree with you, it is a wrong copy paste the URL I use end with
config of course.



Le sam. 19 oct. 2019 à 16:13, Jochen Klein <notifications@github.com> a
écrit :

**Comment by SBKila** [comment]
I perform test test again and item status stay offline until the module module in unplug and replug,

I’m running with 2.5M3 release running on a orange pi zero with debian

[18:41:57] orangepi@openhabserver:~$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
[18:42:19] orangepi@openhabserver:~$

I’m going to  perform same test on 2.4 master ? I’ll be back




De : Stephane Blanc
Envoyé le :samedi 19 octobre 2019 16:53
À : openhab/openhab2-addons
Objet :Re: [openhab/openhab2-addons] [mqtt] Manage the things offline/onlinewith availability_topic for HomeAssistant MQTT Thing (#4863)

Hi, totally agree with you, it is a wrong copy paste the URL I use end with config of course.



Le sam. 19 oct. 2019 à 16:13, Jochen Klein <notifications@github.com> a écrit :
I tried your sample config on the current master branch.
Please note, that the topic for the configuration needs to end in /config for autodiscovery to work (see https://www.home-assistant.io/docs/mqtt/discovery/).
So putting the sample configs under homeassistant/binary_sensor/portal/bell/config, I did not encounter any problems.
The thing went online/offline when the correponding messages where sent.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by jochen314** [comment]
Hi,

I think I understand now, what the problem is.

Openhab assumes, that the config message is sent as a retained message. Therefore it will be always available. 
And it is needed twice: Once to discover the thing and again when the thing is activated.

And you are sending the config message not retained. So the thing is discovered, but during activation, the config is missing, so the thing is not activated.
Restarting you device probably sends the config again and then the thing is activated.

@davidgraeff: I could not find any hint, that homeassitant expects the config messages to be sent retained.
I think, we should not expect the config message to be there during activation.
We should listen for a changed config, but the thing should go active, if the availability message is received with the online payload or any other channel value recevied a message. This is, what homeassistent seems to be doing, see https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant#tip-sync-power-state)

**Comment by SBKila** [comment]
Hi 

Here is an additional question regarding availability_topic.
It is not an issue.

I understand this topic unsing online/offline, 
      1 when my device is able to connect MQTT server and is ready to work i send an online. 
      2 when my device is able to connect MQTT server and is not ready to work  i send an offline.

On my point of view the missing feature is :
      OpenHab do not received online status since « TDB in Discovery config » then device is offline. 

Is there a way to perform that in openhab ?

Regards,


De : Jochen Klein
Envoyé le :dimanche 20 octobre 2019 13:01
À : openhab/openhab2-addons
Cc : SBKILA; Mention
Objet :Re: [openhab/openhab2-addons] [mqtt] Manage the things offline/onlinewith availability_topic for HomeAssistant MQTT Thing (#4863)

Hi,
I think I understand now, what the problem is.
Openhab assumes, that the config message is sent as a retained message. Therefore it will be always available.
And it is needed twice: Once to discover the thing and again when the thing is activated.
And you are sending the config message not retained. So the thing is discovered, but during activation, the config is missing, so the thing is not activated.
Restarting you device probably sends the config again and then the thing is activated.
@davidgraeff: I could not find any hint, that homeassitant expects the config messages to be sent retained.
I think, we should not expect the config message to be there during activation.
We should listen for a changed config, but the thing should go active, if the availability message is received with the online payload or any other channel value recevied a message. This is, what homeassistent seems to be doing, see https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant#tip-sync-power-state)
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by jochen314** [comment]
This is solved by using the LWT (last will) on the broker.
When you device connects, it sends the online message.
And it set a LWT with the offline message.
Then the broker will automatically send the offline message as soon as the connection to your device is lost.

Or am i missing your point?

**Comment by jochen314** [comment]
Or is it the timing which concerns you?
Your device is starting up, but openHAB starts later and does not see the available message?

That is, why most devices send those messages as <code>retained</code>. So any listener will get them as soon as they connect.

**Comment by SBKila** [comment]
For your information, ESPHome have a config to setup Discovery retain, by default it is true.
As you can read it is to get Hass be able to discover item if started after the device.

https://esphome.io/components/mqtt.html

discovery_retain (Optional, boolean): Whether to retain MQTT discovery messages so that entities are added automatically on Home Assistant restart. Defaults to True.





De : Jochen Klein
Envoyé le :dimanche 20 octobre 2019 13:01
À : openhab/openhab2-addons
Cc : SBKILA; Mention
Objet :Re: [openhab/openhab2-addons] [mqtt] Manage the things offline/onlinewith availability_topic for HomeAssistant MQTT Thing (#4863)

Hi,
I think I understand now, what the problem is.
Openhab assumes, that the config message is sent as a retained message. Therefore it will be always available.
And it is needed twice: Once to discover the thing and again when the thing is activated.
And you are sending the config message not retained. So the thing is discovered, but during activation, the config is missing, so the thing is not activated.
Restarting you device probably sends the config again and then the thing is activated.
@davidgraeff: I could not find any hint, that homeassitant expects the config messages to be sent retained.
I think, we should not expect the config message to be there during activation.
We should listen for a changed config, but the thing should go active, if the availability message is received with the online payload or any other channel value recevied a message. This is, what homeassistent seems to be doing, see https://github.com/arendst/Sonoff-Tasmota/wiki/Home-Assistant#tip-sync-power-state)
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by SBKila** [comment]
I’m studying LWT, it seems to be what i was looking for.

My needs :

I’d like to have an offline status in openhab when my device is not connected to MQTT.
It can happen if batterie power is too low.

I’ll be back to you if i’ll be not able to implement it using LWT 








De : Jochen Klein
Envoyé le :dimanche 20 octobre 2019 14:22
À : openhab/openhab2-addons
Cc : SBKILA; Mention
Objet :Re: [openhab/openhab2-addons] [mqtt] Manage the things offline/onlinewith availability_topic for HomeAssistant MQTT Thing (#4863)

Or is it the timing which concerns you?
Your device is starting up, but openHAB starts later and does not see the available message?
That is, why most devices send those messages as retained. So any listener will get them as soon as they connect.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by SBKila** [comment]
Hi,

I have study LWT, LWT is a feature of MQTT server.
As soon as a connection to device is lost, MQTT server is able to post a message according to Last Will and Testament config.

I’m implementing it on my device.

What is not so perfect is :

There is 1 LWT for 1 MQTT client connection. My device establish 1 connection to MQTT server but provides several items to Openhab via several autodiscovery messages.

Autodiscovery protocol is able to group items in the same device. But there is no definition of device availability.
I have to learn more on Openhab or Hass to understand the best practice.

regards



De : Stephane Blanc
Envoyé le :dimanche 20 octobre 2019 14:51
À : openhab/openhab2-addons
Objet :RE : [openhab/openhab2-addons] [mqtt] Manage the things offline/onlinewith availability_topic for HomeAssistant MQTT Thing (#4863)

I’m studying LWT, it seems to be what i was looking for.

My needs :

I’d like to have an offline status in openhab when my device is not connected to MQTT.
It can happen if batterie power is too low.

I’ll be back to you if i’ll be not able to implement it using LWT 








De : Jochen Klein
Envoyé le :dimanche 20 octobre 2019 14:22
À : openhab/openhab2-addons
Cc : SBKILA; Mention
Objet :Re: [openhab/openhab2-addons] [mqtt] Manage the things offline/onlinewith availability_topic for HomeAssistant MQTT Thing (#4863)

Or is it the timing which concerns you?
Your device is starting up, but openHAB starts later and does not see the available message?
That is, why most devices send those messages as retained. So any listener will get them as soon as they connect.
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



Garanti sans virus. www.avast.com 



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by jochen314** [comment]
There is no problem in using the save availability topic for all the components implemented by one device

**Comment by SBKila** [comment]
Good news,  I’ll do like this.

Thank you so much for sharing your knowledge.


Provenance : Courrier pour Windows 10

De : Jochen Klein
Envoyé le :dimanche 20 octobre 2019 16:04
À : openhab/openhab2-addons
Cc : SBKILA; Mention
Objet :Re: [openhab/openhab2-addons] [mqtt] Manage the things offline/onlinewith availability_topic for HomeAssistant MQTT Thing (#4863)

There is no problem in using the save availability topic for all the components implemented by one device
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
L'absence de virus dans ce courrier électronique a été vérifiée par le logiciel antivirus Avast.
https://www.avast.com/antivirus

**Comment by davidgraeff** [comment]
> @davidgraeff: I could not find any hint, that homeassitant expects the config messages to be sent retained.
I think, we should not expect the config message to be there during activation.

True. It's easier with retained messages though and for a discovery protocol retained messages are a must in the mqtt domain. You somehow need to query for devices. We should maybe poke the HA guys to specify their protocol in that regard.

We are storing the config anyway though, so you are right that we could activate devices without /config being present. But what if we missed a /config change (OH temporary offline) and a device changed its abilities etc?

**Comment by jochen314** [comment]
Currently we only store the config after the thing has been activated once.
Discovery only stores the topics.
That would be a bigger change.

I would also opt for forcing devices to publish their config retained.

**Comment by eikowagenknecht** [comment]
Is there any update on this? I'm experiencing problems (see [my thread in openHAB forum](https://community.openhab.org/t/mqtt-availability-topic-not-working/99760?u=eikowagenknecht))  with the "Availability Topic" as well, though I'm using the "Generic MQTT Binding". Do they share code in this regard or should I open another issue?

**Comment by bodiroga** [comment]
Hi @eikowagenknecht!

I have tried to reproduce your issue ("shellies/test/online" as the availability topic and "true/false" as payload), but in my simple example everything behaves correctly. 

Here you have a screen recording of my test:

[MQTT Generic Thing - Availability.zip](https://github.com/openhab/openhab-addons/files/4705624/MQTT.Generic.Thing.-.Availability.zip)

My setup: openHAB 2.5.5 running on Docker and Mosquitto as the MQTT broker. Messages are been sent as QoS 0 and non-retained.

- Can you try refreshing the browser window (F5)? Perhaps Paper UI has not been updated properly, but I suppose that you have tried this.
- Can you try sending some manual MQTT messages using a desktop client?

Good luck!

**Comment by eikowagenknecht** [comment]
Thanks for trying this out! This is almost the same thing I was doing. Very weird. I noticed that restarting the whole openHAB system at least led to some new behaviour. Now sending false or true (with MQTT Explorer just like you did) logs:

```
2020-05-30 17:38:20.519 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'false' not supported by type 'OnOffValue': No enum constant org.eclipse.smarthome.core.library.types.OnOffType.false

2020-05-30 17:38:26.200 [WARN ] [ab.binding.mqtt.generic.ChannelState] - Command 'true' not supported by type 'OnOffValue': No enum constant org.eclipse.smarthome.core.library.types.OnOffType.true
```

When I change the settings of the thing in any way, this does not happen any more. Even if I change it back to the same setting. Only restarting openHAB or disabling and enabling the thing again seems to change this behaviour.

**Comment by eikowagenknecht** [comment]
Trying again with the exact same settings you have (shellies/test/online) with true/false gives a new error..

**Config:**
![image](https://user-images.githubusercontent.com/1475672/83332788-6cf85280-a29d-11ea-9a9b-b41eb5eb208a.png)

**Sending:**
![image](https://user-images.githubusercontent.com/1475672/83332809-90230200-a29d-11ea-98ca-4e22ad505170.png)

**Error:**
![image](https://user-images.githubusercontent.com/1475672/83332813-9913d380-a29d-11ea-88d8-e5b5f498c38a.png)

**Comment by jochen314** [comment]
Hi, 

This seems to be a more basic problem in openhab core (2.5.0).
When we get the incomming message, we try to convert it to an `OnOffType` of a `StringType` (in that order).
In this case, the convesion to `OnOffType` fails ('No enum constant ...'), but `org.eclipse.smarthome.core.types.TypeParser.parseCommand()` does not handle the exception. So the second type (`StringType`) is never tried.

As a workaround, try to use the payloads `ON` and `OFF` for now.

**Comment by eikowagenknecht** [comment]
Unfortunately I can not use ON and OFF because the values are set by the shelly firmware and I can not change that. As a workaround for my use case, I switched to the Shelly binding instead of the MQTT binding for now..

**Comment by cweigel** [comment]
> As a workaround, try to use the payloads ON and OFF for now.

I tried this now myself (openHabian - OpenHAB 2.5.7).  I could successfully use ON / OFF as well as ONLINE/OFFLINE **as long as there is no channel added to the Generic MQTT Thing**.

The very moment I add a channel the Thing switches to "online" and cannot be changed anymore (neither with OFF nor OFFLINE). So perhaps the availability is somehow overridden...

**Comment by bodiroga** [comment]
Hi @cweigel!

Can you show us your full configuration? Thing name and exact configuration: availability topic, payload available, payload not available, channel information...

I've been doing some tests with a single generic MQTT Thing (sending availability messages with MQTT Explorer) and I'm unable to reproduce the issue :thinking: 

Thanks!

**Comment by jochen314** [comment]
> The very moment I add a channel the Thing switches to "online" and cannot be changed anymore (neither with OFF nor OFFLINE). So perhaps the availability is somehow overridden...

Yes, current code will put a thing online if the availability message was received **or** any other messages was received.

PR #7206 corrects that.

**Comment by cweigel** [comment]
> Hi @cweigel!
> 
> Can you show us your full configuration? Thing name and exact configuration: availability topic, payload available, payload not available, channel information... Also, can you tell me if your availability messages are sent as retained?
> 
> I've been doing some tests with a single generic MQTT Thing (sending availability messages with MQTT Explorer) and I'm unable to reproduce the issue 🤔
> 
> Thanks!

Sorry I am currently having no time to test again. I will report asap.

**Comment by hmerk** [comment]
closed due to inactivity
