### ISSUE TITLE
[enocean] EEP A5-38-08 Dimming value range invalid

### ISSUE THREAD

**Issue by fgaultier** [openhab/openhab-addons#4865]
According to EnOcean Equipment Profile Specification v2.6.7, EEP A5-38, command 0x02 dimming:
 valid dimming value range shall be between 0 and 255 (0x00 - 0XFF)

But current implementation (see file A5_38_08_Dimming.java) uses 0 - 100 (0x00 - 0x64) as value range.

We are using Mean Well LCM-40-E0 as LED driver and obviously it does not deliver full power with only 100 as dimming value.

**Comment by dominikkv** [comment]
Hi @fgaultier,

it seems you are right. You can set the DB2 value in two different ways, absolute (0..255) and relative (0..100), but you have to set DB0.2 accordingly. Right now, DB0.2 is always 0 = absolute.

I think this comes from Eltako, they sometimes do interpret the specification in their own way :-D For them, DB0.2 means "block value" and DB2 is always relative. So we have to separate those two profiles.

I'll have a look at this soon.

**Comment by fruggy83** [comment]
Hi @fgaultier 

you are absolute right. I implemented the A5-38 dimming EEP based on the Eltako specs and did not looked in the EnOcean docs. It is a pity that Eltako did not implented the dimmer EEP in line with the official EEP.
@dominikkv It would be nice if you could implement a generic A5_38 dimming profile, I am still working on ESP2 support. Thanks a lot.

**Comment by fgaultier** [comment]
Hi Daniel,

Thanks  for your email. We plan also to contribute to OpenHab in a near future (EnOcean addOn  and possibly on a future BLE Mesh addOn), but the whole Eclipse Ecosystem / Environment is somewhat new for us and we will  need some time (maybe also some help) before we are able to build and push meaningful contributions ??

Best regards,

Franck Gaultier
R&D Project Manager

De : Daniel Weber<mailto:notifications@github.com>
Envoyé le :lundi 25 février 2019 09:16
À : openhab/openhab2-addons<mailto:openhab2-addons@noreply.github.com>
Cc : Franck Gaultier<mailto:fgaultier@citc-eurarfid.com>; Mention<mailto:mention@noreply.github.com>
Objet :Re: [openhab/openhab2-addons] [enocean] EEP A5-38-08 Dimming value range invalid (#4865)


Hi @fgaultier<https://github.com/fgaultier>

you are absolute right. I implemented the A5-38 dimming EEP based on the Eltako specs and did not looked in the EnOcean docs. It is a pity that Eltako did not implented the dimmer EEP in line with the official EEP.
@dominikkv<https://github.com/dominikkv> It would be nice if you could implement a generic A5_38 dimming profile, I am still working on ESP2 support. Thanks a lot.

**Comment by fruggy83** [comment]
Hi @dominikkv, sorry for being so late in commenting this PR. I totally agree with your implementation, however why have you not implemented a new EEP as we did it with FXBH_A5_08_01 or the manufacturer specific D2-01 EEPs?

@davidgraeff I do not want to be to nit-picking, but I would classify this issue more as an enhancement. As this EEP should also support the MeanWell driver. Eltako support is already fine.

**Comment by dominikkv** [comment]
Hey @fruggy83, I have thought about this, but came to the conclusion that it is better to do it this way. The problem is that we have an Eltako specific implementation named as the standard EEP. If I would have renamed the existing implementation, and created a new standard implementation, backward compatibility would have been broken. Everyone using this would have to change their configuration. And, to be honest, I have interpreted your "implement a generic A5_38 dimming profile" as you prefer it to be in one class :-o

I'm sorry that I did not discuss this with the community as I initially intented, but time went by and I wanted to make progress :-D So if you prefer it as two different classes, let me know, and I'm happy to change this. Maybe you have an even better solution?

**Comment by fruggy83** [comment]
Hi @dominikkv,

backward compatibility is a good point 👍 , which I had not in mind. I configured my system with DSL files, therefore such a change would not be big thing for me. But you are absolutly right, having this in mind, I also think that your implementation is the best solution. However if we ever find another implementation of this dimming EEP, we should think about a breaking change instead of introducing another manufacturer switch.

Thanks a lot for your work and explanation.

Best regards
Daniel
