### ISSUE TITLE
[sonyaudio] usb

### ISSUE THREAD

**Issue by tmrobert8** [openhab/openhab-addons#5446]
Is @freke still around?  I've now integrated the sonyaudio fully into the sony plugin (and it could actually be deprecated now).  However - I have some questions that I hoped he might help with.  The biggest is when you try to switch to a USB input [storage:usb1], the API returns successfully but the input is never switched (test bed was with my HT-NT5 and with my DN1080 - didn't work on either).  

Please note that this happens whether I use the sonyaudio addon, my sony addon or if I simply execute the commands directly...

**Comment by freke** [comment]
Still around, lots of other things right now...
Using the USB storage functionality is not recommended to do via the Audio API it is an old implementation that is not working reliable on all devices and is a bit messy in best cases. To access the music on usb (or other media servers) it is better to use the DLNA API. https://developer.sony.com/develop/audio-control-api/get-started/browse-dlna-file

**Comment by tmrobert8** [comment]
Thanks - that may be a future step.  I can use the API to browse the USB content and actually play the content (which switches the input as a side effect) - but just can't seem to select the USB directly (even with your plugin - trying to hit the "USB" button does nothing).

A few other questions if you don't mind:
1. The notifications (events) all seem to come back with version "1.0" even if they aren't (play content being 1.2).  For now, I'm just assuming the calling method version - is the notification version a bug?
2. I was pretty sure that data structure is fixed by version.  However, I've found that getPlayingContentInfo (v1.2) seems to have different fields on my HT-NT5 than on my DN1080.  One has is3D, parentIndex and path fields whereas the other doesn't.  Not really an issue - just broke my way of thinking (ie v1.2 would have the same fields on all devices).  Was that a correct assumption and there is a bug or was that a very bad assumption!
3. SwitchNotifications seems to have a bug in it.  If I blindly move all the disabled to the enabled and reissue switchnotifications - sometimes the response will come back with nothing enabled (and I receive no events as well).  I *think* it may be related to an invalid notification in the disabled list.  My theory is that on the HT-NT5 - there is a notifywirelesssomething event that I'm assuming would give me events on any wireless speakers.  But since I have no wireless speakers paired - I think the API fails and defaults back to the original configuration (everything disabled).  Could you check that - seems like a bug to me on your end (should ignore any invalid ones).  In the meantime, I'm only enabling those that I care about (I was blindly doing them all to see what events I get back)...

**Comment by freke** [comment]
> but just can't seem to select the USB input directly
The USB is something that is phased out and I can't get it selected ether without starting a playback.

1) I think most if not all of the notifications messages are version 1.0 and the version number is actually for the message it self not the API, it is a bit confusing. There is a second version number that is for the API it self, that is updated every year, but that only defines what versions of the messages are to be used in that years device lineup.
2) The data structure is the same and fixed by version, but required and optional field is different from different products and getPlayingContentInfo is really nasty since it changes dependent of the value of the "source" field.
3) SwitchNotifications is a bit tricky I have found that to get consistent result I have to always get current status and set all notifications (event the one I don't want to change) every time. I have also noticed that if the SwitchNotifications message is not what the device expect it will set every thing back to disabled.
4) Will test with your addon, I have most of the newer devices but very limited with things to connect to it here but if I find anything I will let you know.

**Comment by tmrobert8** [comment]
@freke 
One other thing - why don't we get playing notifications for DLNA type of source?  Shouldn't really be any different than USB source (just networked) and we get notifications for that.

Thanks,
Tim

**Comment by freke** [comment]
I don't know why, the API was developed for internal usage only in the beginning so it is not that very well designed and logic always.

If you want playing notifications I think you have to register for the notifications via DLNA, I have never done it my self so I don't know if it works.
