### ISSUE TITLE
[IDE] Build Automatically in Eclipse builds infinitely

### ISSUE THREAD

**Issue by mvalla** [openhab/openhab-addons#5554]
In the new build system, using Eclipse and bnd-tools according to OH2 developer manual, after having checked out maggu2810/openhab-demo project and imported, if Build Automatically is selected it builds infinitely and does not stop ("Building workspace..." again and again). 
De-activating Build Automatically stops the infinite loop.
This makes very unconvenient to develop a new bundle using Eclipse.

## Expected Behavior
Build Automatically should work as normal.

## Current Behavior
If Build Automatically is selected it builds infinitely and does not stop ("Building Workspace..." again and again). De-activating Build Automatically stops the infinite loop.

## Steps to Reproduce (for Bugs)
1. Follow steps 1. - 3. of the developer guide (https://www.openhab.org/docs/developer/)
2. With Build Automatically activated the build enters a loop and never ends

## Your Environment
* Version used: openHAB 2.5.0-SNAPSHOT, maggu2810/openhab-demo
* Environment name and version: Eclipse Eclipse IDE for Java Developers Version: 2019-03 (4.11.0)
* Operating System and version: Windows10

**Comment by davidgraeff** [comment]
FYI The situation is known but no solution has been found yet

**Comment by limdul79** [comment]
I stumbled over this problem also and tried to find the cause. Sadly, as I'm not an eclipse expert, at some point my knowledge & time was to small.

What I found out:
- Whenever the project is build, the bndtools.m2e builds the jar
- That results in a content change of targt/binding-2.5.0-SNAPSHOT.jar
- That results that some plugin/eclipse (it seems that this is not bndtools.m2e) schedules a build because a resource had changed
and now we have a loop.

I found here: https://github.com/bndtools/bnd/blob/master/bndtools.m2e/src/bndtools/m2e/BndConfigurator.java some interessting code mentioning such problems around 163. If I remove the line 
                            buildDir.refreshLocal(IResource.DEPTH_INFINITE, progress.newChild(1));
than the loop does not occur, it stops after build. 
However this is not a real solution because it doesn't rebuild because the change is not detected immediately. If I press F5 in the navigator, another build cycle starts.

Maybe this helps someone with better eclipse insight to find the root of the problem.

**Comment by Gozilla01** [comment]
Look here

https://community.openhab.org/t/temporary-solution-to-compile-with-maven-bnd/74242

**Comment by davidgraeff** [comment]
@limdul79 Thanks a lot. You have found the problematic code. They say in that TODO that they only want to investigate further if it is a real world problem. And now it certainly is.

Maybe @njbartlett has an idea, as he touched that file last to prevent build loops according to git blame :)
(To give a bit of context: We switched from Tycho/PDE to bnd in openHAB and are facing an endless rebuild problem in Eclipse now)

**Comment by mvalla** [comment]
@davidgraeff : what is the solution and plan for this one?

This definitely **show-stopper** for having a working Eclipse IDE for OH2 using the new buildsystem.
At least for me this is the last issue remaining issue before being back to a decent IDE setup with Eclipse, including hot deploy of modified bundles and full debug support (including modifying code while debugging).

Did you try to contact the bndtools developers and explain the urgency for the openHAB community and perhaps have some help from them ? 

Do you have any intermediate B-plan so not to stop all OH developers from being able to use Eclipse ?
Maybe a patch to bndtools ? Or a change in the bndtools-maven script to avoid the loop?

Is @kaikreuzer also having the same issue while preparing the new Eclipse IDE configuration ?

**Comment by davidgraeff** [comment]
@mvalla As you have seen I have referenced the bnd developer that wrote that code and he did not respond.

My plan B is to not use maven and perform a second buildsystem migration to Gradle. bnd developers use Gradle themselves so issues are not expected or expected to be ironed out fast.

**Comment by Misiu** [comment]
@davidgraeff, as I wrote in a different place smooth developer experience, should be the top priority, but...
I think the second migrations should be done **after** another milestone release is published.

Also, core developers should say what they think about second migration.

**Comment by davidgraeff** [comment]
@Misiu You are a very contradicting person ^^. Core developers will be AGAINST a second migration but at the same time smooth developer experience is only guaranteed with a second migration. How do you solve that? ;)

**Comment by Misiu** [comment]
@davidgraeff I agree with Your opinion 🙂 but sometimes it is hard to make a decision that isn't a simple one. I'd like to see OpenHab move forward, see new releases, but at the same time, I want to contribute and have a really easy setup for all new users.
If switching to Gradle means better developer experience then I'm in favor of migration. This is a long term goal - now work must be done, but in the future, more people will be able to contribute.
I personally tried to setup IDE 3 times, now my binding is waiting for new IDE and for tests. I want to create 3 other bindings but this also must wait.

Many people that look here can code, want to help/contribute, but when they try to set up the IDE and development environment they give up 🤔

I come from .NET world, in most cases when You download C# project You clone a repo, open that project in VS and hit F5. I'd love to get the same experience with OpenHab.

**Comment by wborn** [comment]
I created an issue (https://github.com/bndtools/bnd/issues/3220) for it in the bnd tracker after investigating it a bit. Maybe you know a nice workaround for it @maggu2810 ? Using `-includeresource` instead for these resources might work. But that will only work for bundles.

So I think there's no need for a Gradle migration. :wink: There's also a good read by Philipp Hauer for those considering Gradle migrations: [Why I Moved Back from Gradle to Maven](https://phauer.com/2018/moving-back-from-gradle-to-maven/).

**Comment by davidgraeff** [comment]
> There's also a good read by Philipp Hauer for those considering Gradle migrations: Why I Moved Back from Gradle to Maven.

From 2017 and also 2/3 of the comments say that it depends if you stay disciplined in Gradle, because you CAN use it procedural. But that's what @J-N-K did in maven as well with ant tasks. Sometimes you just need to define some procedural tasks. I still believe Gradle is the better choice, especially because the bnd project itself is using it and their bnd m2e maven plugin seem to be in somewhat maintenance mode only.

But maybe the bug report helps. The name mentioning here in this Issue of the guy that wrote the code did not help.

**Comment by wborn** [comment]
Yes there's sometimes a need for procedural tasks. You can also use the [groovy-maven-plugin](https://groovy.github.io/gmaven/groovy-maven-plugin/execute.html) for that so you can just write Groovy/Java code instead of using Ant. You can use JARs from Maven repos by adding them to the `<dependencies>` of the plugin. But if that procedural code is getting complex and it should be reusable across several repo's it's probably better to create a new Maven plugin for it. It might also be reusable for other projects. In case of Karaf it can perhaps also be added to the karaf-maven-plugin.

**Comment by barthoukes** [comment]
Very annoying, but now .continue is working in VScode, I have autocomplete working and it can find bugs in my code. For building projects, my company wants to change to VScode as soon as we found a build alternative to Eclipse builds. All my friends have already stopped with Eclipse, including a big company in Veldhoven.
