### ISSUE TITLE
Dependencies of wrapped dependencies not installed

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab-addons#5644]
I came across the problem when investigating #5473 and [this forum report](https://community.openhab.org/t/update-to-snapshot-1597-partially-failed-allplay-amazondashbutton-wrapper-service-z-wave-solved/74930).

In both cases we have dependencies that are non-OSGi-bundles. These bundles may depend on other bundles (OSGi or non-OSGi), but they can't declare that dependency. These bundles are not installed when the feature is installed. 

The reason is that we mark external dependencies with `dependency="true"` in the feature. A little bit suprising this does not mean `install it if not present` but `install it if not present AND REQUIRED`. The last part is the problem, since non of our other bundles in that feature actually declare that they depend on that bundle.

Solution: Get #5503 running. If we only have OSGi-bundles, this problem will be immediately solved. 

IMO this needs to be resolved before the next milestone since it probably breaks more than those two bindings.

**Comment by J-N-K** [comment]
Another solution would be to remove `dependency="true"` but this will most likely get us into trouble if two bindings install that bundle.

**Comment by wborn** [comment]
The [wrap protocol](https://ops4j1.jira.com/wiki/spaces/paxurl/pages/3833898/Wrap+Protocol) also allows for adding package imports (see last example):

`wrap:mvn:org.infinispan/infinispan-core/5.2.6.Final$overwrite=merge&Import-Package=sun.misc;net.jcip.annotations;resolution:=optional,org.jgroups.*;version="[3.2,4)",org.jboss.logging;version="[3.1,4)",*&Export-Package=org.infinispan.*;-noimport:=true`

However it didn't work when I tested it with the Chromecast Binding (https://github.com/openhab/openhab2-addons/pull/5274). In the end it's probably best if the wrapped JARs are replaced with real bundles because they'd also cause issues when launching openHAB from Eclipse or when used in itests.

**Comment by wborn** [comment]
I think we can close this issue now that the add-ons (except for dlinksmarthome) use real OSGi bundles instead of wrapped OSGi bundles @J-N-K?
