### ISSUE TITLE
[lgwebos] Add support for Brazilian channels using NN-N scheme 

### ISSUE THREAD

**Issue by icarome** [openhab/openhab-addons#5744]
Here in Brazil, digital channels are returned to sdk as NN-N (where N is a number). Openhab binding doesn't handle it as it expects a single number. Is it possible to set on binding so this would handle channels numbers as string?

**Comment by wborn** [comment]
Maybe @sprehn can help with adding support for this?

**Comment by sprehn** [comment]
Hi,

looked into it and it should not be complicated. We just need to change the type of this channel to String. 

However, I struggle at the moment to test the change due to the changes in build system and dependency management.

@wborn I set up a fresh 2.5 M1 instance in docker. and placed my updated jar in the addons folder. When it comes up I get "Unresolved requirement: Import-Package: org.java_websocket ". 
I realize from the documentation that when placing jars in addons the automatic dependency management will not install my dependencies. But could you give me a hind how I can install them?
These are the dependencies in feature.xml

<bundle dependency="true">mvn:org.apache.httpcomponents/httpcore-osgi/4.4.4</bundle>
        <bundle dependency="true">mvn:org.apache.httpcomponents/httpclient-osgi/4.5.2</bundle>
        <bundle dependency="true">mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.xpp3/1.1.4c_7</bundle>
        <bundle dependency="true">mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.json/20140107_1</bundle>
        <bundle dependency="true">wrap:mvn:org.java-websocket/Java-Websocket/1.3.9$Bundle-Name=Java%20Websocket%20Client&amp;Bundle-SymbolicName=org.java-websocket.java-websocket&amp;Bundle-Version=1.3.9</bundle>
        <bundle start-level="80">mvn:org.openhab.addons.bundles/org.openhab.binding.lgwebos/${project.version}</bundle>

**Comment by wborn** [comment]
I think you can install those dependencies on the Karaf Console using:

```sh
feature:install wrap
bundle:install mvn:org.apache.httpcomponents/httpcore-osgi/4.4.4
bundle:install mvn:org.apache.httpcomponents/httpclient-osgi/4.5.2
bundle:install mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.xpp3/1.1.4c_7
bundle:install mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.json/20140107_1
bundle:install wrap:mvn:org.java-websocket/java-websocket/1.3.2
```

**Comment by sprehn** [comment]
```
feature:install wrap
```

worked 

but any of the others fail: 


```
openhab> bundle:install mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.xpp3/1.1.4c_7
Bundle IDs: 
Error executing command: Error installing bundles:
	Unable to istall bundle mvn:org.apache.servicemix.bundles/org.apache.servicemix.bundles.xpp3/1.1.4c_7: org.osgi.framework.BundleException: Error reading bundle content.

```

I am still lost

**Comment by sprehn** [comment]
OK, had to switch to SNAPSHOT docker image, now it is working

**Comment by icarome** [comment]
How can I test it?

**Comment by sprehn** [comment]
use a snapshot build. that will be the easiest i would say
