### ISSUE TITLE
[gardena] Obtaining access and refresh tokens every 2 hours causes App logouts

### ISSUE THREAD

**Issue by Rar9** [openhab/openhab-addons#5815]
Currently the Gardena Binding getting too many Access tokens, which will throw me out of the Gardena APP, forcing me to log off and login.

From gardena support I got this informaton:

Openhab Binding is login into Gardena every 2 Hrs. and therefore gets a new access and refresh token.

*Accestoken* is valid for 10 days
*Refreshtoken* is valid for 50 days

When the accesstoken has expired, the gardena app creates a new one with the help of the refresh token, so you do not have to log in again after 10 days.

If, however, in the meantime, 50 new refresh tokens were generated this is no longer valid and you have to log in again with username and password to get a new Refreshtoken.

Is there a way to adapt this in the Gardena binding to reduce this?

**Comment by nanosonde** [comment]
Hi!

I have also contacted the Gardena support to ask them why I always have to log off and login again.
They ask me if I am using a third-party application which accesses my Gardena account.
I acknowledged that I am using OpenHAB.

Here their answer: 

> OpenHUB ist ein OpenSource Projekt, was von GARDENA nicht unterstützt wird. Wir unterstützen es nicht in der Entwicklung (GARDENA bindings) und unterstützen das Projekt auch nicht von der Backendseite. Es gibt in developer Portal 3 APIs, Authentication, GARDENA Integration API und Husqvarna API für AMC Mower. In Authentication API ist beschrieben, wie man richtig mit den Tokens umgeht. Dieses Verhalten muss Implementiert werden. GARDENA wird es aber nicht tun.

Has the Gardena binding been adapted to their latest Authentication API?

**Comment by oliverlinsenmaier** [comment]
Hi!

I haven’t seen any change in that binding, nor any response. I can’t use this binding until it’s fix, unfortunately I’m not a developer, so I can’t really help.

This issue https://github.com/openhab/openhab2-addons/issues/5815 has the required information:

Openhab Binding is login into Gardena every 2 Hrs. and therefore gets a new access and refresh token.
Accestoken is valid for 10 days
Refreshtoken is valid for 50 days

Now we only need someone to adapt the binding according to Gardenas requirements.

Furthermore, Gardena should allow local access to the gateway in order to connect without the need of a cloud connection. But I don’t think this will happen in near future.

Best, Oli

Mail: OliverLins@web.de

**Comment by kaikreuzer** [comment]
@gerrieg Are you aware of these issues?

**Comment by nanosonde** [comment]
Hier scheint es Doku von Husqvarna zu geben: https://developer.1689.cloud/apis

**Comment by nanosonde** [comment]
Mhmm, looking at the Session class it seems that it does not use a refreshToken at all to get a new accessToken. 
So the binding should implement the standard [OAuth2](https://de.wikipedia.org/wiki/OAuth) way of handling this.

**Comment by gerrieg** [comment]
I am not aware of this, but it explains why I always have to login to the Gardena App.

I have tried the Husqvarna api, but i always get a 'Bad Request'. So I don't know how to do it right. The only thing I can implement is to always send the refresh_token with the login.

As a workaround you can try to increase the session timeout to something < 10 days. 
So configure the Thing and add: sessionTimeout=14000

**Comment by nanosonde** [comment]
@gerrieg 

The bottom part of this page explains more details:
https://developer.1689.cloud/apis/Authentication+API#/readme

If I understand it correctly, the [current binding code](https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.gardena/src/main/java/org/openhab/binding/gardena/internal/GardenaSmartImpl.java#L503) only does a login and never a logout which will cause the trouble. So you always request a new accessToken with every login.
```
Limits

We currently have the following limits on the Authentication API:

    Max 50 access tokens for a user. If more than 50 are created, the oldest one will be invalidated.
    Max 10 logins per minute.
    If more than 100 invalid login attempts are performed in a 5 minute window we will lock the account for 6 hours.```
```

Maybe a possible solution would be to logout the user again if the code is finished by invalidating the accessToken.
```
Invalidating a Token

For security reasons, you should always invalidate the token when it's not needed anymore.

async function logout(accessOrRefreshToken) {
  return fetch(`https://api.authentication.husqvarnagroup.dev/v1/token/${accessOrRefreshToken}`, {
    method: 'DELETE',
    headers: {
      'X-Api-Key': appKey
    }
  });
}
```

However, the proper way of handling this would be to store the accessToken+refreshToken (with its expiration times) and reuse it whenever possible. If the accessToken is about to expire, use the refreshToken to request a new accessToken. This could even survive restarts of OpenHAB.
I can confirm that I have also seen this approach in other products which communicate with a REST API.

The [linked](https://developer.1689.cloud/apis/Authentication+API#/readme) page describes everything that is needed and that the Gardena support means what needs to be fixed.

**Comment by gerrieg** [comment]
I've got it working now. I can login, logout, fetch locations and the device data.

BUT: It's impossible to implement this API, because the response is completely different. Also the device data are much less. For a mower i only get three attributes (state, activity, operatingHours).

So the only thing we can do is to increase the sessionTimeout and hope that it works.

**Comment by kaikreuzer** [comment]
> For a mower i only get three attributes (state, activity, operatingHours).

That indeed does not sound like an option for us. We will have to keep using the "unofficial" API...

**Comment by nanosonde** [comment]
@gerrieg Could you elaborate a bit more what information you are missing besides that the API response looks different?
From the Swagger definitions [here](https://developer.1689.cloud/apis/GARDENA+smart+system+API#/swagger) I can see that the following infos should be there: 

### CommonService:
- batteryLevel
- batteryState
- rfLinkLevel 
- serial
- modelType
- rfLinkState

### SensorService:
- soilHumidity
- soilTemperature
- ambientTemperature
- lightIntensity

### MowerService:
- state
- activity
- lastErrorCode
- operatingHours

There are other status services for the valve and the power socket.
Also the commands offer almost everything if I am not wrong.

This is what I do not see for the mower for example:
- collisions

**Comment by tarabas73** [comment]
just playing a bit with the API

Mower battery is available:

    "batteryLevel": {
      "value": 100,
      "timestamp": "2019-08-26T09:03:12.066+0000"
    },
    "batteryState": {
      "value": "OK",
      "timestamp": "2019-08-26T08:04:36.307+0000"
    },


Also all errors will be submitted:


value* | MowerErrorstringThis field should be paid attention to if the mower is in one of the two error states.NO_MESSAGE - No explanation provided.OUTSIDE_WORKING_AREA - Outside working area.NO_LOOP_SIGNAL - No loop signal.WRONG_LOOP_SIGNAL - Wrong loop signal.LOOP_SENSOR_PROBLEM_FRONT - Loop sensor problem, front.LOOP_SENSOR_PROBLEM_REAR - Loop sensor problem, rear.LOOP_SENSOR_PROBLEM_LEFT - Loop sensor problem, left.LOOP_SENSOR_PROBLEM_RIGHT - Loop sensor problem, right.WRONG_PIN_CODE - Wrong PIN code.TRAPPED - Trapped.UPSIDE_DOWN - Upside down.EMPTY_BATTERY - Empty battery.NO_DRIVE - No drive.TEMPORARILY_LIFTED - Mower lifted.LIFTED - Lifted.STUCK_IN_CHARGING_STATION - Stuck in charging station.CHARGING_STATION_BLOCKED - Charging station blocked.COLLISION_SENSOR_PROBLEM_REAR - Collision sensor problem, rear.COLLISION_SENSOR_PROBLEM_FRONT - Collision sensor problem, front.WHEEL_MOTOR_BLOCKED_RIGHT - Wheel motor blocked, right.WHEEL_MOTOR_BLOCKED_LEFT - Wheel motor blocked, left.WHEEL_DRIVE_PROBLEM_RIGHT - Wheel drive problem, right.WHEEL_DRIVE_PROBLEM_LEFT - Wheel drive problem, left.CUTTING_MOTOR_DRIVE_DEFECT - Cutting system blocked.CUTTING_SYSTEM_BLOCKED - Cutting system blocked.INVALID_SUB_DEVICE_COMBINATION - Invalid sub-device combination.MEMORY_CIRCUIT_PROBLEM - Memory circuit problem.CHARGING_SYSTEM_PROBLEM - Charging system problem.STOP_BUTTON_PROBLEM - STOP button problem.TILT_SENSOR_PROBLEM - Tilt sensor problem.MOWER_TILTED - Mower tilted.WHEEL_MOTOR_OVERLOADED_RIGHT - Wheel motor overloaded, right.WHEEL_MOTOR_OVERLOADED_LEFT - Wheel motor overloaded, left.CHARGING_CURRENT_TOO_HIGH - Charging current too high.ELECTRONIC_PROBLEM - Electronic problem.CUTTING_MOTOR_PROBLEM - Cutting motor problem.LIMITED_CUTTING_HEIGHT_RANGE - Limited cutting height range.CUTTING_HEIGHT_PROBLEM_DRIVE - Cutting height problem, drive.CUTTING_HEIGHT_PROBLEM_CURR - Cutting height problem, current.CUTTING_HEIGHT_PROBLEM_DIR - Cutting height problem, direction.CUTTING_HEIGHT_BLOCKED - Cutting height blocked.CUTTING_HEIGHT_PROBLEM - Cutting height problem.BATTERY_PROBLEM - Battery problem.TOO_MANY_BATTERIES - Battery problem.ALARM_MOWER_SWITCHED_OFF - Alarm! Mower switched off.ALARM_MOWER_STOPPED - Alarm! Mower stopped.ALARM_MOWER_LIFTED - Alarm! Mower lifted.ALARM_MOWER_TILTED - Alarm! Mower tilted.ALARM_MOWER_IN_MOTION - Alarm! Mower in motion.ALARM_OUTSIDE_GEOFENCE - Alarm! Outside geofence.SLIPPED - Slipped - Mower has Slipped.Situation not solved with moving pattern.INVALID_BATTERY_COMBINATION - Invalid battery combination - Invalid combination of different battery types.UNINITIALISED - Radio module sent uninitialised value. We do not know the status of the mower.WAIT_UPDATING - Mower waiting, updating firmware.WAIT_POWER_UP - Mower powering up.OFF_DISABLED - Mower disabled on main switch.OFF_HATCH_OPEN - Mower in waiting state with hatch open.OFF_HATCH_CLOSED - Mower in waiting state with hatch closed.PARKED_DAILY_LIMIT_REACHED - Mower has completed cutting due to daily limit reached.
-- | --

and API seems to run stable :-)

I've  implemented their python example and send some values to a mqtt server. No problems so far!

**Comment by erasedlight** [comment]
Looks like they fixed the issue. I'm using [Gardena2InfluxDB](https://github.com/sorny/gardena2influxdb) to get some history insights from the sensor readings and haven't been logged out of the app since Monday :)

**Comment by Rar9** [comment]
Fix? I unfortunately still have the same issue.

**Comment by nanosonde** [comment]
Currently this is supposed to be a workaround currently:
Set this in the binding config:

sessionTimeout=14000

**Comment by nanosonde** [comment]
This project provides a Python-based implementation of the official API now:
https://github.com/grm/py-smart-gardena

From this you can see what info you get and what is missing.

**Comment by hmerk** [comment]
closed due to inactivity
