### ISSUE TITLE
[mqtt.homeassistant] duplicate inbox entries

### ISSUE THREAD

**Issue by tavalin** [openhab/openhab-addons#5839]
## Expected Behavior

When I enabled homeassistant discovery on my zigbee2mqtt service I expected each device to be discovered only once in openHAB.  However, having waited a while and not approved the first inbox entry, another identical entry appeared.  
## Current Behavior

Devices generate multiple inbox entries.  This has also happened across multiple MQTT topics as per the picture below.

![image](https://user-images.githubusercontent.com/1771518/61314898-8ca59a00-a7f5-11e9-8f74-4e080d3d1026.png)

## Possible Solution

I don't have an IDE system up at the moment so I cannot confirm/diagnose the issue.  However my hypothesis is that the representation property is not being generated and/or set in [this](https://github.com/openhab/openhab2-addons/blob/master/bundles/org.openhab.binding.mqtt.homeassistant/src/main/java/org/openhab/binding/mqtt/homeassistant/internal/discovery/HomeAssistantDiscovery.java) class

## Steps to Reproduce (for Bugs)

1. Set up zigbee2mqtt and pair some devices
2. Install mqtt/mqtt.homeassisstant addon for openHAB
3. Set `homeassistant: true` in the zigbee2mqtt `configuration.yml`

## Your Environment

* Version used: (e.g., openhab and addon versions) openHAB 2.5 snapshot # 1639
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): Zulu Java 8
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Raspbian Buster (Raspberry Pi 4B)

**Comment by J-N-K** [comment]
Please try `bundle:update <number> https://janessa.me/esh/org.openhab.binding.mqtt.homeassistant-5839.jar`. Follow the instructions [here](https://janessa.me/esh/), sceond option.

**Comment by J-N-K** [comment]
Can you show the mqtt topics and please describe what you expect. I have the feeling that maybe there is something more broken than the duplicate entries. I don‘t have the necessary hardware to test.

**Comment by tavalin** [comment]
![image](https://user-images.githubusercontent.com/1771518/61829924-e3e4e380-ae61-11e9-99c3-58abe7954825.png)


Here's a screenshot from the MQTT broker/topics for the same devices shown in the screenshot above.  As mentioned, I wouldn't only expect these topics to create a single inbox entry for each topic but both `click ` and `linkquality` have created duplicate inbox entries. (actually I would prefer if the binding could bunch devices with the same IEEE address into the same Thing similar to what the Homie version does but that's not the issue I'm describing)

**Comment by J-N-K** [comment]
Ok, that helps. What i don‘t understand: `Click` seems to be a switch, why is it `sensor` and not `binary_sensor`?

**Comment by J-N-K** [comment]
@davidgraeff since you wrote that code: how is it supposed to work? the `component` is part of the `thingId`, this can never match a different component with the same `nodeId` or `objectId`. And the `objectId` seems to be more like a channel than part of the `thingId`, otherwise we always have one thing/channel.

**Comment by davidgraeff** [comment]
> actually I would prefer if the binding could bunch devices with the same IEEE address into the same Thing

That's complicated. Because one HA "config" topic already unfolds into multiple openHAB channels (light the light component which creates an on/off, brightness/color channel). If I want to merge all objectid associated components, I would need to introduce channel groups. And that's code wise a lot nastier that just create a Thing for each component of an objectid. If that makes sense.

> how is it supposed to work?

I have honestly no idea right now. HA is confusing with what they call a node and an object and I would need to get into that again first. A safe bet is to just combine nodeid and objectid for the thingid. But it wasn't me that touched the HA parts last. I just did the split of "MQTT All" to MQTT Generic, MQTT HA and MQTT Homie.

**Comment by tavalin** [comment]
I think I have got to the bottom of this one and it looks like user error so I'm sorry for wasted time.  I've just noticed I had duplicate broker Things and I think I was getting a discovery result for the same topic on each broker Thing e.g:

```
2019-07-29 22:17:18.919 [me.event.InboxRemovedEvent] - Discovery Result with UID 'mqtt:homeassistant:mymqttbroker:0x0017880103c929a5_linkquality_sensor' has been removed.

2019-07-29 22:17:21.539 [me.event.InboxRemovedEvent] - Discovery Result with UID 'mqtt:homeassistant:broker:0x0017880103c929a5_linkquality_sensor' has been removed.
```
