### ISSUE TITLE
[lutron] Sending large numbers of commands in a short window causes some to be missed

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#6012]
I have a command that shuts off all lights in the house when we go to bed.  I've noticed that randomly some lights don't shut off despite the item showing it's off.  I believe this is actually an issue with the caseta hub being flooded and not the OH implementation as the Lutron app also shows the switch as off.  The only thing I can think of to resolve this would be to put some sort of queue/delay between messages being sent to the hub.  

System is 2.5.0M2.

**Comment by bobadair** [comment]
Thanks @morph166955 . It’s certainly possible that the Caseta hub is having problems processing a large number of commands in a burst.  I haven’t heard of this particular problem before, and I don't have one myself, but I’ve seen reports from other users which lead me to believe that the implementation of Lutron Integration Protocol on the Caseta PRO hub is not as robust as the implementations on RadioRA 2, HomeWorks QS, etc.  Do you see any error responses from the hub?  You may have to enable debug level logging to tell.

Command are queued by IPBridgeHandler before being sent to the bridge device, but I don’t believe that any delay is introduced between them.  I’ll have to take a look at the code to see if something like that could be added.

With all of their systems, Lutron generally recommends that if you want to simultaneously control a large number of devices (such as with an “all on” or “all off” scene) that you define the scene in the controller and trigger it via the integration protocol rather than attempting to command each device separately via integration. In addition to cutting down on the integration protocol traffic, this allows the controller to synchronize the fade up/fade down of all of the devices involved, which for lights usually looks nicer. You can also use delays in the scene definitions to have switched devices go off exactly when dimmed devices finish fading down, or on when dimmed devices finish fading up (at least on RA2 and HWQS).  This also can look much nicer with lighting.

**Comment by bobadair** [comment]
Hi @morph166955. I've created a new test version of the Lutron binding that includes a "delay" parameter for the bridge thing. It can be used to set a delay (in milliseconds) between transmitting integration commands for send rate throttling.

I'm interested to hear whether or not this resolves the problem you saw.  I'd recommend starting with a delay value of around 100 ms, seeing if that fixes the problem, and then lowering it to 50, 25, 10, etc. until you see the problem start to occur again. Then try running for a while with a delay value set just above that where you saw the problem start to re-occur.  You can disable throttling totally by setting delay to 0.

The test build also includes the fix for 5898, and is available here:
https://github.com/bobadair/openhab2-addons/releases/tag/testfix090219

**Comment by morph166955** [comment]
I've loaded the binding and added the entry.  It's definitely visible when debugs are on that there is a delay between commands as compared to it before.  I'm going to run at 100 for a week and see if it misses.  

On the topic of running the scene on the hub versus in OH, it's mostly because I have 3 hubs that I prefer OH.  I have distance and device count issues here (78 switches across the two Casetas).  I have one hub per floor which seems to fix the distance issues.  The third hub is an RA2 and that is for my fan controls (I put everything in about a year before the Caseta fan control came out).  I could probably consolidate down to one Caseta hub from a device quantity perspective however I may still have range issues.  I prefer to keep the controls in OH simply so that I can tweak in my rules and not have to make changes on the lutron apps (which I can't do remotely).

**Comment by morph166955** [comment]
After a week I can say that this definitely was helpful.  I still have the occasional miss at 100ms.  I will probably dial it up to 125 to see if that fixes it.  Otherwise I would say 100% yes please commit this into the production train as it provides value.

**Comment by bobadair** [comment]
Thanks @morph166955. I've submitted a PR for the addition of the delay parameter. For now I've left the default at 0 (no delay). Please keep me updated on your testing. I'm interested to hear what value you settle on as the minimum delay that fixes your problem. You may want to consider starting a discussion about it in the user forum.

**Comment by morph166955** [comment]
Updated to M3.  There were a bunch of issues with having your test file in the addons folder when I started it.  I ended up having to remove the file, clear cache, restart (several) times and then, once the whole system was "calm" I was able to add the test file.  Subsequent restarts have not had any issues.  Otherwise, now that it's calm, it seems that things are working like normal.  For reference, the error that was generated on upgrade was.

```
2019-09-11 14:15:26.250 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/usr/share/openhab2/addons/org.openhab.binding.lutron-2.5.0-SNAPSHOT-testfix090219.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.lutron [209]
  Unresolved requirement: Import-Package: gnu.io; version="[3.14.0,4.0.0)"

        at org.eclipse.osgi.container.Module.start(Module.java:444) ~[?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) ~[?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1260) [10:org.apache.felix.fileinstall:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1233) [10:org.apache.felix.fileinstall:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:520) [10:org.apache.felix.fileinstall:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:365) [10:org.apache.felix.fileinstall:3.6.4]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:316) [10:org.apache.felix.fileinstall:3.6.4]
```

**Comment by bobadair** [comment]
Yeah, that error doesn't have anything to do with the changes to the binding code.  Sometimes the system just seems to have problems resolving that library when you load the binding from the addons folder.  If restarting doesn't clear it, I usually recommend going in to the console and executing the command “feature:install openhab-transport-serial”.  If it's working for you now, it should continue to work.

How is the system running with a delay value set?  Are you still using 100ms?

**Comment by bobadair** [comment]
Hi @morph166955. Were you ever able to test with a 50ms delay?  I've been hoping that a smaller delay value might work.

**Comment by bobadair** [comment]
The PR that adds the delay function has been merged. I will remove the pending label, but leave this issue open until there is some consensus on what the delay should be for various bridge devices.

**Comment by morph166955** [comment]
I've had mixed results under 100ms.  It seems to be dependent on how long the bridge has been up.  If I restart the hub, it works much more snappy for a few days.  Once it's been up for a while though it really gets a lag.  Is it possible to create a function of some kind where we can send a reboot command from openhab?  I could schedule it for 2AM or something along those lines.

**Comment by bobadair** [comment]
That's interesting. You may want to try reporting that to Lutron support and see what they say. They may ignore you, but I would want to hear about that if I were them.

As for rebooting the hub, you can try logging in to it via telnet and giving it the command "#RESET,0". I know that will trigger a reboot on RadioRA2 and HomeWorks. If it work on Caseta as well, you can use an expect script or something similar to schedule a reboot once in a while.

**Comment by bobadair** [comment]
Hi @morph166955. Have you come to any conclusions about the appropriate delay time to use on your Caseta system? I'm planning to create a PR for a doc update before 2.5.0 releases that, among other things, recommends using a delay value of 100 ms for Caseta, but only for users who experience problems.  Is that the value you are still using? After that I'll probably close this issue unless you see a reason to keep it open.

**Comment by morph166955** [comment]
100ms seems to be a sweet spot.  Under that still has the occasional misfire.  Above that seems to have no real effect.  I would leave it at 100 for now.

**Comment by bobadair** [comment]
Ok. Thanks. I'll go with 100 in the docs, then.
