### ISSUE TITLE
[deconz] Add support for blinds

### ISSUE THREAD

**Issue by cweitkamp** [openhab/openhab-addons#6212]
The deCONZ REST API added support for blinds (e.g. IKEA FYRTUR) couple of weeks ago (see [Supported Devices](https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices#others-supported-devices)). According to https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1121#issuecomment-529117242 it can be accessed via `/lights` resource (type `Window covering device`) and controlled by `state.bri` (0: open - 100: closed, step: 1) or `state.on` (false: open or true: closed).

Example:
```
{
  "etag": "c26cb3cb86b9c5a77211b6c724c364b4",
  "hascolor": false,
  "manufacturername": "IKEA of Sweden",
  "modelid": "FYRTUR block-out roller blind",
  "name": "Bathroom Blind",
  "state": {
    "alert": "none",
    "bri": 0,
    "on": false,
    "reachable": true
  },
  "swversion": "2.2.007",
  "type": "Window covering device",
  "uniqueid": "00:0d:6f:ff:fe:9e:00:aa-01"
}
```

Currently the deCONZ binding coexists with the Hue binding and we recommend to use them in combination to connect sensors or remote controls or lights and plugs to openHAB. deCONZ supports only devices exposed via `/sensor` resource, Hue supports both `/lights` and `/sensors`. Hue underlies the disadvantage to rely on a polling strategy whereas deCONZ uses websocket events.

How can we integrate blinds?

**Comment by davidgraeff** [comment]
I wrote the deconz addon, because at that time they didn't support sensors and the code base is old and crufty and not easy to work with. The last part hasn't changed unfortunately. A tidy up PR of mine collided with the sensor PR and got abandoned.
They do a lot of strange things (non conforming to the specification) especially in the init sequence.

I think at the moment we face the situation of two competing solutions. Either hue adds websockets or deconz keeps growing into a full replacement.

There are so many new zigbee devices that pop up (hue wall plugs for example). Any they are sensors and actors at the same time. If blinds are deconz specific (for the moment) I would add it here tbh.

**Comment by overdrive69** [comment]
Hi, any news on blinds?
I have a Ubisys J1 and have it connected to desconc. But as all the other zigbee devices i want to use it with openhab.

**Comment by olemr** [comment]
@overdrive69, guess we just have to interface with the deconz REST-API through http as we have to do with all other deconz groups for max performance. (openHAB native groups are slow, lights in a group turns on/off out of sync with up to several seconds).
PM me if you wan't more info on this.

**Comment by MHerbst** [comment]
I have an installation with deCONZ and the Ikea blinds. I am planning to add support for the blinds to the deCONZ binding.

**Comment by J-N-K** [comment]
@MHerbst, thanks a lot. I‘m planning to buy some of these, too.

**Comment by J-N-K** [comment]
@MHerbst any news on this one? I got one today.

**Comment by MHerbst** [comment]
@J-N-K I have started with the implementation but was very busy the last weeks. I hope to find more time this weekend. The binding needs some restructuring because currently it only handles "sensors" and ignores all other types. The blinds appear as "lights" (+ one "sensor" for the battery state).

**Comment by MHerbst** [comment]
@J-N-K I have seen your PR. It goes much further than I had planned and started with, but I like the idea of adding light support directly to this binding so that the "Hue bridge" is no longer necessary.

I already created added thing definitions for the blinds and had a working discovery. I now made a copy of your code and added my code to it. Discovery for the blinds is working and the "up" and "down" commands are also working. 

"Stop" is a bit more complicated because I need to know the last executed command and have to send the same again.

BTW: do you have an idea about how to handle the battery state? deconz uses an additional sensor of type "ZHABattery" for it. The easiest option would be a separate thing.

**Comment by J-N-K** [comment]
@MHerbst, I have implemented the blinds and also the stop command, please have a look. I‘ll provide a test jar in the next few days, I‘m a bit unsure about the color lights, I don‘t own them, so no way to test them.

The battery is difficult, I‘ll have to check if it is possible to link the battery sensor device to the light device. 

Can you send me the full config of your system? My email-address in the sign-offs is valid.

**Comment by MHerbst** [comment]
@J-N-K I have pulled your latest changes and started to test the blinds. I found a problem with the stop command. It works if the blinds are going up but now while going down (it's because `lightState.on` and `lastCommand` are both "true"). I had implemented it in this way which worked without storing the last command and it allows to stop the blind even if the command was given by the remote control.

```
            case CHANNEL_POSITION:
                if (command instanceof UpDownType) {
                    newlightState.on = (command == UpDownType.DOWN);
                } else if (command instanceof PercentType) {
                    newlightState.bri = (int) (((PercentType) command).doubleValue() * 2.55);
                } else if (command instanceof StopMoveType) {
                    if (lightState.on && lightState.bri <= 254) { // going down or currently stop (254 because of rounding error)
                        newlightState.on = true;
                    } else if (!lightState.on && lightState.bri > 0) { // going up or currently stopped
                        newlightState.on = false;
                    }
                }
```
I have got two RGB stripes and I can test the binding with them. I have made a first test and the binding correctly discovered a "Dimmable Light" (just für white) and an "LED Strip". This is correct.
When I try tho change the "brightness" of the "Dimmable Light", I get a NPE
```
java.lang.NullPointerException: null
	at org.openhab.binding.deconz.internal.handler.LightThingHandler.handleCommand(LightThingHandler.java:143)
```
After a bit playing around the NPE no longer occurred and I could set the brightness.

BTW: maybe it makes sense to add a separate switch to switch the light on or off. Setting the brightness to 0 is not the same a switching the light off (or you can set the "on" state to off if brightness is set to 0).

Changing the settings of the "LED Strip" works but the results seem not to be correct. Will try to debug it. There is also a warning message: "19:54:34.004 [safeCall-10] WARN  o.o.b.d.i.handler.LightThingHandler:121 - Failed to convert 0,62,40 to xy-values
"

> The battery is difficult, I‘ll have to check if it is possible to link the battery sensor device to the light device.

The battery seems to have the same uniqueid as the blind plus a suffix "-0001". Probably it is easier to simply create a separate thing for the battery. 

> Can you send me the full config of your system? My email-address in the sign-offs is valid.

Yes of course.

**Comment by J-N-K** [comment]
I habe fixed the NPE and changed the STOP code to your version. Battery level is also implemented. I would prefer to keep them separate (as you also suggested), that makes it more generic and will probably also work with other manufacturers.

**Comment by MHerbst** [comment]
@J-N-K Did some quick tests with your latest sources. Here are my results:
- Stop works for up/down but unfortunately not if you set the position to a value and then try to stop (will have a look at it)
- In Paper UI the position does not show a value when I open the "Control" page and it is not updated automatically. After a refresh of the page it works (maybe a problem of Paper UI).
- Battery level is OK
- The NPE for brightness no longer appeared and the "Dimmable light" (white only) seems to work perfectly. The displayed brightness in Paper UI ist automatically updated if it is changed via the Phoscon App.
- The LED Strips generally work, but the displayed values in Paper UI are not updated if they are changed via the Phoscon App, because not all channels are implemented yet. This is a message received via the Web Socket:
```
19:23:47.637 [nz-6a7f28bc-190] DEBUG o.o.b.d.i.handler.LightThingHandler:310 - deconz:extendedcolorlight:6a7f28bc:00212effff0390d30a received LightState{lastupdated='null', reachable=true, on=true, bri=180, alert='null', colormode='xy', effect='null', hue=11393, sat=126, ct=200, xy=[0.3497, 0.4008]}
```

There are also some other errors  appearing:

There were some NPEs (similar to the solved problem with brightness):
```
18:58:02.642 [safeCall-5] ERROR o.e.s.c.i.c.AbstractInvocationHandler:100 - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.deconz.internal.handler.LightThingHandler@7c64fbae': null
java.lang.NullPointerException: null
	at org.openhab.binding.deconz.internal.handler.LightThingHandler.handleCommand(LightThingHandler.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

I also saw these messages several times:

``` 
18:58:07.064 [safeCall-5] WARN  o.o.b.d.i.handler.LightThingHandler:120 - Failed to convert 248,0,0 to xy-values
```
As far as I can see it would be sufficient to use only the "hue" value. I have tried it and it worked perfectly. After sending a first PUT request with "hue" the colormode returned by deconz changed to "hs". It seems that "xy" is the default and it is used by the Phoscon web app.

This warning also appears regularly:

```
19:34:21.046 [ient-common-178] WARN  o.o.b.d.internal.types.LightType:53 - Unknown light type 'Configuration tool' found. This should be reported.
19:34:21.216 [ient-common-178] WARN  o.o.b.d.i.d.ThingDiscoveryService:137 - Found light: ConBee II (Configuration tool 3), type UNKNOWN but no thing type defined for that type. This should be reported.
```
I think this could be suppressed.

**Comment by J-N-K** [comment]
I think I fixed those issues. Can you check with the latest jar in the attached PR?

**Comment by MHerbst** [comment]
@J-N-K instead of the jar I am using the latest source from your repo.

The following problems are open:

- Blinds: I have tried again to top the movement if a percent value is set but it seems that it is not possible. I have tried different combinations of values in the JSON message but none of them worked. We probably can ignore it and maybe add a hint to the documentation about this behavior.
- The "Dimmable Light" (white only) generally works., but if the brightness is set to "0" via the slider in Paper UI sometimes an error is returned. 

This happens because sometimes two messages are sent to deconz (because this is only visible if TRACE is activated it probably can be ignored):
```
19:43:46.574 [safeCall-6] TRACE o.o.b.d.i.handler.LightThingHandler:199 - Sending {"on":false,"bri":0} to light 7
19:43:46.577 [ient-common-180] TRACE o.o.b.d.i.handler.LightThingHandler:202 - Result code=200, body=[{"success":{"/lights/7/state/on":false}},{"success":{"/lights/7/state/bri":0}}]
19:43:46.581 [nz-c291659a-189] TRACE o.o.b.d.i.handler.LightThingHandler:303 - deconz:dimmablelight:c291659a:00212effff0390d30b received LightState{lastupdated='null', reachable=true, on=false, bri=0, alert='null', colormode='null', effect='null', hue=null, sat=null, ct=null, xy=null}
19:43:46.921 [safeCall-6] TRACE o.o.b.d.i.handler.LightThingHandler:199 - Sending {"bri":0} to light 7
19:43:46.924 [ient-common-178] TRACE o.o.b.d.i.handler.LightThingHandler:202 - Result code=200, body=[{"error":{"address":"/lights/7","description":"parameter, /lights/7/bri, is not modifiable. Device is set to off.","type":201}}]
```
- For the "extendcolorlight" most things work perfectly now, but I found one problem with the "color temperature": after you have changed the "color temperature" it is no longer possible to modify the color. I had to use the Phoscon PWA to make it work again. This is the trace output.:

Set "Color Temperature" to 50
```
20:00:55.695 [safeCall-1] TRACE o.o.b.d.i.handler.LightThingHandler:199 - Sending {"colormode":"ct","ct":326} to light 6
20:00:55.699 [nz-c291659a-189] TRACE o.o.b.d.i.handler.LightThingHandler:303 - deconz:extendedcolorlight:c291659a:00212effff0390d30a received LightState{lastupdated='null', reachable=true, on=true, bri=254, alert='null', colormode='ct', effect='null', hue=43690, sat=254, ct=326, xy=[0.1542, 0.0623]}
20:00:55.703 [ient-common-173] TRACE o.o.b.d.i.handler.LightThingHandler:202 - Result code=200, body=[{"success":{"/lights/6/state/ct":326}}]
20:00:57.382 [nz-c291659a-188] TRACE o.o.b.d.i.handler.LightThingHandler:303 - deconz:extendedcolorlight:c291659a:00212effff0390d30a received LightState{lastupdated='null', reachable=true, on=true, bri=254, alert='null', colormode='ct', effect='null', hue=7796, sat=186, ct=326, xy=[0.432, 0.4026]}
```
Tried to change brightness:
```
20:02:01.767 [safeCall-3] TRACE o.o.b.d.i.handler.LightThingHandler:199 - Sending {"bri":96} to light 6
20:02:01.771 [ient-common-176] TRACE o.o.b.d.i.handler.LightThingHandler:202 - Result code=200, body=[{"success":{"/lights/6/state/bri":96}}]
20:02:01.773 [nz-c291659a-190] TRACE o.o.b.d.i.handler.LightThingHandler:303 - deconz:extendedcolorlight:c291659a:00212effff0390d30a received LightState{lastupdated='null', reachable=true, on=true, bri=96, alert='null', colormode='ct', effect='null', hue=7796, sat=186, ct=326, xy=[0.432, 0.4026]}
```
This worked.

Now I change the Color in PaperUI:
```
No trace output
```
The reason is the "switch" statement in line 130 of `LightThingHandler`. After the "Color Temperature" was changed, the `colormode` variable contains "ct", so always the "default" case is executed. I think you can solve it by changing the "if" in line 125 to `if (colormode == null || "ct".equals(colormode))`. With this change, you can modify the color again. But it seems that the hue value is somehow "undefined" after the switch to "ct". If I change the color with the slider, the LED strip changes its color correctly, but the slider in PaperUI moves back to the left. After changing its position again, everything works fine.

- Every few minutes this warning appears: 
```
19:50:04.345 [ient-common-182] WARN  o.o.b.d.i.d.ThingDiscoveryService:137 - Found light: ConBee II (Configuration tool 3), type CONFIGURATION_TOOL but no thing type defined for that type. This should be reported.
```

**Comment by MHerbst** [comment]
@J-N-K Today, I found some time to test the latest version. Most of my issues are solved now. Therefore I have built a jar and installed it in my production environment. The blinds are working perfectly but changing the colors of the LEDs has some problems. After clicking into the color wheel the circle jumps back to the old position and after about 1, 2 seconds it jumps near the position that I have clicked. You can see it in this video https://cloud.mherbst.de/public/294a04209b97 .

If it helps I can enable the trace and attach it here.

**Comment by J-N-K** [comment]
I already know the problem. After sending the color, I get an acknowledge and immediately after that a state message with the old state. After some time the new state is send (probably when either a time has elapsed or the fional state is reached).

Maybe it would be a good idea to drop the first state message after a command if it is received within 100ms or so.

**Comment by MHerbst** [comment]
With the latest commit it works perfectly.
