### ISSUE TITLE
[samsungtv]  Tv configured via Thing file duplicated by discovery and permission issue

### ISSUE THREAD

**Issue by francemgit** [openhab/openhab-addons#6317]
OpenHab 2.5.0 Snapshot version running on Pi 4.
TV Samsung 6 Series55.

Bindings works perfectly using websocket but: 

- my Tv defined via configuration file is discovered during search but and marked as NEW and not IGNORED. Any issue with "representation property" to get auto-ignore working?
- each time i turn on TV (via openHab or through remote) the TV keep asking for OpenHab permission 

Marco

**Comment by jaywiseman1971** [comment]
RE: each time I turn on TV, the TV keep asking for OpenHab permission

I have the same thing happening ONLY when I restart OH on one (newest one) of my 8 Samsung TVs.

Best, Jay

**Comment by Cossey** [comment]
When openHAB restarts I also get a Permission Prompt on the TV, definitely an issue in implementation (unless TV firmware has updated since my last check and does something different in the websocket implementation). 

I recall in testing with a direct Websocket to the TV a while back that as long as I specified correct token and app name in the remote control api URL it would remember permissions.

@jaywiseman1971 Do you have an N series TV among those 8? If so, does your TV have issues with Powering On/Off not always working consistently? How its implemented in the binding and how the Websocket Protocol works needs some additional tweaking which I'm planning on working on (the TV needs to either be sent the TV_POWER command over Websocket or a Wake on LAN packet; the web socket service still runs up to 30-90 after power off which means that the WoL approach won't work until the API service dies).

**Comment by jaywiseman1971** [comment]
Hi @Cossey.

Here's my problem TV which is the newest one.

Brand : Samsung
Model : UN65MU6290  (bought from Costco)

1) Asks permissions whenever I restart OH
2) Can power it ON from OH but can't power it OFF

Defined in THINGS as

Thing samsungtv:tv:basementwired	"Samsung Basement Wired"	[ hostName="192.168.0.128", port=8002,  refreshInterval=15, macAddress="xx:xx:xx:xx:xx:xx" ]

Best, Jay

**Comment by francemgit** [comment]
Still present with latest snapshot 2.5.0. 

Each time the TV is turned on is discovered as new thing (although already present via configuration file):

`[home.event.InboxAddedEvent] - Discovery Result with UID 'samsungtv:tv:.........`

Each time the TV is turned off the inbox discovered one is removed:

`[me.event.InboxRemovedEvent] - Discovery Result with UID 'samsungtv:tv:.........`

The TV keep asking permission while powered.

Best,
Marco

**Comment by Cossey** [comment]
@francemgit Noted.

@jaywiseman1971 Looks like your TV is a 2017 model. Might be missing the `protocol="WebSocket"` or `protocol="SecureWebSocket"` setting in your Thing config, this was only implemented in 2.5.0.M2 onwards.

**Comment by jaywiseman1971** [comment]
Re: protocol="WebSocket" or protocol="SecureWebSocket"

Can someone provide the documentation where this is referenced?  I'm not using either of these in my THING config.

`Thing samsungtv:tv:basementwired	"Samsung Basement Wired"	[ hostName="192.168.0.128", port=8002,  refreshInterval=15, macAddress="9c:8c:6e:69:b6:fe" ]`

Best, Jay

**Comment by webhamster2000** [comment]
> Can someone provide the documentation where this is referenced? I'm not using either of these in my THING config.

I can't point to documentation, but I can verify that the protocol-parameter is used and working (OH 2.5)

**Comment by francemgit** [comment]
Update to OH 2.5.2, issue still present.
Trying to make some test, issue seem to be related to OH installation of plugin openhab-core-io-transport-upnp that is needed by other bindings I have.

Marco

**Comment by jaywiseman1971** [comment]
Please be aware that there is some fundamental issues with the SamsungTV Binding and jUpNp that is trying to be worked out.

https://github.com/openhab/openhab-addons/issues/5892

Best, Jay

**Comment by francemgit** [comment]
Made some test today and partially resolved my issue.

I've removed the protocol and port parameters from things file, the binding auto select secure websocket.
All works perfectly and stopped asking permission each time i turn on tv.

Auto discovery still find and remove a copy of the TV in the inbox each time i turn on and off, it's annoying but not a serius issue :) 

Marco

**Comment by hmerk** [comment]
closed
