### ISSUE TITLE
[mqtt] Homie $name did not receive

### ISSUE THREAD

**Issue by mjcumming** [openhab/openhab-addons#6691]
@davidgraeff 

When using a large number of Homie devices, OH will complain about not receiving the $name property. If I restart the Homie controller which will resend all the Homie device info, OH recognizes the devices. My guess is that the timeout waiting for the $name property is too short.

**Comment by davidgraeff** [comment]
That's the case. The idea is to start/reset the timeout each time a useable value got received to prevent those kind of errors. I didn't come to implement this yet though

**Comment by bodiroga** [comment]
This can be closed! :+1:

**Comment by RayBa82** [comment]
I still have this issue, for me the problem is not solved.
The timeout seems to be far too low. I have 15 homie devices and if I reboot openhab most of them are still displayed as offline, with the same error message.

I have to restart my homie devices, sometimes 5 or 6 times until openhab recognizes them again as offline.

**Comment by manswiss** [comment]
The problem happens by me also in 2.5.3. And the $name is retained.

**Comment by mjcumming** [comment]
Agree, I am still seeing this issue in 2.5.2. I have a little over 400 Homie devices. 

When I restart OpenHAB it continues to discover/enumerate Homie devices for 5 or more minutes. Compared to MQTT Explorer which populates the Homie tree in a second.
