### ISSUE TITLE
[plugwiseha] Unhandled Exception 

### ISSUE THREAD

**Issue by lsiepel** [openhab/openhab-addons#6781]
Once in a while i see this WARN message (using 2.5.0 stable) and the binding version from the initial contribution. 

`2019-12-28 18:45:14.202 [WARN ] [rnal.handler.PlugwiseHABridgeHandler] - Unhandled exception while refreshing the Plugwise Home Automation Controller plugwiseha:gateway:home - null`

Maybe it should be handled in some way that it 1. tells me what is wrong or 2. give a possible solution or 3. set it to debug if it is not affecting the usage of the binding at all.

**Comment by QNimbus** [comment]
I agree with you that this message should probably be logged as 'debug'. I have changed it to prevent this nuissance log message since it doesn't affect the usage of the binding. I will force-push this change into the most recent pull request.

I will have to look into the exact problem that is causing the exception to be thrown - it's on my TODO list.
