### ISSUE TITLE
[astro] Radiation calculation wrong?

### ISSUE THREAD

**Issue by HarrysLapTimer** [openhab/openhab-addons#6808]
I think radiation calculation is wrong in some way. Both direct and diffuse radiation calculated start late and end early. As an example, both radiation values were zero this morning until the sun's elevation has been +3.5 degree, i.e. above horizon.

Expected behavior: direct radiation should go above zero at start of sun raise; diffuse radiation should go above zero at start of astroDawn (or latest once direct radiation is above zero)

Same for dusk in reverse order.

Observed using a lat/lon in Northern Germany, 11th January 2020. All values mentioned above where displayed in PaperUI, so sun elevation / raise / radiation are from the same source.

**Comment by HarrysLapTimer** [comment]
Probably related, the phase name has switched late too. During the scene described, the phase showed SUN_RISE although rise.end has been passed already.

**Comment by clinique** [comment]
@HarrysLapTimer : this behaviour is by design in the code : 

`double rOut = (elevation > 3) ? SC * (0.034 * Math.cos(DEG2RAD * (360 * dayOfYear / daysInYear)) + 1) : 0;`

[Here](http://www.plevenon-meteo.info/technique/theorie/enso/ensoleillement.html)'s the source I used - that states : "Note that this sunshine calculation only applies when the sun's inclination is greater than 3 °. Indeed, as the sunrise / sunset approaches, the precision limits of these calculations are reached"
