### ISSUE TITLE
[shelly] Rollershutter position is wrong

### ISSUE THREAD

**Issue by BenSawary** [openhab/openhab-addons#6813]
Hello,

first of all I'd like to thank all of you, for this excellent work here :)

Today I noticed a problem with the Rollershutter Item. I'm using the shelly-binding and the channel events are the following:

2020-01-11 19:52:39.947 [vent.ChannelTriggeredEvent] - shelly:shelly25-roller:c4a2de:roller#event triggered ROLLER_CLOSE
2020-01-11 19:52:45.822 [ome.event.ItemCommandEvent] - Item 'Jalousie_LivingRoom' received command STOP
2020-01-11 19:52:46.042 [vent.ChannelTriggeredEvent] - shelly:shelly25-roller:c4a2de:roller#event triggered ROLLER_STOP
2020-01-11 19:52:46.913 [vent.ItemStateChangedEvent] - Jalousie_LivingRoom changed from 100 to 10.0
2020-01-11 19:52:46.959 [vent.ItemStateChangedEvent] - Jalousie_LivingRoom_Position changed from 100.0 to 90.0
2020-01-11 19:52:46.967 [vent.ItemStateChangedEvent] - Jalousie_LivingRoom changed from 10.0 to 90.0

My item-binding are the following:

Rollershutter Jalousie_LivingRoom "Jalousie [%d]" <rollershutter> (gLivingRoom)
    {channel="shelly:shelly25-roller:c4a2de:roller#control"}

Dimmer Jalousie_LivingRoom_Position "Jalousie Position [%d]" <rollershutter> (gLivingRoom)
    {channel="shelly:shelly25-roller:c4a2de:roller#rollerpos"}

In this case I would expect an open roller shutter with the value 10 on control channel and 90 on rollerpos channel. The last unexpected event leads to the problem.

<img width="1096" alt="Bildschirmfoto 2020-01-11 um 20 05 30" src="https://user-images.githubusercontent.com/59067902/72209391-c65a1380-34ad-11ea-8c51-3d52e7f4cc74.png">

My openHAB and shelly-binding version is 2.5.0

**Comment by F43RY** [comment]
Same here.
This is Markus7017 answer:
https://github.com/markus7017/org.openhab.binding.shelly/issues/21#issuecomment-573338156
Since in the Shelly 2.5 interface we can set direction (shown in the following printscreen), why do we need two inverted controller (control and rollerPos) ? 
![settings](https://user-images.githubusercontent.com/4217502/72212192-ccfd8080-34d7-11ea-841e-f70811315028.png)
In my opinion "control" should work with UP/STOP/DOWN (or OPEN/STOP/CLOSE) and rollerPos with values in range 0-100 where 0=Open and 100 = closed as in control, not inverted).

**Comment by markus7017** [comment]
> Since in the Shelly 2.5 interface we can set direction (shown in the following printscreen), why do we need two inverted controller (control and rollerPos) ?

Because the are UI controls (e.g. a HABpanel widget I'm using), which work with inverted values.
