### ISSUE TITLE
[homematic] Things sometimes have configuration errors after startup

### ISSUE THREAD

**Issue by s0170071** [openhab/openhab-addons#6816]
I run an RPi4 with piviccu (3.49.17 = latest) and OH2.5.0.-1 . 
When I reboot the RPi, all homematic things show configuration error in PaperUI and do not recover  for hours. They are not responding to rules either, of course.

If I then do "sudo systemctl restart openhab2.service" everything runs smoothly for weeks.
Looks like some race condition on startup...

**Comment by MHerbst** [comment]
If you star piviccu and openHAB at the same time there will of course be error messages because the Homematic binding tries to connect to the CCU but won't not get a valid answer if piviccu is not completely started.

To mitigate the problem, you could make sure that openHAB only starts after piviccu has been completely started.

However, I still don't quite understand why it takes hours until everything works correctly. Can you turn on the trace log for the Homematic binding and then restart the RPi. It would be interesting to see what is output in the log file. The logs should last a few minutes.

**Comment by s0170071** [comment]
@MHerbst 
1. I have no problem with messages. That is totally normal, I know. 
2. Even at simultaneous startup, things should work eventually without manually interference. At least they used to with OH 2.3
3. It took hours because at that point I did restart OpenHab. Could have done it sooner. What I wanted to say is, that if I didn't restart it, it would have malfunctioned forever.

Isn't there a way to delay OpenHab until piViCCU is up ? A fixed delay time would do for now.

**Comment by MHerbst** [comment]
> Even at simultaneous startup, things should work eventually without manual interference. At least they used to with OH 2.3

I agree. I will test what happens with my external CCU if it is offline while openHAB is started. Normally the binding should automatically try to reconnect every some minutes. Are there any messages in the log that may help to find out why this happens. You may have to active the TRACE for the Homematic binding.

> Isn't there a way to delay OpenHab until piViCCU is up ? A fixed delay time would do for now.

You could try to modify the systemd service definition for openHAB and an after condition for the piviccu service. Then it will start after piviccu has been started. But I am not sure whether this will be sufficient.
>

**Comment by s0170071** [comment]
I tried the systemd` After:` option. It seems to start OH after piviccu, but that did not solve the problem. I now created a watchdog like workaround in which I toggle an output of a Homematic-wired module- read it back through another pin - and when either error count (failed to turn on / off ) exceeds 10 I start from a rule: 

`executeCommandLine("sudo@@systemctl@@restart@@openhab2"`

The set up guide is [here](https://community.openhab.org/t/beginners-guide-to-an-openhabian-reboot-shutdown-switch/71903):
Just note, that the systemctl command sits in /cmd/bin and not in /cmd/sbin, so the line to add according to the guide is: 
```
# Allow openhab user to execute reboot and poweroff commands
openhab   ALL=(ALL) NOPASSWD: /sbin/reboot, /sbin/poweroff, /bin/systemctl restart openhab2
```
This is not ideal but at least it starts the system into an operational state without manual interaction.

**Comment by lsiepel** [comment]
As there is no comment for this three year old issue, can i assume it has been fixed in the mean time? I do see [several homematic PR's](https://github.com/openhab/openhab-addons/pulls?q=is%3Apr+homematic+in%3Atitle+created%3A%3E2020-01-12) since creating this issue including some regarding the connection logic.  Could you check if this is still a problem with openHAB 3.4.0 or close this issue?
