### ISSUE TITLE
[somfytahoma] Unable to change state of myfox://SOMFY_PROTECT

### ISSUE THREAD

**Issue by ghost** [openhab/openhab-addons#6989]
## Expected Behavior
Changing alarm state between arm, disarm and partial should be reflected on Somfy Protect

But the API returns 
        "failureTypeCode": 608,
        "name": "ExecutionStateChangedEvent",
        "failureType": "NETWORK_SERVICE_UNAUTHORIZED"

More information in attached file  
[test_json.txt](https://github.com/openhab/openhab-addons/files/4177853/test_json.txt)

## My Environment
* Version used: openHAB stable version 2.5 - somfytahoma binding version 2.5.2-SNAPSHOT
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): MacOS

**Comment by lsiepel** [comment]
As this is a three year old issue. It might allready have been fixed. Since this issue was created [49 PR's have been merged](https://github.com/openhab/openhab-addons/pulls?q=is%3Apr+somfytahoma+in%3Atitle+created%3A%3E2020-02-09) 
As 2.5.x is no longer supported, can you verify if this is still an issue with latest stable 3.4.0 ?
