### ISSUE TITLE
[unifi] Online channel not working after upgrading UniFi Controller to 5.12.35

### ISSUE THREAD

**Issue by ljsquare** [openhab/openhab-addons#7001]
## Expected Behavior
As documented, when a device connects to the unifi network, it suppose to give a online/offline status

## Current Behavior
It doesn't update the online/offline status anymore

## Context
It is reported on the form: https://community.openhab.org/t/online-channel-not-working-after-upgrading-unifi-controller-to-5-12-35

## Your Environment
OpenHAB 2.5.1
Unifi controller 5.12.35
OpenHabian

**Comment by mhilbush** [comment]
@mgbowman After upgrading the controller to 5.12.35, I have one thing whose online channel is working, and another thing whose online channel is not working. Very strange.

For the device whose `online` channel is not working, I can see the `uptime`, `lastSeen`, and `rssi` channels being updated after the device disconnects from the wifi, so clearly the binding thinks the device is still connected.

**Comment by mhilbush** [comment]
One additional thing... I went into the "Insights" view on the controller, then "Forgot" the entry for the device whose `online` channel was not updating. After that, the `online` channel started working again.

**Comment by pbyrne-ms** [comment]
Not sure if this is related, but I was having similar issues with three switch items I had defined to track the 'online' state of our phones. I noticed the labels I'd given my switch items had apostrophes in the text e.g. "Max's Phone" - when removed the apostrophes, the switch items began working again!

**Comment by jlaur** [comment]
I think the issue here is how the binding correlates the configured client id with information obtained from the controller:

> **cid:** The MAC address, IP address, hostname or alias of the client

It seems this **id** is exclusively used to match any client from a number of different properties. Example for IP-based configuration which hasn't worked since pre-Corona (5.12.35):

```
2021-10-13 22:33:38.799 [INFO ] [openhab.event.ItemStateChangedEvent ] - Item 'UniFi_OnePlus8_Jacob_MacAddress' changed from NULL to xx:xx:xx:xx:1a:79
2021-10-13 22:41:52.188 [DEBUG] [i.internal.api.model.UniFiController] - Found 22 UniFi Insights(s):
 - UniFiClient{mac: 'xx:xx:xx:xx:1a:79', ip: 'null', hostname: 'oneplus-8', alias: 'null', wired: false, blocked: false, device: null}
 - UniFiClient{mac: 'xx:xx:xx:xx:69:03', ip: 'null', hostname: 'oneplus-8', alias: 'null', wired: false, blocked: false, device: null}
 - UniFiClient{mac: 'xx:xx:xx:xx:8d:15', ip: 'null', hostname: 'oneplus-8', alias: 'null', wired: false, blocked: false, device: null}
 2021-10-13 22:41:52.308 [TRACE] [.internal.api.cache.UniFiClientCache] - Cache MISS : 'mac:192.168.0.28'
2021-10-13 22:41:52.310 [TRACE] [.internal.api.cache.UniFiClientCache] - Cache MISS : 'ip:192.168.0.28'
2021-10-13 22:41:52.312 [TRACE] [.internal.api.cache.UniFiClientCache] - Cache MISS : 'hostname:192.168.0.28'
2021-10-13 22:41:52.313 [TRACE] [.internal.api.cache.UniFiClientCache] - Cache MISS : 'alias:192.168.0.28'
2021-10-13 22:41:52.315 [TRACE] [.internal.api.cache.UniFiClientCache] - Cache MISS : 'mac:192.168.0.28'
2021-10-13 22:41:52.316 [TRACE] [.internal.api.cache.UniFiClientCache] - Cache MISS : 'ip:192.168.0.28'
2021-10-13 22:41:52.318 [TRACE] [.internal.api.cache.UniFiClientCache] - Cache MISS : 'hostname:192.168.0.28'
2021-10-13 22:41:52.319 [TRACE] [.internal.api.cache.UniFiClientCache] - Cache MISS : 'alias:192.168.0.28'
2021-10-13 22:41:52.321 [DEBUG] [i.internal.api.model.UniFiController] - Could not find a matching client for id = 192.168.0.28

```

Previously **ip** was probably included in response for offline clients, but this is not the case anymore, thus IP-based matching is no longer supported by the binding.

To fix this, the binding could use its cache of multiple properties and make sure to store **_id** in the client cache also. So instead of looking up **cid** directly in current client list (offline scenario):
- 192.168.0.28 -> match this **ip** in response -> failure since not present

it could approach it like this:
- 192.168.0.28 -> match this **ip** in client cache -> **id** 5eb92b8246e0fb00169dc7c8 -> match this **id** in response

In scenario where client is offline when binding is started, cache would be incomplete as we never received all information as for online clients. So we need to maintain the cache, so that IP and other properties will be added for the client id when it becomes available. We will need it when client goes offline once again.

I might not yet have understood all details, only spent 1-2 hours looking at trace logs and code, so please correct any misunderstandings.

Last note, hostname is not DNS host, but something provided by the client. Example:
      "hostname": "OnePlus-8", 

This is then lowercased into "oneplus-8" by the binding. But it's not a real hostname, and it's not unique. I haven't tried configuring a client with it, but it would probably not work well as we have two of those in the house. MAC address might be dynamic nowadays. Which leaves IP address and alias.

Cc @mgbowman

**Comment by jlaur** [comment]
I verified by trying out a very simple temporary fix, which appears to work:

In this method in UniFiController:

```
private UniFiClientCache getClients(UniFiSite site) throws UniFiException {
        UniFiControllerRequest<UniFiClient[]> req = newRequest(UniFiClient[].class);
        req.setAPIPath("/api/s/" + site.getName() + "/stat/sta");
        UniFiClient[] clients = executeRequest(req);
        UniFiClientCache cache = new UniFiClientCache();
        if (clients != null) {
            logger.debug("Found {} UniFi Client(s): {}", clients.length, lazyFormatAsList(clients));
            for (UniFiClient client : clients) {
                cache.put(client);
            }
        }
        return cache;
    }
```

Replace fifth line by:
```
        UniFiClientCache cache = clientsCache;`
```

This will reuse existing cache instead of creating a new one. `cache.put` will replace any existing client with same key (it's implemented as HashMap).

**Comment by kniight** [comment]
I had the similar problem. In my case the Unifi controller and the OpenHab are two different systems.

The problem was that the controller lost the NTP time sync, ans slowly drifted away. The time difference became slowly more than the online time I specified and online became always OFF. 
(The last seen time was updated correctly in every few minutes, but it was always 15 minutes behind the actual timestamp.)

Would it be possible to ask for the current time of the Unifi controller?  If yes, it could be used for base of comparison.
