### ISSUE TITLE
[homekit] Dimmers not discovered by Homekit

### ISSUE THREAD

**Issue by kallioaleksi** [openhab/openhab-addons#7057]
## Expected Behavior

Homekit should show a light accessories with on/off and sliders for each light ("Bedroom light", "Livingroom light" etc), and the lighting group switch as an on/off switch

## Current Behavior

Only the lighting group switch, temperature and moisture sensors are shown, the dimmers are not discovered at all.

I set the log level to trace, but no logs were output when I added OH as a bridge.

## Steps to Reproduce (for Bugs)

1. Configure OH to use lights as Dimmer items
2. Add OH to Homekit
3. Check the accessories discovered by Homekit

## Context

I'm trying to move from Hue Bridge and Aqara Hub and all other Zigbee hubs to zigbee2mqtt, and everything else is working great except Homekit.

My several Hue lights are defined like this:
`Dimmer Bedroom_Light "Bedroom light" <light> (Home, Bedroom, gLight) ["Lighting"] {channel="mqtt:topic:id:channelName"}`
In addition to these there's a group on/off switch defined like this:
`Group:Switch:OR(ON, OFF) gLight "All lights" <light> (Home) ["Lighting"]`
## Your Environment

* Version used: 2.5.0 running on Ubuntu 19.10
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): iOS 13.4
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): iOS 13.4

**Comment by matsahm** [comment]
I have the same problem on a new installation.

**Comment by ccutrer** [comment]
This is a breaking change with the optional characteristics. Because the Brightness characteristic is not a required characteristic, it is not automatically bound to the item. You have to explicitly bind it. Everything works correctly with an item set up like this:

`Dimmer MasterCans_Dimmer "Master Bedroom Cans [%d%%]" <light> (gMaster, gAllOff, gLights, gMasterLights_Switch) [ "Lighting" ] { channel="zwave:device:512:node3:switch_dimmer", homekit="Lighting, Lighting.Brightness" }`

**Comment by onik** [comment]
Sorry, I've migrated from OH to HA since posting this and can't reproduce the issue anymore.
