### ISSUE TITLE
[exec] Binding tries to read deleted whitelist

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab-addons#7065]
## Expected Behavior
The exec binding should not try to read the whitelist file after it gets deleted.

## Current Behavior
The exec binding tries to read the whitelist file after it gets deleted, fails, then warns that the file could not be read.

## Possible Solution
Remove the whitelist "feature".

**Comment by lsiepel** [comment]
This issue is allmost three years old, so it might not be valid anymore. There have been some [whitelist related PR's](https://github.com/openhab/openhab-addons/pulls?q=is%3Apr+%5Bexec%5D+in%3Atitle)  merged since this issue was created. Could you verify if this is still an issue with 3.4.0 and if not close this issue?

If it is still an issue, could you ellaborate the use case /issue ?

**Comment by jlaur** [comment]
Possibly fixed by #14522.

**Comment by J-N-K** [comment]
Yes and no. It’s expected that the file is there, it is created on startup. It should not be deleted (it‘s required, the binding won‘t do anything without it) and so logging a warning if the file can‘t be read is correct. That is what is implemented in the linked PR.
