### ISSUE TITLE
[Q] [Bluegiga] Rfc2217 support for remote BlueGiga dongles?

### ISSUE THREAD

**Issue by curlyel** [openhab/openhab-addons#7190]
Hi @pfink, hi @paulianttila,
according to several @cpmeister 's posts in the openHAB forum, you're putting some effort on the BlueGiga binding currently. This is great! Really happy to hear, that the "official" Bluetooth support is getting this attention. Thanks a lot for working on this!

While doing so, have you considered making it work with rfc2217://<ip>:<port> as serial port definition? Or is it probably possible yet?

The obvious use case is to have multiple BlueGiga dongles connected via rfc2217 to ser2net on remote devices (e.g. Pi Zero etc.) covering an bigger area beyond the usual range of Bluetooth.

Thanks,
Curlyel

**Comment by paulianttila** [comment]
@curlyel, bluegiga binding use serial port manager from openHAB core, so rfc2217 should be supported already. Never used that myself, so don’t know how well it work.

**Comment by cpmeister** [comment]
I never went with the ser2net route to extend my range, I just bought a couple of cheap serial-to-ethernet dongles to extend my range.

https://www.amazon.com/gp/product/B07LDCK438/ref=ppx_yo_dt_b_asin_title_o03_s00?ie=UTF8&psc=1

Of course, this only works if you give it a dedicated ethernet cable; you can't connect it to the network. This way works for me because I have a ton of ethernet cable lying around.

**Comment by curlyel** [comment]
> a couple of cheap serial-to-ethernet dongles to extend my range.

Yeah, I'd recommend the same if in short distance and cabling available, and I already did ;-) :

https://community.openhab.org/t/xiaomi-mi-flora-plant-sensor-mqtt-client-daemon/33119/184

> bluegiga binding use serial port manager from openHAB core, so rfc2217 should be supported already

That's great. I'll give it a try,
Thanks guys for you immediate reply and for your contribution!
