### ISSUE TITLE
Resol binding from Eclipse IoT market missing in openHAB 3.0 snapshot

### ISSUE THREAD

**Issue by EjvindHald** [openhab/openhab-addons#7221]
In openHAB 2.5 you can go to Add-Ons in paperUI and install Eclipse IoT market - see [link](https://www.openhab.org/docs/configuration/eclipseiotmarket.html)

When that is done in openHAB 2.5 some additional bindings becomes available for install such as the very useful Resol binding - see [link](https://community.openhab.org/t/beta-of-resol-binding-available-on-iot-marketplace/43550)

However, in the new openHAB 3.0 snapshot, the Resol does not become available after adding Eclipse IoT market. Therefore, I cannot use this binding in openhab 3.0.

**Comment by wborn** [comment]
It's a known issue and it was removed on purpose because it will be replaced with something new in OH3, see https://github.com/openhab/openhab-addons/issues/6673.

It's also very unlikely that any add-on currently available in the IoT market will work with OH3. That's because all the Java packages in OH3 were renamed from `org.eclipse.smarthome` to `org.openhab`.
