### ISSUE TITLE
[mqtt] Broker settings Certificate/PubKey pinning

### ISSUE THREAD

**Issue by bHub** [openhab/openhab-addons#7382]
## Expected Behavior

When the options Certificate and PubKey pinning are enabled, in the MQTT Broker settings, the fields "Certificate Hash" and "Public key Hash" should be automatically filled, and the hashes should be valid until the certificate and the key are the same. 

## Current Behavior

If OH is restarted, the connection with the broker shouldn't be made until you blank the fields "Certificate Hash" and "Public key Hash"; the same hashes are recreated and the connection could be estabilished. 
If the  Certificate and PubKey pinning are disabled, everything works fine even after a reboot.

## Steps to Reproduce (for Bugs)

1. Configure MQTT Broker in OH in order to use TLS (I use Mosquitto)
2. Enable Certificate and PubKey pinning
3. The first connection should be fine
4. Reboot OH
5. Check the status of the connection between OH and the broker 

## Context

I was configuring OH and all the other MQTT devices in order to use TLS to connect the broker

## Your Environment

* Version used: docker image openhab:latest-debian

**Comment by netboy3** [comment]
This bug still persists in OH3.2.0, almost 3 years now. It looks like the code that stores the discovered hash is not storing the `SHA-256:` hash type in the Thing's config as part of the hash string, and when tested in [BrokerHandler.java#L161](https://github.com/openhab/openhab-addons/blob/dfd4beac825a7524c13cfef1b4058047817fa29d/bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandler.java#L161) and [BrokerHandler.java#L179](https://github.com/openhab/openhab-addons/blob/dfd4beac825a7524c13cfef1b4058047817fa29d/bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/handler/BrokerHandler.java#L179) ends up throwing an exception as there's no ":".

**Comment by miloit** [comment]
Hello any news on this one??

**Comment by FlippingBinary** [comment]
Maybe @kaikreuzer can share some insight into where to find the code that's leaving off the `SHA-256:` prefix? They committed the [MQTT SSL code](https://github.com/openhab/openhab-addons/tree/main/bundles/org.openhab.binding.mqtt/src/main/java/org/openhab/binding/mqtt/internal/ssl) four years ago. This feels like one of those situations where random people spend between a few minutes to a few hours digging through the source to find where it happens and any one of us could easily fix it once it's found but wind up moving on to other things because it's not a problem that impacts any of us for longer the initial time we encounter it.

**Comment by FlippingBinary** [comment]
I was on stable, but I certainly can test 4.2.0-SNAPSHOT. Just let me know when.

**Comment by J-N-K** [comment]
Please update to 4.2.0-SNAPSHOT (or latest 4.2.0 milestone) and go to the karaf console (`openhab-cli console`). Then type

`update org.openhab.binding.mqtt https://download.smarthomej.org/org.openhab.binding.mqtt-4.2.0-SNAPSHOT.jar`

I think you need to reset the pinning configuration, because the error occurs when the hash is stored.

**Comment by FlippingBinary** [comment]
@J-N-K I finally got around to testing this so I installed 4.2.0-SNAPSHOT via Docker today, but your fix is already merged in and works great. Thank you!
