### ISSUE TITLE
[spotify] Duplicated Spotify Connect devices are not removed from the Inbox.

### ISSUE THREAD

**Issue by radokristof** [openhab/openhab-addons#7400]
The Inbox is filling up with the same device (which I don't want to include in my system) and old ones are not removed automatically. Would be great if these could be removed.

## Expected Behavior
Only one Inbox Item /device in the Inbox.

## Current Behavior
The Inbox is filling up with the same device.

## Possible Solution
When the device is discovered, check if the device is already in the Inbox or not. If yes, remove the old one first.

## Your Environment

* Version used: openHAB 2.5.3
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Raspbian Buster

**Comment by radokristof** [comment]
@Hilbrand This still exists on 2.5.4 as well.

**Comment by Hilbrand** [comment]
I tried to reproduce this and looked at the core code, but can't find a reason this happens. By design the discovery framework should always remove old things not found anymore. So there might be some condition why this happens in this specific case, but I don't know what it is. It might be something to do with detecting the same device, but one that get some different data causing to not be seen as the same device. Only a different id should not be a problem as that should be handled.

**Comment by radokristof** [comment]
Which devices did you tried?
I did not see that until now, that it seems that only a few of them are re-appearing... Most of my "real" Spotify Connect devices are added to openHAB, but few of them are not (like Chromecasts), and these are not showing up again, only once. Only phones/Spotify app clients showing up again and again, like phones/tablets/PCs, which are not "real" devices if you know what I mean, you can just control them through any Spotify client...
And I think they are always a "new" device, but I don't know why... Maybe because they are not present in Spotify always, just when you have launched the Spotify app.
What about checking device name? It is too broad and might hide other devices as well?

**Comment by AJErazzor** [comment]
I still get this issue with 2.5.5 - duplicate discovered spotify connect devices in the inbox.  If I leave them there to build up long enough I end up with OOM errors too.
