### ISSUE TITLE
Davis Binding not found Openhabian

### ISSUE THREAD

**Issue by minoanson** [openhab/openhab-addons#7614]
Hi, to all!

I have a problem with Davis Binding
i am trying to find it on my list on my openHAB 2.5.4-1 (Release Build) which i have on raspberry(Openhabian)

and i cant find it anywhere…am i doing anything wrong?i have remote repo and binding for 1.x enable…
The binding i am trying to install is this one:
https://www.openhab.org/addons/bindings/davis1/

![davis 1](https://user-images.githubusercontent.com/9058260/81726496-22e73280-9490-11ea-9f91-4643d954eb61.PNG)
![davis2](https://user-images.githubusercontent.com/9058260/81726499-24185f80-9490-11ea-9199-a55c841f86f3.PNG)
![davis3](https://user-images.githubusercontent.com/9058260/81726500-24b0f600-9490-11ea-817a-dd77bb248d78.PNG)
![davis4](https://user-images.githubusercontent.com/9058260/81726502-25498c80-9490-11ea-9d50-2cc98394feaf.PNG)

i did found via the community a workaround installing it custom via addons and seems to me active in cli! 

Thanks

**Comment by Hilbrand** [comment]
This version 1 binding is not known supported and therefor doesn't show up in PaperUI. But unfortunately it does show up in the documentation. See also this issue: https://github.com/openhab/openhab1-addons/issues/5781 
Part of why it isn't listed because no one has confirmed it worked with openHAB 2 and took the effort to get the binding listed. So it might or might not work. Fyi Since the openHAB 1 bindings are deprecated with openHAB 3 the version 1 will not work with 3, u less someone creates a new binding.
