### ISSUE TITLE
[lametrictime] Error using JAX-RS client from CXF

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab-addons#7802]
Using lametrictime on openHAB 3, which uses CXF instead of Jersey, I get the following error in my log:
```
14:24:56.042 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - Thing 'lametrictime:device:47ee543589' changed from INITIALIZING to UNKNOWN
14:24:56.365 [ERROR] [org.apache.cxf.jaxrs.utils.JAXRSUtils] - Problem with reading the data, class java.lang.String, ContentType: application/json;charset=UTF8.
14:24:56.366 [INFO ] [ome.event.ThingStatusInfoChangedEvent] - Thing 'lametrictime:device:47ee543589' changed from UNKNOWN to OFFLINE (COMMUNICATION_ERROR): Unable to connect to LaMetric Time
```
@wborn fyi

**Comment by wborn** [comment]
I haven't run into this error myself. Maybe it is due to implementation differences between CXF/Jersey or the newer JAX-RS version?

With some changes I was able to get the SSE working with the Nest Binding now. I only need to do some more testing now.

I just ran my [port-addons.sh](https://gist.github.com/wborn/0e3cd275be724e827ef88bb04b7eb12a) and pushed the result to this [port branch](https://github.com/wborn/openhab-addons/tree/port) so you could use that to further debug this issue.

**Comment by kaikreuzer** [comment]
Thanks @wborn, your branch was very helpful!
It turned out to be a bug in the code that by accident worked with Jersey...
I have successfully tested the communication with the fix in #7818 both on 2.5 and 3.0.

**Comment by wborn** [comment]
That's good news! :+1:
Does the Tesla Binding also work now?

**Comment by kaikreuzer** [comment]
Tesla looks quite good now as well, yes! Just having some issues with auto-discovery in my test distro, while it is working in the IDE. But I doubt that this is related to JAX-RS.
