### ISSUE TITLE
[hueemulation] items still announced after uninstall

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab-addons#8043]
I used 2.5.6 hueemulation to expose OH items to Alexa, then moved on to use the skill instead.
I properly uninstalled hueemulation, but I was having trouble with its items to ever appear again when Alexa was told to scan for smart home devices, resulting in duplicate items with equal labels, giving Alexa a hard time to distinguish between.
I finally located these wrongly announced items in `/var/lib/openhab2/jsondb/org.eclipse.smarthome.core.items.Metadata.json`, the remedy was to simply delete the file.

It should automatically happen on bundle uninstall.

**Comment by lsiepel** [comment]
Been a while since this issue was reported, so not sure if it is still valid. The path's changed for sure, but anyway. When i look at the file path it seems a shared file (from core) and not specific to the bundle. I also have not found a hook in the documentation that removing the file would be possible from a bundle.
Isn't the core repo a better place ?

**Comment by mstormi** [comment]
Given its age and inability to reproduce, let's close. I guess you will remember in case there's anything related coming up in the future.
