### ISSUE TITLE
[LCN] Contact Item shows wrong state

### ISSUE THREAD

**Issue by kobelka** [openhab/openhab-addons#8069]
In the new 2.x LCN-Binding the state of a contact item is wrong.
For Example the door is closed and in Openhab shows that the door is open.  
In the 1.x Binding the state was right.
Regards 
Jörg

**Comment by toweosp** [comment]
An LCN-BMI (at least in my environment) delivers "0" in the PCHK's Bx-status command (2.x LCN-binding: contact closed)  if no motion is detected, visualized e.g. by icon motion-closed, and "1" (contact opened) if motion is detected, visualized by e.g. icon motion-opened.

In contrast the door's reed contact - which is connected to an LCN-BU4L configured as a binary sensor - in my environment delivers Bx-status "0" ("contact closed") if the door is opened - or during blackout - and "1" ("contact opened") if the door is closed. So you have to handle the "reverse mapping" when visualizing door-status by yourself.

In my opinion this is intended behavior and not a bug of the 2.x LCN binding.

**Comment by kobelka** [comment]
You are right, this is the behavior of LCN, but I think Openhab should be easy for everyone, so it would be nice If you can change the behavior of the binary sensor channel directly in the paper ui, like it is with the variables channel.

![image](https://user-images.githubusercontent.com/10710041/87036960-d5ffae00-c1eb-11ea-9f6e-303f5e7a2df7.png)

**Comment by kobelka** [comment]
Also in the 1.x Binding I didn´t had to change anything....

`Contact	s_haustuer	"Haustür [%S]"	<frontdoor>	(g_fenster,g_mysql)	{lcn="[myhome:BINARY_STATE.0.20.4]"}`

Now in the 2.x Binding I have do to rules and virtuale contact Items to get the right state....

**Comment by toweosp** [comment]
Do you use (LCN-BMI) motion sensors and were they handled correctly in the 1.x Binding?

Because of the special behaviour of door contacts/reed sensors (see my last post) I myself would have to define rules and virtual contact items for many motion sensors in my environment - instead for 1 or 2 door sensors - if contact state handling in the 2.x binding would be reversed.

I like your idea to add a configurable option to the binary sensor channel where one could define if e.g. status "open" should correspond to "0" or "1" of the LCN bus' binary sensor state message. Alternatively we could use a checkbox "reverse open/closed". Perhaps you could change your bug report into a feature/enhancement request?

If the binding owner (@fwolter) will agree with this extension I could offer to implement such a feature (at least to try to ;-))

**Comment by kobelka** [comment]
`Perhaps you could change your bug report into a feature/enhancement request?`

How could I do this ?
