### ISSUE TITLE
[mqtt.homie] settable, non-retained channels are unusable

### ISSUE THREAD

**Issue by ccutrer** [openhab/openhab-addons#8164]
If a property is non-retained, and settable, OpenHAB creates a trigger channel only, which AFAICT you cannot actually use to send a message to the device. The Homie spec explicitly allows this (the example they give is:

```
non-retained + settable: The node publishes momentary events, and can receive commands for the property (by controller or other party) (brew coffee)
```

## Expected Behavior
A state channel of an appropriate type is created (`Switch` in the case of "brew coffee", when $datatype is boolean).

## Current Behavior
A trigger channel is created, which allows rules to receive events published by the node, but no way to trigger the property and have the node take an action.

## Context
I'm able to work around for now by editing the channel after the Homie binding has created it and setting retained to true, which changes it to a regular state channel.

## Your Environment
* openHAB 2.5.7

**Comment by bodiroga** [comment]
Hi @ccutrer!

Yeah, for "settable" and "non-retained" properties openHAB should give the option to send commands to the channel. And you are right, as trigger channels cannot have "command descriptions" (withCommandDescription), we should model those channels as state channels. @kaikreuzer, @J-N-K, @Hilbrand or @cpmeister, should the framework allow adding command descriptions to trigger channels? Or do we force trigger channels to be read-only? I don't know if it's worth opening an issue in the core repository, I don't think so.

Cody, can you give me the Homie device example where you have implemented the settable and non-retained property? I will try to implement the changes and submit a PR :wink:

**Comment by bodiroga** [comment]
@ccutrer, what type of "datatype" are you using for your "settable" + "non-retained" property? I suppose that it should be the "enum" type, am I right? If the property doesn't store any state, the commands supported by the device should be finite and, therefore, defining them as a list would be the best option. Is this your case?

Having a look at your device structure (or just the special property) would be really helpful :wink:

**Comment by ccutrer** [comment]
Here's my property - https://github.com/ccutrer/gatecontroller/blob/main/app/mqtt.lua#L37

It's a keypad controlling a fence gate latch. The keypad sends a message via a non-settable, non-retained property of a scanned keycard, and my rule shells out to a service to validate that code. Assuming it's correct, the rule then does two things - it unlocks the gate (a settable, retained property), and sends a success signal (makes the keypad beep and light up green). Success is a separate property, since I still want feedback that the keycard was accepted, even if the gate is already open, or if you're executing a lock command.

**Comment by bodiroga** [comment]
Great @ccutrer, thanks for your additional information :+1: 

Let me expose what I have understood:

- The "code" property of the "keypad" node is the one you use to inform openHAB (or the Homie controller) about the keycard code being read. Fine, this is a non-retained and non-settable property and as such is modeled as a trigger channel (you don't want to store this value, but process it in a rule, so creating an item is not necessary).
- The "latch" node has different properties to control the state of the gate and I suppose that you use one of those to unlock the gate (the settable and retained property that you mentioned in your message). Anyway, one question: can your gate be in more than one of the "locked,latched,restricted" states at the same time? For me it seems strange to have three settable properties that look similar, but you know much better than me how your gate operates :rofl: 
- The success signal is the "special" one, because you want a property to which you will send a command and the device will make an action (beep and light up). Two questions: does the keypad send any MQTT message after the action is completed? I don't see any "publish" function been called in SignalSuccess(). Is that correct? And, as you are modelling the property with a "boolean" type, what does the 'false' value do? Nothing, right? That's why in my previous message I mentioned that this type of properties should be defined as "enum": in your case there is a single command, being called "signal", "beep", "light up", "beep+light up", "notify"... or whatever you prefer :wink: I emphasize this because I would like these channels to implement the "commandDescription" option (so that in the user interfaces they appear as buttons and not as switches) and to have their autoupdate property set to false, since the state of the item is not reflected by the command sent to it.

Ok, now that things are more clear, it is time to make some changes to the code and make a PR! Thank you!

**Comment by ccutrer** [comment]
* Yes, you understand code correctly.
* Latched represents the actual state of the latch. Unlocked means you can just press a button on the outside of the gate, and it will unlatch. Restricted means the Push-to-Exit button on the _inside_ of the gate is not allowed to work. Latched is almost a candidate for a non-retained, settable property, but I do vary how long the latch stays open - as soon as the gate opens far enough, it immediately re-latches.
 * Hmm, yeah, interesting, an enum with a single value. That would make sense. Cause yeah, sending it false doesn't mean anything, and there's not feedback that it worked or not. In my mind I was thinking "it's like a momentary switch". I actually do have several MQTT-published devices that I have momentary switches (open/close/stop) that I model as three boolean properties. But then I "cheat" with a "position-percent" property that also recognized UP/DOWN/STOP strings, that I can map directly to an OpenHAB rollershutter (via a manually configured MQTT thing).
