### ISSUE TITLE
[mqtt] Add support for xy colors

### ISSUE THREAD

**Issue by nwpr** [openhab/openhab-addons#8266]
The MQTT binding currently supports RGB and HSB colors. Since many bulbs use XY colors instead, this type should be implemented too.
Example: While Hue also supports HSB, Trådfri bulbs only support XY colors.

The openHAB core already has support for the conversion from HSBType to XY values and vice versa. This existing code can be used to implement this functionality.

**Comment by bodiroga** [comment]
Hi @nwpr!

Thanks for your feature request! In order to make things more clear, you are suggesting to create a new channel type for the Generic MQTT Thing called "Color value (XY)", right?

**Comment by nwpr** [comment]
Hello!

Yes, that's exactly what I meant:
Creating a new channel type for the Generic MQTT Thing called "Color value (XY)".

Nevertheless the HomeAssistant Light Component should also support XY color changes in the future. That why  I wrote a more generic issue.

**Comment by J-N-K** [comment]
I would suggest to add an option „color mode“ tobte color channel.

**Comment by bodiroga** [comment]
> I would suggest to add an option „color mode“ tobte color channel.

Yeah, looks like a better option, I will implement it.

@nwpr, one question, how are xy command messages sent? "0.256,0.486"? And how are status updates reported through MQTT? I would like to know what the payload structure is, thanks! :wink:

**Comment by nwpr** [comment]
> I would suggest to add an option „color mode“ tobte color channel.

That's a very good idea.
> @nwpr, one question, how are xy command messages sent? "0.256,0.486"? And how are status updates reported through MQTT? I would like to know what the payload structure is, thanks! 😉

I'm using zigbee2mqtt as bridge, where a Trådfri bulb state payload looks like this:
```{
  "state": "ON",
  "brightness": 25.4,
  "update_available": false,
  "color": {
    "x": 0.31273010828044345,
    "y": 0.3290198826715099
  }
}
```
Since it is using JSON, I would use a transformation to parse the payload to get the required format, so everything will be more generic for other MQTT devices.

What about using the same format as the other color modes: three comma separated values `x,y,brightness`?
So in this case the value would be `0.31273010828044345,0.3290198826715099,25.4`.

**Comment by bodiroga** [comment]
Awesome @nwpr, thanks for the information!

One question: what is the range of the "brightness" value? 0-100? 0-255? I'm having trouble with the "Y" variable, because I don't know what value it should express. openHAB's built-in ```toXY()``` function returns the brightness, between 0-100, but that brightness has the same value of the HSB type. Does your "25.4" value mean that the bulb brights at its 25%?

**Comment by nwpr** [comment]
Yes that's right. Zigbee2mqtt is using a value between 0-255, and I think that most other devices are using that too in combination with XY.

But I guess it would be no problem to transform this value too, so it's up to you which range to use. My suggestion is pre-converting it to 0-255. ☺️

**Comment by bodiroga** [comment]
Ummmm... I think that the ```toXY()``` and ```fromXY()``` functions implemented by @cdjackson in the HSBType class are a little bit weird :confused: As I told you yesterday, I have been playing with the color converter page (http://colormine.org/color-converter) and the results I'm getting are not the same that the ones I get from the binding. For example, the ```fromXY()``` function, having only two components, seems to indicate that the Y in xyY doesn't have any effect in the HSB representation, and that's not true. And the ```toXY()``` function also doesn't work correctly, because it always suppose that the brightness is at 100%: https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core/src/main/java/org/openhab/core/library/types/HSBType.java#L360.

@cdjackson, can you tell us why are those functions implemented that way? IMO, we should have ```toXYY()``` and ```fromXYY()``` functions, but openHAB's 2.5.X core is freezed and we cannot make any change to it. This color representation topic is really tough :cry:

**Comment by nwpr** [comment]
If the values from the color converter page are just a little bit off, that should not be a problem as our function uses a conversion from sRGB to CIE XY using D65 reference white, whereas we don't know which exact parameters the page is using. If there is a very big difference, this of course needs further investigation.

Having only two components for fromXY() seems fine to me, since we don't get the second Y value from the bulb. Even if the function would parse this value, we don't have it available. And always supposing the brightness as 100% should also be right, because if you dim the bulb (change the brightness value), the color itself (x,y) doesn't change at all.

As you can see in the JSON message, these bulbs normally completely separate color and brightness, so these values are independent.

The important thing is that the sequential conversion toXY() and fromXY() must result in the same original value, so changing only the brightness in openHAB doesn't change the color. (Wrong HSB value gets written back to openHAB and then sent again.)

**Comment by bodiroga** [comment]
Thanks for your message @nwpr, some concepts are more clear for me now :+1:

Anyway, there is something that I still don't understand. Let's take the color converter web page (http://colormine.org/color-converter) and convert a pure red color from RGB to XYY.

(R, G, B) -> (x, y, Y)
```(255, 0, 0)``` -> ```(0.6400744994567747, 0.3299705106316933, 21.26)```

Ok, I understand that ```(0.6400744994567747, 0.3299705106316933)``` is what makes the color pure "red", and lowering the "redness" doesn't change the first pair of values. For example, ```(100, 0, 0)``` is converted to ```(0.6400744994567747, 0.3299705106316933, 2.7093250860618645)```. Great, still, red.

Let's do the same exercise for a pure green value: ```(0, 255, 0)```.

(R, G, B) -> (x, y, Y)
```(0, 255, 0)``` -> ```(0.3, 0.6, 71.52)```

Fine, ```(0.3, 0.6)``` are the coordinates for the green color, because they stay constant for the ```(0, 100, 0)``` -> ```(0.3, 0.6, 9.114342904757505)``` transformation.

But... what is going on with the ```Y``` value? What does it mean? Certainly it is not a "brightness" value, because in both cases we are using full red and green colors and the Y value is not 100 :confused: It seems that "full brightness" for red is at ```21.26``` and for green is at ```9.1143```.

That's not what happens with the HSB representation (openHAB's internal representation):

Red: ```(255, 0, 0)``` -> ```(0, 100, 100)```
Green: ```(0, 255, 0)``` -> ```(120, 100, 100)```

In both cases brightness is at its full value: (?, ?, 100).

In any case, let's forget the theory for now and focus on your JSON example :smile: From your previous messages, this is what I have understand:

Having a ```(0.31273010828044345,0.3290198826715099,25.4)``` command, should I take the first pair of values to create the (x, y) color using the ```fromXY()``` function (ignoring the third value) and then set the HSB brightness with the 25.4 number? That's it? :thinking: 

Many thanks for your help and sorry for my questions, it seems that I'm requesting the feature and you are implementing it :rofl:
