### ISSUE TITLE
Looking for the maintainer of the Openhab deCONZ binding.

### ISSUE THREAD

**Issue by Mimiix** [openhab/openhab-addons#8379]
Hi!

I'm Dennis, the community manager of the deCONZ community. In our community, i get more and more questions of openHAB users. Especially in regards to bugs or questions in usage. As there is no developer from you around, i cannot answer them all. 

By posting this message, i hope to get in touch with you and have you around. Currently, most developers of deCONZ and surrounding ecosystems are present aswel. 

Love to hear from you!

- Dennis

**Comment by cweitkamp** [comment]
Hi Dennis (@Mimiix),

Thank you for inviting us to join the deCONZ community. It would be great if you could share a link as well, because - to be honest - I do not know where to look for it.

Just as a side note - our community can be found here: [https://community.openhab.org/](https://community.openhab.org/). That is the place where you should forward users to ask their openHAB related questions.

I am not sure if the initial contributor (@davidgraeff) of the deCONZ binding is still around. In the past weeks @J-N-K and myself were working beside others on improvements or bugfixes.

Looking forward to strengthen our cooperation in the future.

Best,
Christoph

**Comment by Mimiix** [comment]
Hi Christoph (@cweitkamp)!

Thanks for your quick response!

I was unsure if i was able to post URL's right away, as not everyone appreciates that. 

We are only residing at [Discord](https://discord.gg/a5fXUEc) and [Github](https://github.com/dresden-elektronik/deconz-rest-plugin) right now. Discord is the main place for the devs to meet and discuss changes and bugs. 

Great to hear you are as excited as I am 😄 

Cheers,
Dennis
