### ISSUE TITLE
[opensprinkler] nextDuration is not transformed with UoM

### ISSUE THREAD

**Issue by HerzScheisse-zz** [openhab/openhab-addons#8541]
Hi,

recently I submitted a change to the OpenSprinkler Binding to get the `nextDuration` channel editable in PaperUI...
see #8322 

but i guess we need to change something else in the binding to get the selected minutes value transformed into seconds if the user is using a different UoM than seconds...

Maybe @FlorianSW can help here?

this is my .items entry:
`Number:Time    OpenSprinklerStation01NextDuration          "S1 nächste Laufzeit [%.0f min]"    (gOSPI)                   {channel="opensprinkler:station:http:01:nextDuration"}`

![2020-09-22 11_21_29-Window](https://user-images.githubusercontent.com/760240/93864975-f22cca80-fcc5-11ea-8f37-043e59ffa36d.png)

![2020-09-22 11_22_13-Window](https://user-images.githubusercontent.com/760240/93864995-f822ab80-fcc5-11ea-8670-fd1552c6abb7.png)

**Comment by Hilbrand** [comment]
Yes the problem is this:
https://github.com/openhab/openhab-addons/blob/edc77ec1a6f465bbb863b989ebbeb57f72bf4f52/bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerStationHandler.java#L94
The value passed is just convert to a number, without taking into account what the unit is. So it should first get the unit as seconds and then get the value.

Also when updating state it should use `new QuantityType`:
https://github.com/openhab/openhab-addons/blob/edc77ec1a6f465bbb863b989ebbeb57f72bf4f52/bundles/org.openhab.binding.opensprinkler/src/main/java/org/openhab/binding/opensprinkler/internal/handler/OpenSprinklerStationHandler.java#L207

**Comment by HerzScheisse** [comment]
Thanks @Hilbrand for the answer and help...

as i'm always willing to learn i'll post what i think that needed to be changed... but atm i dont have a working IDE to test and submit the needed code changes...

May I ask you if you could add this fix to 3.0 and 2.5.x aswell?

OpenSprinklerStationHandler.java
L94:
change `this.nextDurationTime = quantity.toBigDecimal();` to `this.nextDurationTime = quantity.toUnit(SIUnits.SECOND);`

L207:
change `updateState(channel, new DecimalType(duration));` to `updateState(channel, new QuantityType<TIME>(duration, SIUnits.SECOND));`

is this correct?
