### ISSUE TITLE
[heos] Login with special characters in password does not work

### ISSUE THREAD

**Issue by ifs-net** [openhab/openhab-addons#8760]
There seems to be a problem with heos login having special characters in the passwort.
For example a passwort including $ and ! does not work.

See also https://community.openhab.org/t/6-invalid-credentials-when-using-the-heos-binding-2-5-5/103029/2

Could you please add support for passwords using special characters?

**Comment by J-N-K** [comment]
What special characters are you using?

**Comment by ifs-net** [comment]
> What special characters are you using?

In this case I tried ! and $

**Comment by J-N-K** [comment]
The reason is https://github.com/openhab/openhab-addons/blob/f199142ef8e98daa8c783add99f9088abbf0b212/bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/resources/HeosCommands.java#L266 which uses https://docs.oracle.com/javase/7/docs/api/java/net/URLEncoder.html. There is already a workaround for the `@` character https://github.com/openhab/openhab-addons/blob/f199142ef8e98daa8c783add99f9088abbf0b212/bundles/org.openhab.binding.heos/src/main/java/org/openhab/binding/heos/internal/resources/HeosCommands.java#L328. Maybe this needs to be extended to more characters. Unfortunately I have no knowledge about what heos supports or not and not really an idea how to get that information. 

@Wire82 or @martinvw Can you comment on that?

**Comment by martinvw** [comment]
I would say it is related to the other issue, reported before: https://github.com/openhab/openhab-addons/issues/6491 however that was already included in 2.5.6

So the reports about success in version 2.5 seem to be about the affected version, would anyone know why it would break in 3.x?

**Comment by J-N-K** [comment]
I think it's probably the other way. Too much characters are encoded.

**Comment by martinvw** [comment]
@J-N-K sorry for the delay, yes you are right, I'll try to look into.
