### ISSUE TITLE
[mqtt] Cannot add "Publish Trigger" channel

### ISSUE THREAD

**Issue by ulfwin** [openhab/openhab-addons#8853]
## Expected Behavior
Being able to add "Publish Trigger" channel through PaperUI

## Current Behavior
I'm using PaperUI to try to add a "Publish Trigger" channel (the only channel available). After entering the settings (see picture) and pressing save, I get "ERROR: 500 - Internal Server Error". The thing is online when I try this.
![mqtt_settings](https://user-images.githubusercontent.com/9116407/97084460-8963a580-1617-11eb-96c0-7324a23d0eb1.png)

![mqtt_error](https://user-images.githubusercontent.com/9116407/97084487-aac49180-1617-11eb-928f-0f18c5befdd5.png)

I've tried to restart the pi, but still the same error.

Also note that I've already done this with the same channel settings on another openhab install, which works fine.

Nothing is revealed from the log viewer (tail -f /var/log/openhab2/openhab.log /var/log/openhab2/events.log)

## Steps to Reproduce

All steps below except the first is using PaperUI
1. Install Mosquitto through openhabian-config, and choose to use password
2. Install MQTT binding
3. Manually add a MQTT broker
4. Try to add a channel to the MQTT broker

## My Environment

I'm running a fresh openhabian on a raspberry pi 4 4GB, MQTT installed through command line using openhabian-config. 

openHABian Configuration Tool [stable]v1.6-880(769ea17) 
openHAB 2.5.9 Release Build

**Comment by ulfwin** [comment]
Hmm... it appears to be related to the channel id. If I call it "pub" it works. What is the syntax requirements? Also, perhaps there should be a more understandable error message, or at least a comment below the field?

**Comment by bigbasec** [comment]
Yea, you can tell when it's not going to work.   You don't get the "Thing updated" box in the bottom right corner.   Looking at the error console on the browser you get this : 
`"{\"error\":{\"message\":\"UID segment \\u0027BasementAQOut.MQTT\\u0027 contains invalid characters. The last segment of the channel UID must match the pattern \\u0027[\\\\w-]*|[\\\\w-]*#[\\\\w-]*\\u0027.\",\"http-code\":500,\"exception\":{\"class\":\"java.lang.IllegalArgumentException\",\"message\":\"UID segment \\u0027BasementAQOut.MQTT\\u0027 contains invalid characters. The last segment of the channel UID must match the pattern \\u0027[\\\\w-]*|[\\\\w-]*#[\\\\w-]*\\u0027.\",\"localized-message\":\"UID segment \\u0027BasementAQOut.MQTT\\u0027 contains invalid characters. The last segment of the channel UID must match the pattern \\u0027[\\\\w-]*|[\\\\w-]*#[\\\\w-]*\\u0027.\"}}}"`

Seems as though it's self induced, changing the name of the channel works fine.   Oddly though nothing is in the logs even with the binding in trace.

**Comment by bigbasec** [comment]
So there are a couple things you can't put in the "Channel ID" part of this.   

It gets passed to the ChannelUID class which does a check on the format of the complete Channel name, and it would seem as though anything with a space( ) or a period(.) would not be allowed.   

So the bug is not really with the MQTT binding since the bindings aren't expected to validate the channel names, but I think this is more a core issue.   It seems as though it doesn't allow the name, but still shows the channel as created(until you refresh the page).   

This will happen on any binding that allows you to enter a channel name and you enter it wrong.    Most likely the fix needs to made here : "openhab-webui/bundles/org.openhab.ui/web/src/pages/settings/things/channel/channel-add.vue" to check that and not allow an invalid entry.   Could add a required validate to the Channel Identifier, but that will still allow the Create button to work.   It'll need to be checked in the js save() function for it to be effective.   A pop up box would be ideal I'd assume.

**Comment by bigbasec** [comment]
Should be fixed here if accepted : https://github.com/openhab/openhab-webui/pull/795

**Comment by lolodomo** [comment]
PR for UI was merged.
