### ISSUE TITLE
[chromecast] Create distinction between powered by mains, or through another device like a TV

### ISSUE THREAD

**Issue by SierraNL** [openhab/openhab-addons#8901]
I've been using the Chromecast binding for a while now, using a first generation Chromecast connected to an older Samsung smart TV, which through it's USB port, powers the Chromecast, when the TV is turned on.

When I look at the things overview, when the TV is off (and so is the Chromecast), the thing shows a communication error.
This is a trigger for me, that there is something wrong in my setup, but it's just caused by the device being off.
But I agree that it should show a message like this when it's mains powered, and expected to be always online.

So I would like to have a checkmark in the things configuration, where I can mark it as mains powered or not.
And if it's not, it's just offline without showing errors when the Chromecast is not powered.

## Your Environment
* Version used: OpenHAB 2.5.9 (also checked in 3.0.0M1)
* Environment name and version (OpenHAB running on Docker, using the official image):

**Comment by wborn** [comment]
The [ThingStatus](https://www.openhab.org/docs/concepts/things.html#thing-status) is not some kind of made up status but it is well defined:

* ONLINE: The device/service represented by a Thing is assumed to be working correctly and can process commands.
* OFFLINE: The device/service represented by a Thing is assumed to be not working correctly and may not process commands. But the framework is allowed to send commands, because some radio-based devices may go back to ONLINE if a command is sent to them.

**Comment by SierraNL** [comment]
@wborn the fact that it's offline is fine, the point is that it shows this:
![image](https://user-images.githubusercontent.com/2605717/97678632-6d875600-1a94-11eb-9de4-21f8a61191d9.png)
So offline, and Configuration_Error, where for instance an unpowered Hue lamp just shows Offline

**Comment by lsiepel** [comment]
As this issue is a bit more then two years old, it might allready been fixed as there are several PR's merged since. Could you verify if this is still happening with 3.4.0? Last week there was also some PR merged to the (yet) unreleased 3.4.1 branch that solved some connection issues. 

If this issue is still active, could you provide a debug log from the 3.4.0 version of the binding?

**Comment by lsiepel** [comment]
As this cannot be fixed from the binding, i close this issue. If there is a need to, it can be reopened again.
