### ISSUE TITLE
[mqtt] Support for Home Assistant Component: Vacuum 

### ISSUE THREAD

**Issue by nullket** [openhab/openhab-addons#8988]
## Problem
OpenHAB supports already a couple of the "offical" Home Assistant mqtt schemes that many devices follow. But not all of them: The Xioami/Roborock vacuum robots are used by quite a lot of people and most just use the miio binding (which is great btw). But in order to get rid of the cloud used by the robot (for privacy, independence ande feature extension reasons) one can use  [Valetudo.](https://github.com/Hypfer/Valetudo). Valetudo offers mqtt for the robot with the implementation of the Home Assistant  vaccum-scheme. Unfortunately, this scheme is not implemented in openHAB yet.

## Solution
Integration of the [Home Assistant vacuum-scheme](https://www.home-assistant.io/integrations/vacuum.mqtt/) in the openHAB mqtt binding. 

I am far away of knowing enough java to implement this myself, but maybe there is somebody willing to help with this. 

## Your Environment

* Version used: openHAB 2.5.10 Release Build
* Environment name and version (e.g. Chrome 76, Java 8, Node.js 12.9, ...): docker:latest
* Operating System and version (desktop or mobile, Windows 10, Raspbian Buster, ...): Ubuntu 20.04

**Comment by t2000** [comment]
Just a short notice here: I have started working on the implementation.

A short teaser is here ;-)

![image](https://user-images.githubusercontent.com/123778/108241531-396f9800-714c-11eb-9570-2129746200e4.png)


However, it turns out to be quite tricky to get the full setup running. As I just learned it is nto enough to have valetudo (or in my case valetudo re) running on the robot. One also needs the valetudo_mapper which takes the raw information published by the robot to mqtt and converts them to a PNG image, which the valetudo_mapper then publishes to mqtt (different topic) as well.

Other than that I am still reading through the code and doing some reverse engineering to find out how to use all the datastructured and helper methods that are already offered :-)

**Comment by t2000** [comment]
FYI: I just noticed that I do not need to write any line of code for the map to work :)

Start up the "valetudo_mapper" and it provides a "camera" that will be detected by the homeassistent mqtt auto detection.

![image](https://user-images.githubusercontent.com/123778/108247503-0381e200-7153-11eb-994a-67ef825493b4.png)

I was wondering why I suddenly had 2 map channels in my system :)
