### ISSUE TITLE
[HTTP] Feature Request - Off Cycle Refresh & Agent String

### ISSUE THREAD

**Issue by morph166955** [openhab/openhab-addons#9265]
Requesting two features be added to the HTTP binding:

1) Ability to trigger an off cycle refresh.  Some devices do not work well getting flooded with API requests so dialing the refresh down is not necessarily desirable.  Example usage: Assume we send a power on/off command to a device via the binding moments after a scheduled update.  There will be an obvious want to update the channels more frequently than the standard refresh.  An action for the thing could likely do this as part of a rule.  For example:

rule "TV Power Change"
when
    Item TVPower received command
then
    val httpActions = getActions("http","http:url:mytv")
    httpActions.forceRefresh()
end

2) Some APIs require specific agent strings to be set for functionality.  If this could be set as part of the Thing it would enable this.  Similar in function to "curl -A"

**Comment by jlaur** [comment]
I recently experienced that when setting the user-agent in a HTTP header, Jetty will use two user-agents (the one set and its own), which is considered an error by some web servers. For example, energidataservice.dk failed. The fix was to set it using the agent method: https://github.com/openhab/openhab-addons/pull/14376/files#diff-a299a861229ecc8972ed87af778fbfe04ad31a424ec3f294ef7bdc91682ea335R116

However, after this change and inspecting my web server logs in my emulated environment, I saw the same thing happening after a redirect, i.e.:

`https://host/path`
-> one agent

redirect to:
`https://host/path/`
-> now two agents

**Comment by jimtng** [comment]
@jlaur could you help test this https://community.openhab.org/t/sendhttpgetrequest-does-not-respect-user-agent-in-header/144838/3

I haven't tested whether it affects/fixes the http binding. I did test it on the HTTP action HTTP.sendHttpGetRequest.

**Comment by jlaur** [comment]
@jimtng - what do you specifically need tested? I'm not currently using the HTTP binding, so I'm not sure if you tagged me by mistake?

**Comment by jimtng** [comment]
> 1. Ability to trigger an off cycle refresh.  Some devices do not work well getting flooded with API requests so dialing the refresh down is not necessarily desirable.  Example usage: Assume we send a power on/off command to a device via the binding moments after a scheduled update.  There will be an obvious want to update the channels more frequently than the standard refresh.  An action for the thing could likely do this as part of a rule.  For example:

This can be done by sending a `REFRESH` command to the relevant Item.



> 2\. Some APIs require specific agent strings to be set for functionality.  If this could be set as part of the Thing it would enable this.  Similar in function to "curl -A"

Added in #14518

**Comment by lsiepel** [comment]
Fixed by: https://github.com/openhab/openhab-addons/pull/16282
