### ISSUE TITLE
Enhancement of Shelly 1L support

### ISSUE THREAD

**Issue by PJ-Verger** [openhab/openhab-addons#9290]
Hello here the possible data you need to enhance the Shelly 1L device support for the 2nd button channel, and power consumption
[Shelly1Lsettings-status-coap.zip](https://github.com/openhab/openhab-addons/files/5658917/Shelly1Lsettings-status-coap.zip)

Nice work on that binding.

**Comment by markus7017** [comment]
There is already #9148 


---

Latest **DEV** build: [2.5.11](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-2.5.11-SNAPSHOT.jar?raw=true) - [3.0.0](https://github.com/markus7017/myfiles/blob/master/shelly/org.openhab.binding.shelly-3.0.0-SNAPSHOT.jar?raw=true) - [README](https://github.com/markus7017/myfiles/blob/master/shelly/README.md) -  [Installation](https://github.com/markus7017/myfiles/blob/master/shelly/READMEbeta.md) - [Bugs/Features](https://github.com/openhab/openhab-addons/issues?q=is%3Aissue+is%3Aopen+%5Bshelly%5D) - [Firmware Index](https://repo.shelly.cloud/files/firmware/?fbclid=IwAR0Kz6bjMGoq_HYU85QAdl8b-xh7E3IPa4ENKjqsvmMAYQ6QGC8ODvqPzUs) - [Firmware Archive](http://archive.shelly-faq.de) - [API Doc](https://shelly-api-docs.shelly.cloud/?fbclid=IwAR23ukCi_3aBSTPRHYUIcpr0pLi0vcyL0fF0PnJQdFvkkc8_Zo5LkAcli_A#http-server)  - Note: The 3.0 build is behind 2.5.11. Let me know if someone needs a 3.0 build due to new device support etc.
