### ISSUE TITLE
[modbus] Convenience profiles to work with QuantityTypes and commanding individual bits

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab-addons#9470]
Inspired by discussion in https://github.com/openhab/openhab-addons/pull/8975#issuecomment-731552768, I came up with an idea to simplify handling data with modbus binding.

## QuantityType-aware numbers
Modbus binding currently supports only plain `Number` channels. This makes it incompatible with excellent UoM system of openHAB.

Typically decimal numbers are scaled to integers with Modbus. Having support for scaling the integers and attaching the unit with a convenience profile would streamline configuration UoM aware numbers.

## Commanding individual bits of holding register

Command individual bits of modbus registers is currently hard, and additional rules are required. See e.g. @Rossko57 's post in the forum https://community.openhab.org/t/bitwise-operations-in-a-modbus-register/77123

~~Since profiles can hold state, it should be possible to construct a profile caching the full register (16 bits), and using that to transparently command individual bits.~~

Profiles for this purpose is not suitable since each channel would have their own cache, even though they might refer to same register. 

Better approach for implementation is to have the cache centrally in the poller thing. This is the approach in https://github.com/openhab/openhab-addons/pull/9980

**Comment by ssalonen** [comment]
PRs 
addons: https://github.com/openhab/openhab-addons/pull/9469
core: https://github.com/openhab/openhab-core/pull/1984

**Comment by Rossko57** [comment]
Academic question, for bitwise writing ; when is the target register cached?  I assume it is necessary to specify the target register in a read poller Thing, and that will govern this.

**Comment by ssalonen** [comment]
This profile would be used with data thing, working with uint16 read value type, so indeed one register.

The internal cache is updated on every read. The internal cache is also optimistically updated with command writes, in many ways similar to autoupdate=true.

There are some inherent problems with the bit profile. If there are two profiles (items) referring to same register but different bit, some race conditions are possible. Each profile have their own cache so the commands are not the same cache. 

Everything will get synchronized eventually when new data is polled but trying to modify many bits of same register is not going to end up well.

This is the biggest weakness with the current implementation compared to something implemented with rules where everything can use the same cache.

**Comment by Rossko57** [comment]
That all sounds reasonable to me.   As said, with the nature of Modbus it is not possible to completely bomb-proof this function.

**Comment by Rossko57** [comment]
> Each profile have their own cache so the commands are not the same cache.

Helping a bit with someone else's project led me to think harder about this. It is a bit of a problem.  The project is not that weird - the bits control lights, so you might want to turn 3 on "at once", or rather quick-fire individual OH commands.  This isn't going to work well with multiple per-bit caches.   I fear this would be a common use pattern.

I guess the problem here is that the individual profiles don't know what the others are doing.
I wonder if I can persuade you to have a think ... is it possible to bring this into the binding, where a register cache can be maintained?  I'm guessing that would be quite a bit of work :(

**Comment by ssalonen** [comment]
Yep, this is exactly my concern as well with the profile approach.

I have think about it how it should work out. There is in fact a [short lived cache in poller](https://www.openhab.org/addons/bindings/modbus/#refresh-command) which is used when REFRESH is issued in close succession, a simple mechanism introduced to avoid spamming the device with read requests when openHAB core automatically refreshes the channels, for example. Cache is ignored when it is older than the configured threshold.

Perhaps this could be reused for caching these bit changes as well. 

In order to have it symmetric with other write value types, I think it would make sense that normal register writes (int16) would also update this internal cache. This would have an impact to user only in corner cases where command is triggered after recently polled data, followed by REFRESH command. The REFRESH command would use the mutated cache since it is still fresh. As an summary, REFRESH  might generate item state updates which reflect the "predicted"/auto-updated registers, not anything that has been polled from the device. 

Thoughts?

**Comment by Rossko57** [comment]
Those constraints all sound reasonable to me.
This feature is not gong to be _that_ heavily used. Even though there are a few PLCs and simpler digi i/o boxes out there with bit-packed registers, they don't often seem to crop up in openHAB world.  Used mostly by the silent knowledgeable perhaps!

I think we could live with rarely-used REFRESH using shared cached register image with possible 'predicted' content, chances of glitches are low and all becomes right at the next (mandatory) poll.  In fact, it sounds desirable, the current "best guess" since polled data is stale as soon as we poll it.

If it all works out, it may be of interest to the HVAC extension authors for review, as these sometimes bit-pack.

**Comment by ssalonen** [comment]
Writing of individual things using `data` thing implemented in https://github.com/openhab/openhab-addons/pull/9980

`REFRESH` uses it own short-duration cache still but it is invalidated if there has been writes to individual bits.
