### ISSUE TITLE
[http] Examples for textual configuration missing

### ISSUE THREAD

**Issue by s0170071** [openhab/openhab-addons#9480]
The http plugin documentation misses textual configuration information. 

Those users who started and maintained a textual configuration so far most likely want to keep it. 
And they don't want to mix configurations, e.g. keep parts of it in the gui database and others in the config files. 

So please, for the sake of compatibility, provide examples for the textual configuration of the http plugin. Otherwise config file users would face very unpleasant decisions.

**Comment by kaikreuzer** [comment]
Every binding is expected to provide a textual configuration example - it seems that was forgotten in that case.

@J-N-K Could you do a PR to add such an example? I agree with @s0170071 that this would be extremely helpful in that case!

**Comment by J-N-K** [comment]
Nope. Takes me hours to figure that out. Whoever wants textual configuration can take the documented parameters and figure it out.

**Comment by kaikreuzer** [comment]
Sorry, but we will have to provide this. No binding must be merged without it (reminder to all @openhab/add-ons-maintainers).
Especially in this case, everyone that used the HTTP1 binding before only had textual configuration and we should even have some migration description for it that explains the common use cases and how it translates to the new binding.
If you cannot do it, please at least try to get help on it by some volunteer.

**Comment by s0170071** [comment]
Sommer 100nm
winter 135 NM

**Comment by J-N-K** [comment]
Well. Then no new bindings from my side.

**Comment by kaikreuzer** [comment]
Do you feel what I wrote does not make any sense? Please stay collaborative as you always were and don't feel offended, which definitely wasn't my intention (I hope that this is clear).

**Comment by J-N-K** [comment]
I agree on the migration examples, but they are not part of the binding documentation (for no binding where a v1 was superseded by v2/v3). I can't provide those, since I never used the http1 binding. 

Regarding the value transformations (which are most of the questions I have seen so far), IIRC you said in the past (regarding the MQTT which uses the same syntax) that transformation examples should live in the transformation documentation not in the binding documentation. 

Regarding the textual configuration for things in general I already made my point clear more than once: Textual configuration allows you to do things that are not allowed and later on we have "bug" reports that are not bugs but misconfiguration. If you look e.g. through the deconz issues, there are quite a few where clearly the documentation was not read and (e.g.) wrong item types linked. This cannot happen in UI based configuration because it's impossible to do that. If you look through the forum, people complain about things configured in .things-files not read, not properly updated, ... for bindings (e.g. MQTT) where there is not one of such reports from users who use the UI. So the conclusion is: I would have preferred to ditch the whole textual configuration and whoever wants it more complicated than necessary can waste his own time but not mine. 

That aside: I already said  [here](https://community.openhab.org/t/http-binding-openhab-3-version/101851/219) that I'll happily merge any PR with documentation updates. But I won't write that.

**Comment by s0170071** [comment]
I think I got it working in the mean time. I'll post it here later.

**Comment by s0170071** [comment]
Example for the textual configuration of the http 3.0 binding: 

1. Things file: 

The thing definition always starts with http:url: followed by the name of the thing (here:VitoWifi). After the @ you may pass a location string in with quotes. The square brackets hold parameters as explained above, each intersected by a comma. Use quotes. 
The transformation string is basically the same as for MQTT, but it differs from the v1 http plugin slightly. Mind the colon ":" for Regex

```
Thing http:url:vitowifi "VitoWifi" @ "1stfloor" [baseURL="http://192.168.1.61/", commandMethod="POST", delay="1000", refresh="90", timeout="900"]   {

    Channels:
        Type number : Channel_Vito_ID           "Vito_ID"                  [ stateExtension="read?DP=0x00f8&Type=CountS", stateTransformation="REGEX:(^[-+]?[0-9]+)" ]
        Type number : Channel_Vito_Mode         "Vito_Mode"                [ stateExtension="read?DP=0xb000&Type=Mode", stateTransformation="REGEX:(^[-+]?[0-9]+)", commandExtension="write?DP=0xb000&Type=Mode&Value=%2$s" ]
        Type number : Channel_Vito_OnOff        "Vito_OnOff_for_ESPEasy"   [ stateExtension="control?cmd=Status,GPIO,12", stateTransformation="JSONPATH(state)",commandExtension="control?cmd=GPIO,12,%2$s"]
}
```

2. Items file. 
This is exactly the same like for MQTT: 
```
Number Vito_ID                   "Vito_ID"           <switch>                (gHeating)                                              {channel="http:url:vitowifi:Channel_Vito_ID" ,   expire="5m"  }
Number Vito_Mode                 "Vito_Mode"         <switch>                (gHeating)                                              {channel="http:url:vitowifi:Channel_Vito_Mode" ,   expire="5m"  }// 0= Off 1= WW 2= WW+heat 0x42 (66)=party
Number Vito_OnOff                "ONOFF Switch"      <switch>                (gHeating)                                              {channel="http:url:vitowifi:Channel_Vito_OnOff" ,   expire="5m"  }   

```

@J-N-K the example above already includes the delay parameter. It should be included in the regular description as well.

**Comment by J-N-K** [comment]
@s0170071 Can you prepare a PR for that? Or can you state that it's okay if I take it?

**Comment by s0170071** [comment]
I would appreciate it if you did it. Thank you.

Am 26. Dezember 2020 09:59:17 schrieb J-N-K <notifications@github.com>:
