### ISSUE TITLE
[enigma2] Refresh Interval not saved

### ISSUE THREAD

**Issue by pug304** [openhab/openhab-addons#9557]
After setting Refresh Interval to another value then default of 5 and restart of openhab service the default value 5 is back again. Aslong you don't restart teh service the new value ist valid and used. But new value is not saved permanent

Used: binding: Binding-enigma2 3.1.0.snapshot Build #2103, configured via UI

UID: enigma2:device:x_x_x_x
label: PVR
thingTypeUID: enigma2:device
configuration:
  host: x.x.x.x
  refreshInterval: 120
  timeout: 5

**Comment by t2000** [comment]
> Aslong you don't restart teh service the new value ist valid and used
To me this looks like it is correctly implemented in the binding.

How did you specify your `Thing`? Is it in a `*.things` file within the `things` directory? I assume that this is the case, because this means that your `Thing` is read-only for the UIs.

Try deleting the `Thing` from your ´*.things` file and create it via the OH3 Web UI. Afterwards you should be able to change the refresh interval and also restart the openhab service which should then still use the new value.

**Comment by lsiepel** [comment]
@pug304 Did the suggestion from t2000 help?

**Comment by pug304** [comment]
to be honest: to long ago, i don't remember

**Comment by lsiepel** [comment]
In that case, i close this issue as besides your comment,  there dont seem to be more reports. If needed the issue can always be re-opened.
