### ISSUE TITLE
[jdbc.mysql] MySQL migration - Items table is not used for index but creates a new table called items

### ISSUE THREAD

**Issue by CrispinPZA** [openhab/openhab-addons#9637]
Migration fro OH2.5.11 to 3.0

As part of the upgrade and persistence migration from old mysql to jdbc, you have to change the config to ensure it keeps your item mappings.

However, even if you use the recommended config
```

tableNamePrefix=Item
tableUseRealItemNames=false
tableIdDigitCount=0
```
it uses an index table called items and not Items. As a result, everything is out of whack as OH reindexes all items requiring persistence. 

I assume this is not by-design?

**Comment by lolodomo** [comment]
@jlaur : could it be something you recently fixed ?

**Comment by jlaur** [comment]
> @jlaur : could it be something you recently fixed ?

No, this is not fixed - still hardcoded:
https://github.com/openhab/openhab-addons/blob/160e0c2548f0110799e8f55cc6fc82128b03b8a9/bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/dto/ItemsVO.java#L30

No usages:
https://github.com/openhab/openhab-addons/blob/160e0c2548f0110799e8f55cc6fc82128b03b8a9/bundles/org.openhab.persistence.jdbc/src/main/java/org/openhab/persistence/jdbc/dto/ItemsVO.java#L56-L58

Besides this, queries are prepared for using the table name put here.

Some care needs to go into supporting this and all migration paths must be verified and covered. There is no _old_ and _new_ when doing a migration, only _new_. So once this table is named differently in config, the migration wouldn't know where to find the definitions from the _old_ table. It would be possible to configure the table name, but users would need to manually rename the table accordingly - at least with current code.

I'm wondering if it would be better to perform migrations from the console so they could be "steered" more precisely, rather than using the `rebuildTableNames` configuration option and assume/analyze things. On the other hand, this could scare some users.

I'll think about how this could be approached, and might be able to do something soon.

Do you have any ideas? Migration is an action which should be initiated by the user, and currently the way to do this is to temporarily enable migration in configuration (with `rebuildTableNames`), then disable it again once it's done. This seems cumbersome to me, but besides console, I'm not aware how this process could be integrated into the UI. On the other hand, the naming scheme to migrate **to** must be configured, so configuration and migration goes hand in hand.
