### ISSUE TITLE
[avmfritz] FritzBox thing goes offline after some time or after restart

### ISSUE THREAD

**Issue by lhurt** [openhab/openhab-addons#9768]
My FritzBox can be added as a thing via UI and usually connects right away. After some random time, after ObenHAB restart or disabling and re-enabling the thing goes offline and puts strange output in my OpenHAB log.

## Expected Behavior
The binding should be stable, stay online as long as the boxes do, come up safely on restart and be disabled and enabled at any time.

## Current Behavior
- The thing can be added without any problem and usually comes online hereafter
- After some time which can be seconds hours or even days the thing goes offline and tries to go online again without success
- Sometimes it's possible get it up again by disabling and re-enabling after some time
- Please refer to [this thread](https://community.openhab.org/t/avm-fritz-binding-loses-connection-after-some-hours/107096?u=dolittle) that that it's not only me observing this issue.

### Here are my log files.
[openhab_event_log.txt](https://github.com/openhab/openhab-addons/files/5792519/openhab_event_log.txt)
[openhab_trace_log.txt](https://github.com/openhab/openhab-addons/files/5792520/openhab_trace_log.txt)
I've added some remarks about my actions between the lines to make it easier to understand what happended.

### Remarks
- It seemed like changing the password of the user increases the probability that the binding goes ONLINE again after saving it to the thing
- Changing the sync timeout seemed to have some positive effect in some situations. Very vague guess though.

### Additional minor issues not related to the bug
- The UI doesn't check the max. user password lenght of 32 characters.
- Saving a changed password to the disabled binding causes the Exception: `Exception during HTTP PUT request for update config at 'things/avmfritz:fritzbox:192_168_1_5/config'`

## Possible Solution
- Not sure if it is relate to #9731 

## Steps to Reproduce (for Bugs)
1. Add thing via UI (not in the logs)
2. Disable thing
3. Enable thing
4. Wait

## Context
Used for call and availability monitoring

## Your Environment
* Version used: OpenHAB 3.0.0, same for binding
* Docker installation on Ubuntu 20.04 LTS
* Two FritzBoxes
* Call monitoring is enabled
* Access to Smart Home should be granted (wouldn't go ONLINE at all otherwise, wouldn't it?)

### Thing definition code
UID: avmfritz:fritzbox:192_168_1_5
label: Fritzbox-7560
thingTypeUID: avmfritz:fritzbox
configuration:
  syncTimeout: 5000
  protocol: http
  password: <my password>
  asyncTimeout: 10000
  ipAddress: 192.168.1.5
  pollingInterval: 60
  user: openhab
location: Büro

**Comment by konfetti72** [comment]
I can confirm this behavior (since a long time). 
One problem is from my perspective the missing handling of the BlockTime. You can see it in the trace log from lhurt ("<BlockTime>34</BlockTime>"). This is a time in seconds where the box does not accept any log-in. Sending in that timeframe a new log-in request leads to an increase of BlockTime.

**Comment by cweitkamp** [comment]
Okay. Thanks. It is good to have this written down in an issue to keep track on it. I will tr to look into it and find an improvement.

**Comment by wakkomon** [comment]
I can confirm this Issue. Having Problems with connction to Fritzbox every 3-7 hours. Only a Restart of OpenHAB service helps. Uninstalling and reinstalling Addon does NOT help.

I tacked the Issue a littlebit further and set up a Proxy in between Fritzbox and OpenHAB to see what happens.
I Also uses rieshark for tracking directly without HTTP-proxy.

OpenHAB does not send ANY http requests to Fritzbox after this time when conneciton gets lost, It does not try to reconnect. so it seems not to be a Fritzbox Issue. I can see Pending TCP connections from Openhab/Java in Status CLOSE_WAIT to target(tested with proxy and without/fritzbox directly) that do not close. Forcing to close the connections by linux kernel does not help/work in my environment. 

it looks like the addon or java cannot handle the TCP connctions after stalling and then openhab core/addon or java or whatever is responsible for the connection(i am not a developer just an administrator)

i also testet openhabinstallation on ubuntu and openhabian with same results, did a intallaiton from scratch also without importing a backup. i had this problem since last openhab 2 versoin and also in openhab 3.

hope this informaiton will help some way

**Comment by konfetti72** [comment]
A short update from my investigations and trials the last time. 

Since one week I use OH 3.1.0 Snapshot (build #2144) and what should I see, I have not a single broken connection to the fritzbox. I must add, that I have also added the tr064 binding and add items and rules to it (just to mention it, don't know if this can have a positive side effect).

Some other investigations I have done with 3.0.0 before changing to 3.1.0. I have added a polling thread to FritzAhaWebInterface which polls all 5 seconds the connection (WEBSERVICE_PATH). The following happens:

- the amount of connection lost increases significantly
- not only the avmfritz binding was effected, also homematic, openweathermap and some other stop working

A further investigation shows, that all bindings using getCommonHttpClient are effected from it. All other which uses own implementations like HUE and those which uses createHttpClient are not effected.

Not sure if something has changed from 3.0.0 to 3.1.0 #2144 in jetty implementation but currently it looks a little bit like a problem with jetty in 3.0.0. But that is more a good feeling from me.

Br,
Stefan

**Comment by ironator** [comment]
Would be interesting if there is a change for the OH 3.1.0 Snapshot, maybe something which may come by a changed getCommonHttpClient handler. This bug is very annoying to me, but I'm struggling with the consequences to change again to the Snapshot Release path.

**Comment by wakkomon** [comment]
YES i can confirm my issue with fritzbox connection loss is also gone using openHAB 3.1.0 snapshot build 2200

**Comment by ironator** [comment]
Ok, thanks to @wakkomon hint, I updated yesterday to the OH 3.1.0 Milestone 1 Release and my OH runs the first time in months for more than a day without losing connectivity to the Fritzbox!

**Comment by msebald** [comment]
I can confirm this for me and also a friend. The Fritzbox thing goes offline after a while. This can be some hours or some days after a restart of OH2/OH3, most likely it is about a day until the thing goes offline.

When I alter the authentication (changing HTTP to HTTPS and also the ports, or vise versa) the thing sometimes comes back online.

As mentioned, I have this problem for a long time now, also in OH2. And now in OH3. It never bugged me much as I not really use the binding. I only have a DECT repeater with a temperature sensor behind the Fritzbox. For my friend this is different as he has many AVM devices behind the Fritzbox.

**Comment by lhurt** [comment]
Works for me with 3.1.0 now.

Closing this issue.
