### ISSUE TITLE
[radiothermostat] Remote Temperature/Mode

### ISSUE THREAD

**Issue by rstevenson** [openhab/openhab-addons#9807]
I'm currently using a wrapper python/homie implementation and looking to switch to this binding. 
One of my main uses is to send an average temperature of my house to the remote temperature of the API. 

This really enables remote sensors and a smarter thermostat.

some more technical details

http address is: http://<ip-address>/tstat/remote_temp

Attributes are:
- rem_mode which is read/write
- rem_temp which is write only

**Comment by rstevenson** [comment]
@mlobstein I'll get it installed, test it out and report back. thanks!

**Comment by rstevenson** [comment]
@mlobstein it works for me. The only part i didn't find intuitive was setting it to -1 to turn off the remote mode but that can be put into the documentation

**Comment by mlobstein** [comment]
@rstevenson thanks for the feedback. I struggled on how to implement this as a single channel. It did not make sense to have a separate channel to turn 'on' rem_mode since the only way to turn it on is to send a value to rem_temp. Therefore a channel for rem_mode would only be used to turn 'off' remote mode. So I settled on using -1 to disable remote mode and documented it in the README. If this functionality works for you please close the issue.

**Comment by rstevenson** [comment]
It works for me. closed

**Comment by mlobstein** [comment]
An enhancement to implement rounding of the value sent to the remote temperature channel is being implemented by #20207
