### ISSUE TITLE
[iCalendar] suddenly stops working

### ISSUE THREAD

**Issue by GekoCH** [openhab/openhab-addons#9827]
The iCalendar binding did work for several days without any problmes no I get this error:

```
2021-01-15 08:41:35.371 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar timed out (waited too long for headers).
2021-01-15 08:41:35.372 [DEBUG] [g.icalendar.internal.handler.PullJob] - TimeoutException message is: null
```

I download and ICS file from nextcloud via:
https://***/remote.php/dav/public-calendars/J9Kq9H979DaJQwEK?export

When I curl -L the command on the olpenHAB server it does work so there is no ip block or what so ever 

Any Idea?

**Comment by daMihe** [comment]
I'm not sure, whether this is a client side bug. As the message is relatively clear and i have no additional data about this problem, i can't analyse it. The best "from outside" would an http-server (not https) and a packet trace.

Does this message repeat?

**Comment by GekoCH** [comment]
yes it does repeat
![image](https://user-images.githubusercontent.com/3285638/105317422-759df000-5bc2-11eb-9d88-0038c62e5bbb.png)

So I now activated the TRACE log for the iCalendar binding

**Comment by daMihe** [comment]
Okay, so the error handling works fine. In my eyes the server is not responding correctly. Please look into a general debug log (that will be verbose and should show interactions with parts of the framework, warning: that will contain your personal data), and do a packet trace to ensure the server is really responding. If you are hosting yourself, please also check the server logs.

**Comment by GekoCH** [comment]
hmm sorry currently I don't know how to do that ("general debug log" where is this located an on which machine (openhab or nextcloud))). The nextcloud instance I host myself but here are no errors in the log files.

**Comment by ekkards** [comment]
started from fresh: 
* log:set TRACE org.openhab.binding.icalendar

Create Thing with 
* iCal url from iCloud (150 chars long, replaced webdav:// with https:// 
* checked URL and it works with curl, 
* entered 60 (min) refresh)

But thing stays OFFLINE
```
11:30:53.581 [DEBUG] [dar.internal.handler.ICalendarHandler] - The calendar is currently offline as no local copy exists. It will go online as soon as a valid valid calendar is retrieved.
....many other items from other sources, 1 min later
11:31:53.583 [WARN ] [ng.icalendar.internal.handler.PullJob] - Download of calendar timed out (waited too long for headers).
11:31:53.583 [DEBUG] [ng.icalendar.internal.handler.PullJob] - TimeoutException message is: null
```

**Comment by daMihe** [comment]
Please do not only set iCalendar to debug as the http client is not inside the binding but in the framework instead. To set the levels higher you have to set at least the `ROOT`-Logger to debug. Depending on you configuration, you need to set also further Loggers to `DEBUG`. For a list of available commands about logging see [Karaf Docs](https://karaf.apache.org/manual/latest/#_commands_2).

**Comment by ekkards** [comment]
We could rename the title to "iCalendar suddenly starts working again"
Upon restart much later the same day (due to other stuff), the following happened (unfortunately with the previous setting of limited logs)
from openhab.log
```
2021-01-21 22:57:15.136 [INFO ] [.core.internal.i18n.I18nProviderImpl] - Time zone set to 'Europe/Berlin'.
2021-01-21 22:57:15.147 [INFO ] [.core.internal.i18n.I18nProviderImpl] - 
.....
2021-01-21 22:57:18.711 [INFO ] [org.openhab.ui.internal.UIService   ] - Started UI on port 8080
....
2021-01-21 22:57:18.981 [DEBUG] [ar.internal.handler.ICalendarHandler] - The calendar is currently offline as no local copy exists. It will go online as soon as a valid valid calendar is retrieved.
```
and then 1 hour later in the events.log:
```
2021-01-21 23:57:20.036 [INFO ] [openhab.event.ThingStatusInfoEvent  ] - Thing 'icalendar:calendar:d3255a0c42' updated: ONLINE
```
and the last event repeats every hour.
Code shows https://github.com/openhab/openhab-addons/blob/8da4d4d0cb9698511a4a76e1b0a4b9141d7f28ab/bundles/org.openhab.binding.icalendar/src/main/java/org/openhab/binding/icalendar/internal/handler/ICalendarHandler.java#L162 that there was no file and next retrieval is scheduled (with my config) as 60 min later and then it could retrieve it.

Now its working - and I am afraid I cannot add anything more to the issue just for now.

Conclusion: It took a restart and 1 retrieval interval.

**Comment by GekoCH** [comment]
same here after a reboot an reinitialize I don't get any more erros form the iCalendar binding

**Comment by J-N-K** [comment]
Seems to be solved

**Comment by t2000** [comment]
Unfortunately this issue is NOT solved :(

I am running on 3.1.0-SNAPSHOT - Build #2221 and just experienced this as well:

```
2021-03-04 16:52:49.317 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar timed out (waited too long for headers).
2021-03-04 16:54:23.288 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar timed out (waited too long for headers).
2021-03-04 16:54:23.290 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar timed out (waited too long for headers).
2021-03-04 16:57:23.290 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar timed out (waited too long for headers).
```

I just noticed this in my logs. When this first ocured I had my webserver in mind, because there had been some changes too. However, this is not the case. This is because there is absolutely NO entry that openHAB tries to query the nextcloud calendars.

I tried to disable/enable the icalender bridges and its things, this didn't get it back to work. Then I had a an issue in mind that the binding itself is in an inconsistent state, so I restarted the "icalendar" bundle and removed the icalendar cache files first. 

Result were OFFLINE icalendar bridges and thing and it couldnt download any file.

Now comes the "interesting part": What I also noticed is that my 2 miio vaccuum things where OFFLINE too! I haven't checked yet, but as far as I know they are also communication via http with the devices.

So I am assuming that this is a bigger issue, namely the jetty server from the framework kills itself/runs into an inconsistent state and afterwards no some (all) http requests from opeHAB run into timeouts.

Just before OH 3 was released I had fixed one of such issues https://github.com/openhab/openhab-addons/issues/9428 where the robonect binding killed the common jetty service. Maybe this issue here is similar to that, except for that it takes a while until it kicks in.

Can we please re-open this issue, or shall I create an additional one?

**Comment by arjan-io** [comment]
Same issue here. After a few weeks of using the iCalendar binding I too have the `Download of calendar timed out (waited too long for headers).` warning. A restart of OH did solve the issue. Nothing else in the logs. Running OH 3.1.0 stable.

**Comment by daMihe** [comment]
This is not a systematic issue with icalendar. The scheduling of the download works, the download (performed by the openhab framework) fails. I can't research this without more information. Please post a list of installed plugins and an output of `dmesg -T` just before the issue happens. You can use the "last_update" channel to identify the time the issue occurs.

In my case it was caused by an flaky wifi connection. I have not researched further, as i'm doing a restart of openhab when the connection changes now. However, for more investigation, i need more information.

**Comment by izharm** [comment]
I think this [https://community.openhab.org/t/solved-httpclient-keeps-failing-get-request-after-onqueued-with-timeout/118320](url) is the same issue and a possible workaround

In the mean time, is anyone aware of a way to restart the httpClient without restarting openhab ?

**Comment by CSchlipp** [comment]
+1, faced this issue today as well. 
@J-N-K: Could you please reopen this issue again? Thanks!

**Comment by t2000** [comment]
I finally hit it again and found some time to analyze the issue a bit:

For me all started with a:
```
2021-11-30 10:37:27.920 [WARN ] [g.icalendar.internal.handler.PullJob] - Response status for getting "https://URL" was 503 instead of 200. Ignoring it.
```
Which might have been caused by a nextcloud update that I ran on my server.

Afterwards this started:
```
2021-11-30 10:52:47.309 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar timed out (waited too long for headers).
```

And in addition I also saw:

```
2021-12-06 03:23:47.742 [WARN ] [g.icalendar.internal.handler.PullJob] - Download of calendar failed.
```

However, the most interesting thing for me is this line:

```
2021-12-22 18:13:47.571 [DEBUG] [g.icalendar.internal.handler.PullJob] - ExecutionException message is: Max requests queued per destination 1024 exceeded for HttpDestination[https://<HOST OF URL>]@7fc1029,queue=1024,pool=DuplexConnectionPool@50812a46[c=0/2/2,a=2,i=0,q=1024]
```

Apparently the shared `httpclient` gets flooded with requests until its is full for a destination. One destination seems to be one hostname.

I think that the solution to this is canceling the request once we hit an exception, which will then also dequeue that request from the shared `httpclient` and hence not block it.
