### ISSUE TITLE
[mapdb] addon docs are missing

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab-addons#9884]
There is no documentation of the mapdb persistence addon at https://www.openhab.org/addons/.

In fact it looks like it doesn't even exist in OH3 anymore.

![image](https://user-images.githubusercontent.com/1270359/105107131-a9d8ba00-5ab7-11eb-8dac-595d42420426.png)

**Comment by dilyanpalauzov** [comment]
MapDB is present at https://v2.openhab.org/addons/persistence/mapdb/ and missing from https://www.openhab.org/addons/persistence/rrd4j/ .  This suggests, that MapDB stopped working with OH 3.

It appears however in the integrated in OH 3.2 Market place.  I do use it in OH 3.2 without problems (since yesterday).  https://github.com/openhab/openhab-addons/issues/8794 updates MapDB to work with OH3.  That said, I assume MapDB does work under OH 3.2 correctly.

* Mention MapDB on the left of https://www.openhab.org/addons/persistence/rrd4j/ under “Data Persistence”.

**Comment by jlaur** [comment]
Resolved by #13964.
